Repository LuccaSA/lucca-front, pull requests merged in 2018-08, with the labels that each got.

#348 Clearer
  packages/ng/docs/demo/src/app/select/basic/basic.html
  packages/ng/libraries/core/src/lib/input/clearer/clearer.model.ts
  packages/ng/libraries/core/src/lib/input/clearer/index.ts
  packages/ng/libraries/core/src/lib/input/index.ts
  packages/ng/libraries/core/src/lib/select/clearer/index.ts
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.html
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.scss
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.ts
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.module.ts
  packages/ng/libraries/core/src/lib/select/index.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.component.html
  packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
  packages/ng/libraries/core/src/lib/select/select.module.ts
Labels: enhancement, ng

#360 [NG] Selects common style
  packages/ng/docs/demo/src/app/api/select/api-select.module.ts
  packages/ng/docs/demo/src/app/api/select/basic/basic.html
  packages/ng/docs/demo/src/app/select/basic/basic.html
  packages/ng/docs/demo/src/app/user/select/basic/basic.html
  packages/ng/docs/demo/src/app/user/select/searcher/searcher.html
  packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.html
  packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.scss
  packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
  packages/ng/libraries/core/src/lib/option/item/option-item.component.scss
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.scss
  packages/ng/libraries/core/src/lib/select/input/select-input.common.scss
  packages/ng/libraries/core/src/lib/select/input/select-input.component.html
  packages/ng/libraries/core/src/lib/select/input/select-input.component.scss
  packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
  packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
  packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.scss
  packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts
Labels: ng

#366 [ng][enh] Select additionnal styles
  packages/ng/libraries/core/src/lib/option/item/option-item.component.scss
  packages/ng/libraries/core/src/lib/option/operator/options/options.component.scss
  packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.scss
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.scss
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.scss
  packages/ng/libraries/core/src/lib/select/input/select-input.common.scss
Labels: ng

#369 Select.cleanup
  packages/ng/docs/demo/src/app/select/basic/basic.html
  packages/ng/libraries/core/src/lib/input/displayer/input-displayer.directive.ts
  packages/ng/libraries/core/src/lib/input/displayer/input-displayer.model.ts
  packages/ng/libraries/core/src/lib/option/displayer/index.ts
  packages/ng/libraries/core/src/lib/option/displayer/option-displayer.component.html
  packages/ng/libraries/core/src/lib/option/displayer/option-displayer.component.scss
  packages/ng/libraries/core/src/lib/option/displayer/option-displayer.component.ts
  packages/ng/libraries/core/src/lib/option/displayer/option-displayer.module.ts
  packages/ng/libraries/core/src/lib/option/index.ts
  packages/ng/libraries/core/src/lib/option/operator/options/options.component.ts
  packages/ng/libraries/core/src/lib/option/option.module.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
Labels: enhancement

#371 Select.support.multiple
  packages/ng/docs/demo/src/app/select/basic/basic.html
  packages/ng/docs/demo/src/app/select/multiple/multiple.html
  packages/ng/docs/demo/src/app/select/multiple/multiple.ts
  packages/ng/docs/demo/src/app/select/select.component.html
  packages/ng/docs/demo/src/app/select/select.component.ts
  packages/ng/docs/demo/src/app/select/select.module.ts
  packages/ng/libraries/core/src/lib/input/displayer/input-displayer.directive.ts
  packages/ng/libraries/core/src/lib/input/displayer/input-displayer.model.ts
  packages/ng/libraries/core/src/lib/input/picker/input-picker.model.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.html
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
Labels: enhancement

#378 [NG] Extract styles into style mixins
  packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.scss
  packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.component.scss
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.component.ts
  packages/ng/libraries/core/src/lib/option/item/option-item.component.scss
  packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.scss
  packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.ts
  packages/ng/libraries/core/src/lib/option/operator/searcher/searcher.common.scss
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.scss
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.scss
  packages/ng/libraries/core/src/lib/select/input/select-input.common.scss
  packages/ng/libraries/core/src/lib/select/input/select-input.component.scss
  packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
  packages/ng/libraries/core/src/lib/user/picture/user-picture.component.scss
  packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.scss
  packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts
  packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.component.scss
  packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.component.ts
  packages/ng/libraries/core/src/lib/user/tile/user-tile.component.scss
  packages/ng/libraries/core/src/style/_definitions.scss
  packages/ng/libraries/core/src/style/definitions/option/_option-item.scss
  packages/ng/libraries/core/src/style/definitions/option/_option-picker.scss
  packages/ng/libraries/core/src/style/definitions/option/_option-searcher.scss
  packages/ng/libraries/core/src/style/definitions/select/_select-clearer.scss
  packages/ng/libraries/core/src/style/definitions/select/_select-input.scss
  packages/ng/libraries/core/src/style/definitions/user/user-picture.scss
  packages/ng/libraries/core/src/style/definitions/user/user-tile.scss
  packages/ng/libraries/core/src/style/main.scss
  packages/ng/yarn.lock
Labels: ng
