Repository LuccaSA/lucca-front, pull requests merged in 2018-05, with the labels that each got.

#276 [NG] Adds Enter and leave animation timing and trigger naming
  packages/ng/CHANGELOG.md
  packages/ng/src/app/animations/animation.factory.ts
  packages/ng/src/app/animations/fade.animation.ts
  packages/ng/src/app/animations/scale.animation.ts
  packages/ng/src/app/animations/slide.animation.ts
Labels: ng

#281 Icons.18.05.03
  packages/icons/CHANGELOG.md
  packages/icons/demo/mapping.js
  packages/icons/font/lucca-icons.eot
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/selection.json
  packages/scss/demo/demo.js
Labels: enhancement, icon

#296 Migrate.core.select
  packages/ng/libraries/core/src/lib/index.ts
  packages/ng/libraries/core/src/lib/module.ts
  packages/ng/libraries/core/src/lib/select/clearer/index.ts
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer-first.component.spec.ts
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer-first.component.ts
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.html
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.scss
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.spec.ts
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.ts
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.model.ts
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.module.ts
  packages/ng/libraries/core/src/lib/select/directive/index.ts
  packages/ng/libraries/core/src/lib/select/directive/select.directive.module.ts
  packages/ng/libraries/core/src/lib/select/directive/select.directive.spec.ts
  packages/ng/libraries/core/src/lib/select/directive/select.directive.ts
  packages/ng/libraries/core/src/lib/select/index.ts
  packages/ng/libraries/core/src/lib/select/option/feeder/index.ts
  packages/ng/libraries/core/src/lib/select/option/feeder/select-option-feeder.directive.ts
  packages/ng/libraries/core/src/lib/select/option/feeder/select-option-feeder.model.ts
  packages/ng/libraries/core/src/lib/select/option/feeder/select-option-feeder.module.ts
  packages/ng/libraries/core/src/lib/select/option/index.ts
  packages/ng/libraries/core/src/lib/select/option/select-option.component.html
  packages/ng/libraries/core/src/lib/select/option/select-option.component.scss
  packages/ng/libraries/core/src/lib/select/option/select-option.component.spec.ts
  packages/ng/libraries/core/src/lib/select/option/select-option.component.ts
  packages/ng/libraries/core/src/lib/select/option/select-option.event.ts
  packages/ng/libraries/core/src/lib/select/option/select-option.module.ts
  packages/ng/libraries/core/src/lib/select/picker/index.ts
  packages/ng/libraries/core/src/lib/select/picker/select-picker.component.html
  packages/ng/libraries/core/src/lib/select/picker/select-picker.component.scss
  packages/ng/libraries/core/src/lib/select/picker/select-picker.component.spec.ts
  packages/ng/libraries/core/src/lib/select/picker/select-picker.component.ts
  packages/ng/libraries/core/src/lib/select/picker/select-picker.module.ts
  packages/ng/libraries/core/src/lib/select/picker/select.template.ts
  packages/ng/libraries/core/src/lib/select/scroll/index.ts
  packages/ng/libraries/core/src/lib/select/scroll/picker/index.ts
  packages/ng/libraries/core/src/lib/select/scroll/picker/select-scroll-picker.component.html
  packages/ng/libraries/core/src/lib/select/scroll/picker/select-scroll-picker.component.scss
  packages/ng/libraries/core/src/lib/select/scroll/picker/select-scroll-picker.component.ts
  packages/ng/libraries/core/src/lib/select/scroll/picker/select-scroll-picker.model.ts
  packages/ng/libraries/core/src/lib/select/searcher/index.ts
  packages/ng/libraries/core/src/lib/select/searcher/select-searcher.component.html
  packages/ng/libraries/core/src/lib/select/searcher/select-searcher.component.scss
  packages/ng/libraries/core/src/lib/select/searcher/select-searcher.component.spec.ts
  packages/ng/libraries/core/src/lib/select/searcher/select-searcher.component.ts
  packages/ng/libraries/core/src/lib/select/searcher/select-searcher.model.ts
  packages/ng/libraries/core/src/lib/select/searcher/select-searcher.module.ts
  packages/ng/libraries/core/src/lib/select/select.component.html
  packages/ng/libraries/core/src/lib/select/select.component.scss
  packages/ng/libraries/core/src/lib/select/select.component.spec.ts
  packages/ng/libraries/core/src/lib/select/select.component.ts
  packages/ng/libraries/core/src/lib/select/select.module.ts
  packages/ng/libraries/core/src/lib/select/utils/index.ts
  packages/ng/libraries/core/src/lib/select/utils/select-searcher.intl.ts
  packages/ng/libraries/core/src/lib/select/utils/select-utils.factory.ts
Labels: enhancement, ng

#301 fix dependencies in ng sub package
  packages/ng/libraries/core/package.json
Labels: ng

#306 demo/formly works with minimal effort
  packages/ng/docs/demo/src/app/app.module.ts
  packages/ng/docs/demo/src/app/formly/basic/basic.html
  packages/ng/docs/demo/src/app/formly/basic/basic.ts
  packages/ng/docs/demo/src/app/formly/change/change.html
  packages/ng/docs/demo/src/app/formly/change/change.ts
  packages/ng/docs/demo/src/app/formly/fieldgroup/fieldgroup.html
  packages/ng/docs/demo/src/app/formly/fieldgroup/fieldgroup.ts
  packages/ng/docs/demo/src/app/formly/formly.component.html
  packages/ng/docs/demo/src/app/formly/formly.component.ts
  packages/ng/docs/demo/src/app/formly/formly.module.ts
  packages/ng/docs/demo/src/app/formly/formly.router.ts
  packages/ng/docs/demo/src/app/formly/option/option.html
  packages/ng/docs/demo/src/app/formly/option/option.ts
  packages/ng/docs/demo/src/app/formly/validation/validation.html
  packages/ng/docs/demo/src/app/formly/validation/validation.ts
  packages/ng/docs/demo/src/app/navigation/navigation.router.ts
Labels: ng

#282 Scss.figgo.misc.revisions
  packages/scss/CHANGELOG.md
  packages/scss/demo/components/breadcrumb.html
  packages/scss/demo/components/cards.html
  packages/scss/demo/components/forms/forms-textfields.html
  packages/scss/demo/includes/demo-main-content.html
  packages/scss/demo/includes/demo-menu.html
  packages/scss/demo/templates/form.html
  packages/scss/src/_components.scss
  packages/scss/src/components/_breadcrumb.scss
  packages/scss/src/components/_card.scss
  packages/scss/src/components/_content-section.scss
  packages/scss/src/components/_form.scss
  packages/scss/src/components/inputs/textfield/_textfield.material.scss
  packages/scss/src/components/inputs/textfield/_textfield.scss
  packages/scss/src/theming/_commons.scss
  packages/scss/src/theming/_components.scss
  packages/scss/src/theming/components/_content-section.theme.scss
  packages/scss/src/theming/components/_form.theme.scss
  packages/scss/src/theming/components/_textfield.theme.scss
Labels: bug, enhancement, scss

#311 Formly.version
  packages/ng/docs/demo/src/styles.scss
  packages/ng/libraries/core/src/lib/user/picture/user-picture.component.scss
  packages/ng/libraries/core/src/style/_theming.scss
  packages/ng/libraries/formly/package.json
  packages/ng/libraries/material/package.json
  packages/ng/libraries/material/src/style/_theming.scss
  packages/ng/package.json
  packages/ng/tsconfig.json
  packages/ng/yarn.lock
Labels: ng

#314 Fix.build.ng
  package.json
  packages/ng/docs/demo/src/app/animation/fading/fading.ts
  packages/ng/docs/demo/src/app/animation/scaling/scaling.ts
  packages/ng/docs/demo/src/app/animation/sliding/sliding.ts
  packages/ng/docs/demo/src/app/api/api-select/api-select.module.ts
  packages/ng/docs/demo/src/app/api/api-select/basic/rdd-select-feeder.ts
  packages/ng/docs/demo/src/app/api/api-select/custom/custom-select-feeder.ts
  packages/ng/docs/demo/src/app/api/api.module.ts
  packages/ng/docs/demo/src/app/app.component.html
  packages/ng/docs/demo/src/app/empty/empty.module.ts
  packages/ng/docs/demo/src/app/formly/formly.module.ts
  packages/ng/docs/demo/src/app/popover/basic/basic.ts
  packages/ng/docs/demo/src/app/popover/popover.module.ts
  packages/ng/docs/demo/src/app/select/clearer/clearer.module.ts
  packages/ng/docs/demo/src/app/select/feeder/basic/feeder-select-picker.ts
  packages/ng/docs/demo/src/app/select/feeder/feeder.module.ts
  packages/ng/docs/demo/src/app/select/mod-select/mod-select.module.ts
  packages/ng/docs/demo/src/app/select/searcher/searcher-demo.intl.ts
  packages/ng/docs/demo/src/app/select/searcher/searcher.module.ts
  packages/ng/docs/demo/src/app/select/select.module.ts
  packages/ng/docs/demo/src/app/shared/redirect/redirect.module.ts
  packages/ng/docs/demo/src/app/user/display/user-display.module.ts
  packages/ng/docs/demo/src/app/user/picture/basic/basic.ts
  packages/ng/docs/demo/src/app/user/picture/user-picture.module.ts
  packages/ng/docs/demo/src/app/user/select/basic/basic.ts
  packages/ng/docs/demo/src/app/user/select/user-select-basic.module.ts
  packages/ng/docs/demo/src/app/user/tile/basic/basic.component.ts
  packages/ng/docs/demo/src/app/user/tile/displayFormat/display-format.component.ts
  packages/ng/docs/demo/src/app/user/tile/sizes/sizes.component.ts
  packages/ng/docs/demo/src/app/user/tile/user-tile.module.ts
  packages/ng/docs/demo/tsconfig.app.json
  packages/ng/libraries/core/ng-package.json
  packages/ng/libraries/core/src/lib/api/select/picker/api-select-picker.component.scss
  packages/ng/libraries/core/src/lib/popover/popover.component.scss
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.scss
  packages/ng/libraries/core/src/lib/select/scroll/picker/select-scroll-picker.component.scss
  packages/ng/libraries/core/src/lib/select/searcher/select-searcher.component.scss
  packages/ng/libraries/core/src/lib/select/select.component.scss
  packages/ng/libraries/core/src/lib/user/picture/user-picture.component.scss
  packages/ng/libraries/core/src/lib/user/tile/user-tile.component.scss
  packages/ng/libraries/core/src/style/_theming.scss
  packages/ng/libraries/formly/src/lib/formly.module.ts
  packages/ng/libraries/material/src/style/_theming.scss
  packages/ng/package.json
  packages/ng/tsconfig.json
Labels: bug, ng

#309 Icons.2018 05 16 + sortable table
  packages/icons/demo/mapping.js
  packages/icons/font/lucca-icons.eot
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/selection.json
  packages/icons/src/_mappings.scss
  packages/scss/CHANGELOG.md
  packages/scss/demo/components/tables.html
  packages/scss/demo/demo.js
  packages/scss/src/components/_table.scss
Labels: enhancement, icon, scss

#316 1.0.lerna
  README.md
  lerna.json
  packages/ng/libraries/core/package.json
  packages/ng/package.json
Labels: enhancement

#318 Ng.css.var.forever.together
  demo/package.json
  packages/ng/docs/demo/src/styles.scss
  packages/ng/libraries/core/src/lib/api/select/picker/api-select-picker.component.scss
  packages/ng/libraries/core/src/lib/popover/popover.component.scss
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.scss
  packages/ng/libraries/core/src/lib/select/scroll/picker/select-scroll-picker.component.scss
  packages/ng/libraries/core/src/lib/select/searcher/select-searcher.component.scss
  packages/ng/libraries/core/src/lib/select/select.component.scss
  packages/ng/libraries/core/src/lib/user/picture/user-picture.component.scss
  packages/ng/libraries/core/src/lib/user/tile/user-tile.component.scss
  packages/ng/libraries/core/src/style/_theming.scss
  packages/ng/libraries/material/src/style/_theming.scss
  packages/ng/libraries/material/src/style/components/_tooltip.scss
  packages/scss/src/_theming.overridable.scss
  packages/scss/src/_theming.scss
  packages/scss/src/main.cssvar.scss
  packages/scss/src/theming/_cssvars.scss
Labels: enhancement, ng
