Repository LuccaSA/lucca-front, pull requests merged in 2018-11, with the labels that each got.

#442 [fix] scss - Bottom section on compact
  packages/scss/demo/components/templates.html
  packages/scss/demo/demo.css
  packages/scss/demo/templates/compact-withBanner.html
  packages/scss/demo/templates/full-withBanner.html
  packages/scss/src/components/_main.scss
  packages/scss/src/components/_nav-side.scss
  packages/scss/src/theming/components/_nav-side.theme.scss
Labels: bug, scss

#451 [fix] update package.json for security alerts
  .travis.yml
  package-lock.json
  package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/scss/package-lock.json
  packages/scss/package.json
Labels: bug

#462 [fix] lu-select clearer causing unexpected form submit
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.html
Labels: bug, ng

#465 Fix.select.disabled
  packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
  packages/scss/src/components/inputs/textfield/_textfield.scss
Labels: bug, ng
