Repository LuccaSA/lucca-front, pull requests merged in 2018-10, with the labels that each got.

#368 Scss.small.device.containers.width
  packages/scss/CHANGELOG.md
  packages/scss/demo/templates/fullmenu.html
  packages/scss/demo/templates/side-cards.html
  packages/scss/demo/templates/side-filters.html
  packages/scss/demo/templates/side-header.html
  packages/scss/demo/templates/side-sections-header.html
  packages/scss/demo/templates/side-sections.html
  packages/scss/demo/templates/side.html
  packages/scss/src/components/_container.scss
  packages/scss/src/components/_nav-side.scss
Labels: bug, scss

#396 Scss.animation.theming
  packages/scss/CHANGELOG.md
  packages/scss/demo/components/animations.html
  packages/scss/src/theming/_commons.scss
  packages/scss/src/utilities/_animations.scss
  packages/scss/src/utilities/animations/_sliding.scss
Labels: enhancement, scss

#399 [FIX] Select & forms style
  packages/ng/docs/demo/src/app/select/foundations/basic/basic.html
  packages/ng/docs/demo/src/app/select/foundations/multiple/multiple.html
  packages/ng/docs/demo/src/app/select/multiple/basic/basic.html
  packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.html
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.component.html
  packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.html
  packages/ng/libraries/core/src/style/definitions/option/_option-item.scss
  packages/ng/libraries/core/src/style/definitions/select/_select-input.scss
  packages/ng/libraries/core/src/style/theme/_options.theme.scss
  packages/scss/src/components/inputs/field/_field.framed.scss
  packages/scss/src/components/inputs/field/_field.scss
  packages/scss/src/components/inputs/textfield/_textfield.material.scss
Labels: bug, ng

#427 Scss.theming.primary
  packages/ng/libraries/core/src/style/components/_popover.scss
  packages/ng/libraries/core/src/style/definitions/select/_select-clearer.scss
  packages/ng/libraries/core/src/style/definitions/select/_select-input.scss
  packages/ng/libraries/core/src/style/theme/_select.theme.scss
  packages/ng/libraries/formly/src/lib/wrappers/icon.html
  packages/ng/libraries/material/src/style/components/_datepicker.scss
  packages/scss/demo/components/forms/forms-files.html
  packages/scss/demo/components/forms/forms-radios.html
  packages/scss/demo/components/tooltips.html
  packages/scss/demo/includes/demo-main-content.html
  packages/scss/demo/includes/demo-menu.html
  packages/scss/src/_components.scss
  packages/scss/src/components/_box.scss
  packages/scss/src/components/_card.scss
  packages/scss/src/components/_tooltip.scss
  packages/scss/src/components/inputs/checkbox/_checkbox.scss
  packages/scss/src/components/inputs/file/_file.scss
  packages/scss/src/components/inputs/radio/_radio.scss
  packages/scss/src/components/inputs/switch/_switch.scss
  packages/scss/src/components/inputs/textfield/_textfield.framed.scss
  packages/scss/src/components/inputs/textfield/_textfield.material.scss
  packages/scss/src/components/inputs/textfield/_textfield.scss
  packages/scss/src/mixins/_forms.scss
  packages/scss/src/mixins/_loading.scss
  packages/scss/src/theming/_commons.scss
  packages/scss/src/theming/_components.scss
  packages/scss/src/theming/_palettes.scss
  packages/scss/src/theming/components/_action-icon.theme.scss
  packages/scss/src/theming/components/_loading.theme.scss
  packages/scss/src/theming/components/_textfield.theme.scss
Labels: bug, enhancement

#429 [scss] button font
  packages/scss/src/_typo.scss
  packages/scss/src/components/inputs/field/_field.scss
Labels: enhancement, scss

#431 [ng][fix] Select - isEmpty if empty array
  packages/ng/libraries/core/src/lib/select/input/select-input.model.ts
Labels: bug

#435 [SCSS][FIX] Unnesting fieldname-messages
  packages/scss/src/components/inputs/checkbox/_checkboxesfield.scss
  packages/scss/src/components/inputs/field/_field.scss
  packages/scss/src/components/inputs/radio/_radiosfield.scss
  packages/scss/src/components/inputs/textfield/_textfield.scss
Labels: bug, scss

#437 [NG][FIX] Select disabled state
  packages/ng/libraries/core/src/lib/api/select/input/api-select-input.component.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.component.ts
  packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts
Labels: bug, ng

#438 [NG][FIX] Select calls & Scrolls issues
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.component.ts
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.model.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
  packages/ng/libraries/core/src/lib/scroll/scroll.directive.ts
Labels: bug, ng

#448 ng-select [fix] clearer not working in forefox cuz the onclick was on…
  packages/ng/libraries/core/src/lib/select/clearer/select-clearer.component.html
Labels: bug
