Repository LuccaSA/lucca-front, pull requests merged in 2018-12, with the labels that each got.

#439 [feat] ng - Add luTooltipDisabled option
  packages/ng/docs/demo/src/app/tooltip/basic/basic.html
  packages/ng/libraries/core/src/lib/tooltip/trigger/tooltip-trigger.directive.ts
Labels: enhancement, ng

#450 [feat] rxjs pipe synthax
  packages/ng/docs/demo/src/app/shared/redirect/redirect.component.html
  packages/ng/docs/demo/src/app/shared/redirect/redirect.component.ts
  packages/ng/docs/demo/src/app/shared/redirect/redirect.interceptor.ts
  packages/ng/docs/demo/src/app/shared/redirect/redirect.service.ts
  packages/ng/libraries/core/package.json
  packages/ng/libraries/core/src/lib/api/select/feeder/api-feeder.component.ts
  packages/ng/libraries/core/src/lib/api/select/feeder/api-feeder.model.ts
  packages/ng/libraries/core/src/lib/api/select/pager/api-pager.component.ts
  packages/ng/libraries/core/src/lib/api/select/pager/api-pager.model.ts
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.component.ts
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.model.ts
  packages/ng/libraries/core/src/lib/index.ts
  packages/ng/libraries/core/src/lib/input/clearer/clearer.model.ts
  packages/ng/libraries/core/src/lib/input/picker/input-picker.model.ts
  packages/ng/libraries/core/src/lib/module.ts
  packages/ng/libraries/core/src/lib/number/number.module.ts
  packages/ng/libraries/core/src/lib/option/item/option-item.model.ts
  packages/ng/libraries/core/src/lib/option/item/option-item.module.ts
  packages/ng/libraries/core/src/lib/option/operator/feeder/option-feeder.component.ts
  packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts
  packages/ng/libraries/core/src/lib/option/operator/option-operator.model.ts
  packages/ng/libraries/core/src/lib/option/operator/pager/option-pager.component.ts
  packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
  packages/ng/libraries/core/src/lib/popover/panel/popover-panel.model.ts
  packages/ng/libraries/core/src/lib/popover/trigger/popover-trigger.model.ts
  packages/ng/libraries/core/src/lib/scroll/scroll.directive.ts
  packages/ng/libraries/core/src/lib/scroll/scroll.model.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.module.ts
  packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.component.ts
  packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.model.ts
  packages/ng/libraries/formly/package.json
  packages/ng/libraries/formly/src/lib/types/date.ts
  packages/ng/libraries/material/package.json
  packages/ng/package-lock.json
  packages/ng/package.json
Labels: enhancement, ng

#468 [feat] ng - update to angular 7
  packages/ng/.angular.json
  packages/ng/docs/demo/src/app/user/display/basic/basic.component.html
  packages/ng/docs/demo/src/polyfills.ts
  packages/ng/libraries/core/package.json
  packages/ng/libraries/core/src/lib/api/api.model.ts
  packages/ng/libraries/core/src/lib/user/picture/user-picture.component.ts
  packages/ng/libraries/formly/package.json
  packages/ng/libraries/material/package.json
  packages/ng/misc/api-doc.js
  packages/ng/package-lock.json
  packages/ng/package.json
Labels: ng

#494 release 2.1.0
  lerna.json
  package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/ng/.angular.json
  packages/ng/docs/demo/src/app/app.module.ts
  packages/ng/docs/demo/src/app/shared/redirect/redirect.component.html
  packages/ng/docs/demo/src/app/shared/redirect/redirect.component.ts
  packages/ng/docs/demo/src/app/shared/redirect/redirect.interceptor.ts
  packages/ng/docs/demo/src/app/shared/redirect/redirect.service.ts
  packages/ng/docs/demo/src/app/tooltip/basic/basic.html
  packages/ng/docs/demo/src/app/user/display/basic/basic.component.html
  packages/ng/docs/demo/src/app/user/select/basic/basic.ts
  packages/ng/docs/demo/src/app/user/select/scoped/scoped.html
  packages/ng/docs/demo/src/app/user/select/scoped/scoped.ts
  packages/ng/docs/demo/src/app/user/select/user-select.component.html
  packages/ng/docs/demo/src/app/user/select/user-select.component.ts
  packages/ng/docs/demo/src/app/user/select/user-select.module.ts
  packages/ng/docs/demo/src/polyfills.ts
  packages/ng/libraries/core/package.json
  packages/ng/libraries/core/src/lib/api/api.model.ts
  packages/ng/libraries/core/src/lib/api/select/feeder/api-feeder.component.ts
  packages/ng/libraries/core/src/lib/api/select/feeder/api-feeder.model.ts
  packages/ng/libraries/core/src/lib/api/select/pager/api-pager.component.ts
  packages/ng/libraries/core/src/lib/api/select/pager/api-pager.model.ts
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.component.ts
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.model.ts
  packages/ng/libraries/core/src/lib/index.ts
  packages/ng/libraries/core/src/lib/input/clearer/clearer.model.ts
  packages/ng/libraries/core/src/lib/input/picker/input-picker.model.ts
  packages/ng/libraries/core/src/lib/module.ts
  packages/ng/libraries/core/src/lib/number/number.module.ts
  packages/ng/libraries/core/src/lib/option/item/option-item.model.ts
  packages/ng/libraries/core/src/lib/option/item/option-item.module.ts
  packages/ng/libraries/core/src/lib/option/operator/feeder/option-feeder.component.ts
  packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts
  packages/ng/libraries/core/src/lib/option/operator/option-operator.model.ts
  packages/ng/libraries/core/src/lib/option/operator/pager/option-pager.component.ts
  packages/ng/libraries/core/src/lib/option/operator/searcher/option-searcher.component.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.model.ts
  packages/ng/libraries/core/src/lib/popover/panel/popover-panel.model.ts
  packages/ng/libraries/core/src/lib/popover/trigger/popover-trigger.model.ts
  packages/ng/libraries/core/src/lib/scroll/scroll.directive.ts
  packages/ng/libraries/core/src/lib/scroll/scroll.model.ts
  packages/ng/libraries/core/src/lib/select/input/select-input.module.ts
  packages/ng/libraries/core/src/lib/tooltip/trigger/tooltip-trigger.directive.ts
  packages/ng/libraries/core/src/lib/user/picture/user-picture.component.ts
  packages/ng/libraries/core/src/lib/user/select/input/user-select-input.component.ts
  packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.component.ts
  packages/ng/libraries/core/src/lib/user/select/searcher/user-searcher.model.ts
  packages/ng/libraries/formly/package.json
  packages/ng/libraries/formly/src/lib/types/date.ts
  packages/ng/libraries/material/package.json
  packages/ng/misc/api-doc.js
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/scss/package-lock.json
  packages/scss/package.json
Labels: enhancement

#516 [fix][SCSS] NavSide moving when scrolling on IE11
  packages/scss/CHANGELOG.md
  packages/scss/demo/templates/compact-withBanner.html
  packages/scss/demo/templates/full-withBanner.html
  packages/scss/demo/templates/fullmenu.html
  packages/scss/demo/templates/side-cards.html
  packages/scss/demo/templates/side-filters.html
  packages/scss/demo/templates/side-header.html
  packages/scss/demo/templates/side-sections-header.html
  packages/scss/demo/templates/side-sections.html
  packages/scss/demo/templates/side.html
  packages/scss/src/components/_main.scss
  packages/scss/src/components/_nav-side.scss
  packages/scss/src/theming/components/_nav-side.theme.scss
Labels: bug, scss

#524 [icons] reply, distribute, evolution
  packages/icons/CHANGELOG.md
  packages/icons/demo/mapping.js
  packages/icons/font/lucca-icons.eot
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/selection.json
  packages/scss/demo/demo.js
Labels: icon

#525 [fix] select height
  packages/ng/CHANGELOG.md
  packages/ng/libraries/core/src/style/definitions/select/_select-input.scss
  packages/ng/libraries/core/src/style/theme/_select.theme.scss
  packages/ng/package-lock.json
Labels: bug, ng

#526 [FIX][SCSS] Mobile menu height should be toggle size.
  packages/scss/src/components/_nav-side.scss
Labels: bug, scss

#530 [fix] ng-formly api without filters
  packages/ng/libraries/formly/src/lib/types/api.ts
Labels: bug, ng
