Repository LuccaSA/lucca-front, pull requests merged in 2019-02, with the labels that each got.

#549 [feat] tooltip positioning
  packages/ng/docs/demo/src/app/tooltip/basic/basic.html
  packages/ng/libraries/core/src/lib/popover/trigger/popover-trigger.model.ts
  packages/ng/libraries/core/src/lib/tooltip/panel/tooltip-panel.component.ts
  packages/ng/libraries/core/src/lib/tooltip/trigger/tooltip-trigger.directive.ts
  packages/ng/libraries/core/src/style/definitions/tooltip/_tooltip.scss
Labels: enhancement, ng

#550 [feat] lu for options optimizations
  packages/ng/docs/demo/src/app/select/option-picker/operator/operator.html
  packages/ng/docs/demo/src/app/select/option-picker/operator/operator.ts
  packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts
Labels: enhancement, ng

#557 [feat] Scss loading
  packages/scss/src/components/_loading.scss
  packages/scss/src/mixins/_loading.scss
  packages/scss/src/theming/components/_loading.theme.scss
Labels: enhancement, scss

#558 [feat] Scss radio button.theme
  packages/scss/CHANGELOG.md
  packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
  packages/scss/src/theming/components/_radio-buttons.theme.scss
Labels: enhancement, scss

#559 [feat] add a min width to select's options
  packages/ng/libraries/core/src/style/definitions/option/_option-picker.scss
Labels: enhancement, ng

#560 2.3.0
  lerna.json
  package-lock.json
  package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/ng/docs/demo/src/app/select/option-picker/operator/operator.html
  packages/ng/docs/demo/src/app/select/option-picker/operator/operator.ts
  packages/ng/libraries/core/package.json
  packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts
  packages/ng/libraries/core/src/lib/option/picker/option-picker.component.ts
  packages/ng/libraries/core/src/style/definitions/option/_option-picker.scss
  packages/ng/libraries/formly/package.json
  packages/ng/libraries/material/package.json
  packages/ng/package-lock.json
  packages/ng/package.json
  packages/scss/CHANGELOG.md
  packages/scss/package-lock.json
  packages/scss/package.json
  packages/scss/src/components/_header.scss
  packages/scss/src/components/_loading.scss
  packages/scss/src/components/inputs/radio-buttons/_radio-buttons.scss
  packages/scss/src/mixins/_loading.scss
  packages/scss/src/theming/components/_loading.theme.scss
  packages/scss/src/theming/components/_radio-buttons.theme.scss
Labels: enhancement, ng, scss

#561 [fix] Firefox compatibility issue
  packages/ng/libraries/core/src/lib/scroll/scroll.directive.ts
Labels: bug, ng

#569 [fix] Container width wasn't properly calculated
  packages/scss/src/components/_container.scss
Labels: bug, scss

#574 [fix] some bugs with api pager and paged searcher
  packages/ng/libraries/core/src/lib/api/select/pager/api-pager.component.ts
  packages/ng/libraries/core/src/lib/api/select/pager/api-pager.model.ts
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.model.ts
  packages/ng/libraries/core/src/lib/option/operator/for-options/for-options.directive.ts
Labels: bug, ng

#578 picker rescroll shenanigans
  packages/ng/libraries/core/src/lib/api/select/pager/api-pager.model.ts
  packages/ng/libraries/core/src/lib/api/select/searcher/api-searcher.model.ts
Labels: bug, ng
