Repository LuccaSA/lucca-front, pull requests merged in 2021-05, with the labels that each got.

#1300 feat(scss) Clearfix utils
  packages/scss/src/mixins/_utilities.scss
  packages/scss/src/utilities/_misc.scss
  stories/scss/utilities/clearfix.stories.html
  stories/scss/utilities/clearfix.stories.ts
Labels: :bookmark::sparkles: Feature, package scss

#1301 feat(scss-a11y) better a11y for checkbox mixed
  packages/scss/src/components/inputs/checkbox/_checkbox.scss
  stories/scss/form/checkbox/checkbox.stories.html
  stories/scss/form/checkbox/checkbox.stories.ts
Labels: :bookmark::sparkles: Feature, minor

#1296 fix(ng-tooltip) tooltip focus handling
  packages/ng/tooltip/src/lib/trigger/tooltip-trigger.directive.ts
  stories/ng/popover/popover.stories.ts
  stories/ng/tooltip/tooltip.stories.html
  stories/ng/tooltip/tooltip.stories.ts
Labels: :bookmark::bug: FIX

#1293 feat(scss) use theme variable for field label color
  packages/scss/src/components/inputs/field/_field.scss
  packages/scss/src/theming/components/_field.theme.scss
Labels: enhancement, package scss

#1289 feat(scss) add utilities for border radius
  packages/scss/src/utilities/_misc.scss
  stories/scss/utilities/border-radius.stories.html
  stories/scss/utilities/border-radius.stories.ts
  to-migrate/scss/components/utilities.html
Labels: package scss

#1288 feat(scss) new utility for flexbox
  packages/scss/src/utilities/_flex.scss
  stories/scss/utilities/min-width.stories.html
  stories/scss/utilities/min-width.stories.ts
  to-migrate/scss/components/utilities.html
Labels: package scss

#1291 feat(scss-a11y) menu : placeholder + aria-current
  packages/scss/src/components/_menu.scss
  stories/scss/menu/menu.stories.html
  stories/scss/menu/menu.stories.ts
  to-migrate/scss/components/menus.html
Labels: Accessibility, package scss

#1303 tech(all) publish on tag
  Jenkinsfile
Labels: :hammer: Technical

#1304 tech(all) Volta and clean up peer deps
  package.json
  packages/icons/package.json
  packages/ng/root/package.json
  packages/scss/package.json
Labels: :hammer: Technical

#1306 fix(ng) Some API/User select related fixes
  packages/ng/api/src/lib/select/searcher/api-searcher.component.ts
  packages/ng/api/src/lib/select/searcher/api-searcher.model.ts
  packages/ng/date/src/lib/select/date-select-input.component.ts
  packages/ng/department/src/lib/select/input/department-select-input.component.ts
  packages/ng/user/src/lib/select/searcher/user-searcher.component.ts
  stories/ng/api/select/api-select.stories.html
  stories/ng/api/select/api-select.stories.ts
  stories/ng/date/select/date-select.stories.ts
  stories/ng/user/select/user-select.stories.ts
  stories/ng/user/user.mocks.ts
Labels: :bookmark::bug: FIX, package ng

#1309 nolog(sb) add qa/empty state stories
  stories/qa/empty-state/empty-state.stories.html
  stories/qa/empty-state/empty-state.stories.ts
Labels: :bookmark::sparkles: Feature

#1311 nolog(sb) add qa/divider stories
  stories/qa/divider/divider.stories.html
  stories/qa/divider/divider.stories.ts
  stories/qa/icon/icon.stories.ts
Labels: :bookmark::sparkles: Feature

#1312 nolog(sb) add qa/label stories
  stories/qa/label/label.stories.html
  stories/qa/label/label.stories.ts
Labels: :bookmark::sparkles: Feature

#1313 nolog(sb) add qa/list stories
  stories/qa/list/list.stories.html
  stories/qa/list/list.stories.ts
Labels: :bookmark::sparkles: Feature

#1315 nolog(sb) add qa/container stories
  stories/qa/container/container.stories.html
  stories/qa/container/container.stories.ts
Labels: :bookmark::sparkles: Feature

#1316 nolog(sb) add qa/gauge stories
  stories/qa/gauge/gauge.stories.html
  stories/qa/gauge/gauge.stories.ts
Labels: :bookmark::sparkles: Feature

#1317 nolog(sb) add qa/grid stories
  stories/qa/grid/grid.stories.html
  stories/qa/grid/grid.stories.ts
Labels: :bookmark::sparkles: Feature

#1321 nolog(ci) use volta
  Jenkinsfile
Labels: :hammer: Technical

#1322 nolog(sb) add qa/table stories
  stories/qa/table/table.stories.html
  stories/qa/table/table.stories.ts
Labels: :bookmark::sparkles: Feature

#1326 nolog(ci) sync rc-master
  Jenkinsfile
  stories/qa/container/container.stories.html
  stories/qa/container/container.stories.ts
  stories/qa/divider/divider.stories.html
  stories/qa/divider/divider.stories.ts
  stories/qa/empty-state/empty-state.stories.html
  stories/qa/empty-state/empty-state.stories.ts
  stories/qa/gauge/gauge.stories.html
  stories/qa/gauge/gauge.stories.ts
  stories/qa/grid/grid.stories.html
  stories/qa/grid/grid.stories.ts
  stories/qa/icon/icon.stories.ts
  stories/qa/label/label.stories.html
  stories/qa/label/label.stories.ts
  stories/qa/list/list.stories.html
  stories/qa/list/list.stories.ts
  stories/qa/table/table.stories.html
  stories/qa/table/table.stories.ts
Labels: :hammer: Technical

#1364 nolog(sb) add qa/links stories
  stories/qa/links/links.stories.html
  stories/qa/links/links.stories.ts
Labels: :bookmark::sparkles: Feature

#1374 nolog(sb) add qa/table-of-content stories
  stories/qa/table-of-content/table-of-content.stories.html
  stories/qa/table-of-content/table-of-content.stories.ts
Labels: :bookmark::sparkles: Feature

#1365 nolog(sb) add qa/loadings stories
  stories/qa/loadings/loadings.stories.html
  stories/qa/loadings/loadings.stories.ts
Labels: :bookmark::sparkles: Feature

#1366 nolog(sb) add qa/section stories
  stories/qa/section/section.stories.html
  stories/qa/section/section.stories.ts
Labels: :bookmark::sparkles: Feature

#1367 nolog(sb) add qa/main stories
  stories/qa/main/main.stories.html
  stories/qa/main/main.stories.ts
Labels: :bookmark::sparkles: Feature

#1368 nolog(sb) add qa/tags stories
  stories/qa/tags/tags.stories.html
  stories/qa/tags/tags.stories.ts
Labels: :bookmark::sparkles: Feature

#1370 nolog(sb) add qa/timelines stories
  stories/qa/timelines/timelines.stories.html
  stories/qa/timelines/timelines.stories.ts
Labels: :bookmark::sparkles: Feature

#1371 nolog(sb) add qa/typography stories
  stories/qa/typography/typography.stories.html
  stories/qa/typography/typography.stories.ts
Labels: :bookmark::sparkles: Feature

#1372 nolog(sb) add qa/pagination stories
  stories/qa/pagination/pagination.stories.html
  stories/qa/pagination/pagination.stories.ts
Labels: :bookmark::sparkles: Feature

#1373 nolog(sb) add qa/progress stories
  stories/qa/progress/progress.stories.html
  stories/qa/progress/progress.stories.ts
Labels: :bookmark::sparkles: Feature
