Repository LuccaSA/lucca-front, pull requests merged in 2021-07, with the labels that each got.

#1151 refactor(scss) responsive container and breakpoints
  README.md
  demo/index.html
  packages/ng/material/src/style/components/_dialog.scss
  packages/ng/root/src/style/components/_popup.scss
  packages/scss/src/components/_container.scss
  packages/scss/src/components/_error-page.scss
  packages/scss/src/components/_grid.scss
  packages/scss/src/components/_header.scss
  packages/scss/src/components/_layout.scss
  packages/scss/src/components/_nav-side.scss
  packages/scss/src/components/_section.scss
  packages/scss/src/theming/_breakpoints.scss
  packages/scss/src/theming/_commons.scss
  packages/scss/src/theming/components/_container.theme.scss
  stories/qa/container/container.stories.html
  stories/qa/grid/grid.stories.html
  to-migrate/ng/drag-drop/drag-drop.component.html
  to-migrate/scss/components/containers.html
  to-migrate/scss/components/forms/forms-checkboxes.html
  to-migrate/scss/components/forms/forms-files.html
  to-migrate/scss/components/forms/forms-framed.html
  to-migrate/scss/components/forms/forms-radios.html
  to-migrate/scss/components/forms/forms-switches.html
  to-migrate/scss/components/forms/forms-textfields.html
  to-migrate/scss/components/grids.html
  to-migrate/scss/components/templates.html
  to-migrate/scss/demo.css
  to-migrate/scss/lucca-front.css
  to-migrate/scss/templates/form.html
Labels: BREAKING CHANGE, enhancement, package scss

#1299 tech(all) first draft ui-diff
  .cd/qa.json
  Jenkinsfile
  stories/qa/box/box.stories.html
  stories/qa/breadcrumb/breadcrumb.stories.html
  stories/qa/button/button.stories.html
  stories/qa/callout/callout.stories.html
  stories/qa/card/card.stories.html
  stories/qa/chip/chip.stories.html
  stories/qa/collapse/collapse.stories.html
  stories/qa/empty-state/empty-state.stories.ts
  stories/qa/links/links.stories.ts
  stories/qa/pagination/pagination.stories.ts
  stories/qa/progress/progress.stories.ts
  stories/qa/table-of-content/table-of-content.stories.ts
  stories/qa/tags/tags.stories.ts
  stories/qa/timelines/timelines.stories.ts
Labels: :hammer: Technical

#1397 ref(ci) Jenkinsfile cleanup
  Jenkinsfile
Labels: :hammer: Technical

#1314 fix(scss) add missing important on text utilities
  packages/scss/src/_typo.scss
  packages/scss/src/components/_card.scss
  packages/scss/src/components/_title-section.scss
  packages/scss/src/utilities/_text.scss
Labels: :bookmark::bug: FIX, package scss

#1323 feat(scss) table add mod-stickyHeader
  packages/scss/src/components/_table.scss
  stories/qa/table/table.stories.html
Labels: :bookmark::sparkles: Feature, package scss

#1377 feat(scss) palettes overhaul
  packages/scss/src/theming/_palettes.scss
Labels: DS to LF

#1378 feat(scss) Change divider color to grey 200
  packages/scss/src/theming/_commons.scss
Labels: DS to LF

#1379 feat(scss) Breadcrumb color
  packages/scss/src/components/_breadcrumbs.scss
Labels: DS to LF

#1380 feat(ng) Tooltip background
  packages/ng/material/src/style/components/_tooltip.scss
  packages/ng/root/src/style/definitions/tooltip/_tooltip.scss
  packages/ng/root/src/style/theme/_tooltip.theme.scss
Labels: BREAKING CHANGE, DS to LF

#1381 feat(scss) Callout
  packages/scss/src/components/_callout.scss
  packages/scss/src/theming/components/_callout.theme.scss
  stories/qa/callout/callout.stories.html
  stories/qa/callout/callout.stories.ts
Labels: DS to LF

#1385 feat(scss) tags
  packages/scss/src/components/_tag.scss
  stories/qa/tags/tags.stories.html
Labels: DS to LF

#1387 feat(scss) Labels
  packages/scss/src/components/_label.scss
  stories/qa/label/label.stories.html
Labels: DS to LF

#1390 feat(ng) official ng 12 support
  .storybook/main.js
  .storybook/tsconfig.json
  Jenkinsfile
  package-lock.json
  package.json
  packages/ng/root/package.json
  packages/scss/package.json
Labels: :bookmark::sparkles: Feature, :hammer: Technical, package ng

#1382 feat (scss) : add mod-layoutFixed, sticky columns, sticky columns automatic drop shadow
  packages/scss/src/components/_table.scss
  packages/scss/src/theming/components/_table.theme.scss
  stories/qa/table/table.stories.html
Labels: :bookmark::sparkles: Feature, package scss

#1392 feat(scss) component page-header
  packages/scss/src/_components.overridable.scss
  packages/scss/src/_components.scss
  packages/scss/src/components/_page-header.scss
  packages/scss/src/theming/_commons.scss
  packages/scss/src/theming/_components.scss
  packages/scss/src/theming/components/_page-header.theme.scss
  stories/qa/page-header/page-header.stories.html
  stories/qa/page-header/page-header.stories.ts
Labels: DS to LF

#1391 feat(ng-dpt) scoped tree
  .gitignore
  package-lock.json
  package.json
  packages/ng/department/src/lib/select/feeder/department-feeder.component.ts
  packages/ng/department/src/lib/select/input/department-select-input.component.html
  packages/ng/department/src/lib/select/input/department-select-input.component.ts
  packages/ng/department/src/lib/service/department-v3.service.ts
  stories/ng/department/department-select.stories.html
  stories/ng/department/department-select.stories.ts
Labels: :bookmark::sparkles: Feature, minor, package ng

#1394 feat(ng-a11y) popover triggers
  packages/ng/popover/src/lib/trigger/popover-trigger.model.ts
  packages/ng/tooltip/src/lib/trigger/tooltip-trigger.directive.ts
  stories/ng/popover/popover.stories.ts
Labels: :bookmark::sparkles: Feature, Accessibility, package ng

#1401 feat(ng-ets) Do not group by legal unit if not usefull
  packages/ng/api/src/lib/service/api-v4.service.ts
  packages/ng/establishment/src/lib/select/input/establishment-select-input.component.html
  packages/ng/establishment/src/lib/select/input/establishment-select-input.component.ts
  packages/ng/establishment/src/lib/service/index.ts
  packages/ng/establishment/src/lib/service/legal-unit-service.model.ts
  packages/ng/establishment/src/lib/service/legal-unit.service.ts
  packages/ng/select/src/lib/input/select-input.model.ts
  stories/ng/establishment-select/establishment-select.stories.ts
Labels: :bookmark::sparkles: Feature

#1399 fix(ng-user) me-first directive wasnt applying the filters of the user-select
  packages/ng/user/src/lib/select/input/user-select-input.component.html
  packages/ng/user/src/lib/select/me/me-option.directive.ts
  stories/ng/user/select/user-select.stories.ts
Labels: :bookmark::bug: FIX

#1421 REF optimize gulp build time
  gulpfile.js
Labels: :hammer: Technical, enhancement

#1406 nolog(sb) add qa/forms stories
  stories/qa/forms/checkboxes.stories.html
  stories/qa/forms/checkboxes.stories.ts
  stories/qa/forms/files.stories.html
  stories/qa/forms/files.stories.ts
  stories/qa/forms/framed.stories.html
  stories/qa/forms/framed.stories.ts
  stories/qa/forms/radio-buttons.stories.html
  stories/qa/forms/radio-buttons.stories.ts
  stories/qa/forms/radios.stories.html
  stories/qa/forms/radios.stories.ts
  stories/qa/forms/switches.stories.html
  stories/qa/forms/switches.stories.ts
  stories/qa/forms/textfields.stories.html
  stories/qa/forms/textfields.stories.ts
  to-migrate/scss/components/forms/forms-files.html
Labels: :bookmark::sparkles: Feature

#1412 nolog(sb) add callout in scss
  stories/scss/callout/callout.stories.html
  stories/scss/callout/callout.stories.ts
Labels: :bookmark::sparkles: Feature

#1414 nolog(sb) add tag on scss
  stories/scss/tags/tags.stories.html
  stories/scss/tags/tags.stories.ts
Labels: :bookmark::sparkles: Feature

#1415 nolog(sb) add progress in scss
  stories/scss/progress/progress.stories.html
  stories/scss/progress/progress.stories.ts
Labels: :bookmark::sparkles: Feature

#1413 nolog(sb) add chip on scss
  stories/scss/chip/chip.stories.html
  stories/scss/chip/chip.stories.ts
Labels: :bookmark::sparkles: Feature

#1405 nolog(sb) add qa/menu and scss/menu stories
  stories/qa/menu/menu.stories.html
  stories/qa/menu/menu.stories.ts
  stories/scss/menu/menu.stories.html
  stories/scss/menu/menu.stories.ts
  to-migrate/scss/components/menus.html
  to-migrate/scss/includes/demo-main-content.html
  to-migrate/scss/includes/demo-menu.html
Labels: :bookmark::sparkles: Feature

#1416 nolog(sb) add scss/box story
  stories/scss/box/box-basic.stories.html
  stories/scss/box/box-basic.stories.ts
Labels: :bookmark::sparkles: Feature

#1407 nolog(sb) add qa/comm-in-app story
  stories/qa/comm-in-app/comm-in-app.stories.html
  stories/qa/comm-in-app/comm-in-app.stories.ts
  to-migrate/scss/components/comm-in-app.html
Labels: :bookmark::sparkles: Feature

#1417 nolog(sb) add scss/card story
  stories/qa/card/card.stories.html
  stories/scss/card/card-basic.stories.html
  stories/scss/card/card-basic.stories.ts
Labels: :bookmark::sparkles: Feature

#1418 nolog(sb) add scss/labels story
  stories/scss/labels/label-basic.stories.html
  stories/scss/labels/label-basic.stories.ts
  to-migrate/scss/components/labels.html
Labels: :bookmark::sparkles: Feature

#1411 nolog(sb) add scss/breadcrumbs story
  stories/qa/breadcrumb/breadcrumb.stories.html
  stories/scss/breadcrumb/breadcrumb-basic.stories.html
  stories/scss/breadcrumb/breadcrumb-basic.stories.ts
Labels: :bookmark::sparkles: Feature

#1420 nolog(sb) add scss/pageHeader story
  packages/scss/src/components/_page-header.scss
  stories/qa/page-header/page-header.stories.html
  stories/scss/page-header/page-header-basic.stories.html
  stories/scss/page-header/page-header-basic.stories.ts
Labels: :bookmark::sparkles: Feature

#1408 nolog(sb) add main-menu story
  stories/qa/main-menu/main-menu.stories.html
  stories/qa/main-menu/main-menu.stories.ts
  to-migrate/scss/includes/demo-main-content.html
  to-migrate/scss/includes/demo-menu.html
Labels: :bookmark::sparkles: Feature

#1419 nolog(sb) add scss/lists story
  stories/qa/list/list.stories.html
  stories/scss/lists/lists-basic.stories.html
  stories/scss/lists/lists-basic.stories.ts
  to-migrate/scss/components/lists.html
Labels: :bookmark::sparkles: Feature
