Repository LuccaSA/lucca-front, pull requests merged in 2022-09, with the labels that each got.

#1837 Update dependencies
  .storybook/main.js
  angular.json
  package-lock.json
  package.json
  tsconfig.json
Labels: :hammer: Technical

#1842 [Box] Toggle story
  stories/documentation/feedback/box/box-toggle.stories.ts
Labels: 👥 Guilde Design, 📖 Documentation changes

#1840 [Table] Layout missing property
  packages/scss/src/components/table/index.scss
  packages/scss/src/components/table/mods.scss
  packages/scss/src/components/tableSticked/index.scss
  packages/scss/src/components/tableSticked/mods.scss
Labels: 🐞 Bug, 👥 Guilde Design

#1847 [popup] Fix broken animation
  packages/ng/styles/components/cdk/_overlay.scss
Labels: 🐞 Bug, 👥 Guilde Design

#1790 [QA] Init e2e project (ui-diff)
  .cd/production.json
  .cd/qa.json
  .vscode/settings.json
  Jenkinsfile
  e2e/.editorconfig
  e2e/.gitignore
  e2e/.vscode/extensions.json
  e2e/.vscode/settings.json
  e2e/LuccaFront.Tests.e2e/Contexts/ScreenshotContext.cs
  e2e/LuccaFront.Tests.e2e/Features/Button.feature
  e2e/LuccaFront.Tests.e2e/Features/Checkboxes.feature
  e2e/LuccaFront.Tests.e2e/Features/DateSelect.feature
  e2e/LuccaFront.Tests.e2e/Features/DepartmentSelect.feature
  e2e/LuccaFront.Tests.e2e/Features/EstablishmentSelect.feature
  e2e/LuccaFront.Tests.e2e/Features/FeedbackBox.feature
  e2e/LuccaFront.Tests.e2e/Features/FeedbackBoxCallout.feature
  e2e/LuccaFront.Tests.e2e/Features/Link.feature
  e2e/LuccaFront.Tests.e2e/Features/Overlays.feature
  e2e/LuccaFront.Tests.e2e/Features/QualificationSelect.feature
  e2e/LuccaFront.Tests.e2e/Features/Structure/Cards.feature
  e2e/LuccaFront.Tests.e2e/Features/Structure/Containers.feature
  e2e/LuccaFront.Tests.e2e/Features/Structure/Divider.feature
  e2e/LuccaFront.Tests.e2e/Features/Structure/EmptyState.feature
  e2e/LuccaFront.Tests.e2e/Features/Structure/Filters.feature
  e2e/LuccaFront.Tests.e2e/Features/Structure/Grids.feature
  e2e/LuccaFront.Tests.e2e/Features/Structure/Headers.feature
  e2e/LuccaFront.Tests.e2e/Features/Structure/Sections.feature
  e2e/LuccaFront.Tests.e2e/Features/Switches.feature
  e2e/LuccaFront.Tests.e2e/Features/Textfield.feature
  e2e/LuccaFront.Tests.e2e/INavigation.cs
  e2e/LuccaFront.Tests.e2e/LuccaFront.Tests.e2e.csproj
  e2e/LuccaFront.Tests.e2e/LuccaFrontPlaywright.cs
  e2e/LuccaFront.Tests.e2e/Steps/CheckboxesSteps.cs
  e2e/LuccaFront.Tests.e2e/Steps/ModSteps.cs
  e2e/LuccaFront.Tests.e2e/Steps/Overlays.cs
  e2e/LuccaFront.Tests.e2e/Steps/ScreenshotSteps.cs
  e2e/LuccaFront.Tests.e2e/Steps/SelectSteps.cs
  e2e/LuccaFront.Tests.e2e/Steps/StartupSteps.cs
  e2e/LuccaFront.Tests.e2e/Steps/StorybookSteps.cs
  e2e/LuccaFront.Tests.e2e/testSettings.json
  e2e/LuccaFront.e2e.sln
  e2e/NuGet.Config
  lucca-front.code-workspace
  stories/documentation/feedback/callout/callout-basic.stories.ts
  stories/documentation/feedback/callout/callout-icons.stories.ts
  stories/documentation/overlays/tooltip/tooltip.stories.ts
Labels: 👥 Guilde Front, :hammer: Technical

#1857 fix: eslint on VSCode was broken
  .eslintrc
  packages/ng/tsconfig.json
  packages/ng/tsconfig.lib.json
Labels: 👥 Guilde Front, :hammer: Technical

#1853 [File upload] Cursor pointer
  packages/scss/src/components/file/component.scss
Labels: 👥 Guilde Design, 🎨 UI Adjustments

#1859 Table foot
  packages/scss/src/components/table/component.scss
  packages/scss/src/components/table/index.scss
  packages/scss/src/components/table/mods.scss
  packages/scss/src/components/tableFixed/index.scss
  packages/scss/src/components/tableSticked/index.scss
  packages/scss/src/components/tableSticked/mods.scss
Labels: 🐞 Bug

#1851 [Tag] Allow outlined + palette
  packages/scss/src/components/tag/mods.scss
Labels: 👥 Guilde Design, 🎉 Feature

#1864 [Table] Add mod align center
  packages/scss/src/components/table/index.scss
  packages/scss/src/components/table/mods.scss
  packages/scss/src/components/tableSorted/index.scss
  packages/scss/src/components/tableSorted/mods.scss
  stories/documentation/listings/table/table-basic.stories.ts
Labels: 👥 Guilde Design, 🎉 Feature

#1852 [Label] Documentation for mod-icon
  stories/documentation/texts/labels/label-icon.stories.ts
Labels: 👥 Guilde Design, 📖 Documentation changes

#1876 Ajouts d'un comportement lorsque l'observable d'une submitAction d'une modal est "completed"
  packages/ng/modal/src/lib/modal-panel.component.ts
Labels: 🎉 Feature

#1877 Add type button on basicButton stories
  stories/documentation/actions/button/button-basic.stories.ts
Labels: 👥 Guilde Front, 🎉 Feature, 📖 Documentation changes

#1866 [Textfield] add mod-small
  packages/scss/src/components/textfield/component.scss
  packages/scss/src/components/textfield/index.scss
  packages/scss/src/components/textfield/mods.scss
  packages/scss/src/components/textfield/vars.scss
  stories/documentation/forms/textfields/textfield-basic.stories.ts
  stories/qa/forms/textfields.stories.html
Labels: 👥 Guilde Design, 🎉 Feature, 🎨 DS to LF

#1849 delete cross on type search hover and focus
  packages/scss/src/components/textfield/mods.scss
  stories/qa/forms/textfields.stories.html
Labels: 🐞 Bug, 👥 Guilde Design

#1860 fontWeight
  packages/scss/src/components/util/index.scss
Labels: 🐞 Bug, 💥 Breaking change, 📖 Documentation changes

#1858 Fix type search
  packages/scss/src/components/textfield/component.scss
Labels: 🐞 Bug

#1863 Status component
  packages/scss/src/components/index.scss
  packages/scss/src/components/status/component.scss
  packages/scss/src/components/status/exports.scss
  packages/scss/src/components/status/index.scss
  packages/scss/src/components/status/mods.scss
  packages/scss/src/components/status/states.scss
  packages/scss/src/components/status/vars.scss
  stories/documentation/texts/status/status-basic.stories.ts
Labels: 🎉 Feature
