Repository LuccaSA/lucca-front, pull requests merged in 2022-06, with the labels that each got.

#1701 Next fixes
  packages/ng/api/src/lib/select/searcher/api-searcher.component.scss
  packages/ng/establishment/src/lib/select/searcher/establishment-searcher.component.scss
  packages/ng/establishment/src/lib/select/select-all/establishment-select-all.component.scss
  packages/ng/option/src/lib/item/tree-option-item.component.scss
  packages/ng/option/src/lib/operator/searcher/option-searcher.component.scss
  packages/ng/option/src/lib/placeholder/option-placeholder.component.scss
  packages/ng/option/src/lib/selector/all/select-all.component.scss
  packages/ng/style/_components.scss
  packages/ng/style/components/_dropdown.scss
  packages/ng/style/definitions/option/_option-item.scss
  packages/ng/user/src/lib/select/searcher/user-searcher.component.scss
  packages/scss/src/components/chip/component.scss
  packages/scss/src/main.dist.scss
Labels: Next

#1702 Next forms
  packages/scss/src/components/checkbox/component.scss
  packages/scss/src/components/field/index.scss
  packages/scss/src/components/field/mods.scss
  packages/scss/src/components/field/vars.scss
  packages/scss/src/components/form/component.scss
  packages/scss/src/components/form/index.scss
  packages/scss/src/components/form/mods.scss
  packages/scss/src/components/form/vars.scss
  packages/scss/src/components/textfield/index.scss
  packages/scss/src/components/textfield/states.scss
  packages/scss/src/components/textfield/vars.scss
Labels: Next

#1706 Fix use
  packages/ng/style/components/_popup.scss
Labels: Next

#1710 Next.material
  packages/ng/formly/src/lib/types/formly-field.common.scss
  packages/ng/formly/src/lib/wrappers/flex-layout.scss
  packages/ng/formly/src/lib/wrappers/suffixes.common.scss
  packages/ng/formly/src/lib/wrappers/wrappers.common.scss
  packages/ng/formly/style/_components.scss
  packages/ng/formly/style/_theming.scss
  packages/ng/formly/style/main.scss
  packages/ng/material/style/_components.scss
  packages/ng/material/style/_theming.scss
  packages/ng/material/style/components/_autocomplete.scss
  packages/ng/material/style/components/_buttons.scss
  packages/ng/material/style/components/_datepicker.scss
  packages/ng/material/style/components/_dialog.scss
  packages/ng/material/style/components/_input.scss
  packages/ng/material/style/components/_menu.scss
  packages/ng/material/style/components/_mixins.scss
  packages/ng/material/style/components/_options.scss
  packages/ng/material/style/components/_select.scss
  packages/ng/material/style/components/_tooltip.scss
  packages/ng/material/style/main-v11.scss
  packages/ng/material/style/main.scss
  packages/scss/src/components/textfield/mods.scss
Labels: Next

#1711 Remove legacy theming / override system
  demo/assets/github.png
  demo/assets/ng.png
  demo/assets/sass.png
  demo/index.html
  packages/ng/formly/style/_theming.overridable.scss
  packages/ng/formly/style/_theming.scss
  packages/ng/formly/style/main.overridable.scss
  packages/ng/material/style/_theming.overridable.scss
  packages/ng/material/style/_theming.scss
  packages/ng/material/style/main-v11.overridable.scss
  packages/ng/material/style/main-v11.scss
  packages/ng/material/style/main.overridable.scss
  packages/ng/material/style/main.scss
  packages/ng/style/_definitions.scss
  packages/ng/style/_theming.overridable.scss
  packages/ng/style/_theming.scss
  packages/ng/style/main.overridable.scss
  packages/ng/style/main.scss
  packages/ng/style/overrides/_calendar.override.scss
  packages/ng/style/overrides/_dropdown.override.scss
  packages/ng/style/overrides/_options.override.scss
  packages/ng/style/overrides/_popup.override.scss
  packages/ng/style/overrides/_select.override.scss
  packages/ng/style/overrides/_tooltip.override.scss
  packages/ng/style/overrides/_user-picture.override.scss
  packages/ng/style/theme/_calendar.theme.scss
  packages/ng/style/theme/_dropdown.theme.scss
  packages/ng/style/theme/_options.theme.scss
  packages/ng/style/theme/_popup.theme.scss
  packages/ng/style/theme/_select.theme.scss
  packages/ng/style/theme/_tooltip.theme.scss
  packages/ng/style/theme/_user-picture.theme.scss
  packages/scss/src/components/textfield/mods.scss
Labels: Next

#1712 Fixes before first test
  packages/scss/src/commons/config.scss
  packages/scss/src/components/divider/vars.scss
  packages/scss/src/components/field/mods.scss
  packages/scss/src/components/label/component.scss
  packages/scss/src/components/label/mods.scss
Labels: Next

#1716 Naming + colors
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/components/form/index.scss
  packages/scss/src/components/index.scss
  packages/scss/src/components/main/component.scss
  packages/scss/src/components/main/exports.scss
  packages/scss/src/components/main/index.scss
  packages/scss/src/components/main/mods.scss
  packages/scss/src/components/main/states.scss
  packages/scss/src/components/main/vars.scss
  packages/scss/src/components/navside/index.scss
  packages/scss/src/components/tableOfContent/component.scss
  packages/scss/src/components/tableOfContent/exports.scss
  packages/scss/src/components/tableOfContent/index.scss
  packages/scss/src/components/tableOfContent/mods.scss
  packages/scss/src/components/tableOfContent/states.scss
  packages/scss/src/components/tableOfContent/vars.scss
Labels: :bookmark::bug: FIX, Next

#1718 Fixes
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/core.scss
  packages/scss/src/commons/utils/reset.scss
Labels: :bookmark::bug: FIX, Next

#1717 Package icons
  .storybook/src/styles.scss
  packages/icons/icons-list.js
  packages/icons/src/_classes.scss
  packages/icons/src/_font.scss
  packages/icons/src/_icons.scss
  packages/icons/src/_mappings.scss
  packages/icons/src/_mixins.scss
  packages/icons/src/_partials.scss
  packages/icons/src/main.scss
  packages/scss/src/components/icon/exports.scss
  packages/scss/src/components/icon/index.scss
  packages/scss/src/components/icon/mods.scss
  packages/scss/src/components/index.scss
Labels: Next

#1721 Fix forward
  packages/scss/src/commons/utils/index.scss
Labels: :bookmark::bug: FIX, Next

#1720 Scss.stories
  stories/documentation/listings/table/table-actions.stories.ts
  stories/documentation/listings/table/table-basic.stories.ts
  stories/documentation/listings/table/table-selectable.stories.ts
  stories/documentation/navigation/menu/menu-basic.stories.ts
  stories/documentation/navigation/menu/menu-count.stories.ts
  stories/documentation/navigation/table-of-content/table-of-content-basic.stories.ts
  stories/documentation/structure/containers/containers-basic.stories.ts
  stories/documentation/structure/grids/grids-basic.stories.ts
  stories/documentation/structure/grids/grids-justify.stories.ts
  stories/documentation/texts/text/text.stories.ts
Labels: package scss

#1722 Labels color
  packages/scss/src/components/emptyState/component.scss
  packages/scss/src/components/field/component.scss
  packages/scss/src/components/field/mods.scss
  packages/scss/src/components/field/vars.scss
  packages/scss/src/components/textfield/mods.scss
  packages/scss/src/components/textfield/vars.scss
  packages/scss/src/components/titleSection/component.scss
Labels: Next

#1713 feat(ng) Allow Title service to replace first prefix
  packages/ng/title/src/lib/title.service.spec.ts
  packages/ng/title/src/lib/title.service.ts
Labels: :bookmark::sparkles: Feature

#1727 Fixes
  packages/scss/src/components/container/component.scss
  packages/scss/src/components/navside/vars.scss
  packages/scss/src/components/pageHeader/component.scss
Labels: :bookmark::bug: FIX, Next

#1728 Fixes
  packages/scss/src/commons/core.scss
  packages/scss/src/components/button/index.scss
  packages/scss/src/components/card/states.scss
  packages/scss/src/components/titleSection/component.scss
  packages/scss/src/components/titleSection/index.scss
  packages/scss/src/components/util/index.scss
Labels: :bookmark::bug: FIX, Next

#1729 Fix button and clearer
  packages/ng/input/src/lib/clearer/clearer.component.ts
  packages/scss/src/components/button/mods.scss
Labels: :bookmark::bug: FIX, Next

#1732 Black to G900
  packages/ng/style/components/cdk/_overlay.scss
  packages/ng/style/definitions/select/_select-clearer.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/utils/loading.scss
  packages/scss/src/components/button/mods.scss
  packages/scss/src/components/chip/component.scss
  packages/scss/src/components/file/component.scss
  packages/scss/src/components/gauge/component.scss
  packages/scss/src/components/navside/component.scss
Labels: :bookmark::sparkles: Feature, Next

#1734 Fix timeline title
  packages/scss/src/components/timeline/component.scss
Labels: :bookmark::bug: FIX, Next

#1735 Revert "Fix timeline title (#1734)"
  packages/scss/src/components/timeline/component.scss
Labels: :bookmark::bug: FIX, Next

#1736 fontVariable option
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
Labels: :bookmark::sparkles: Feature, Next

#1737 Remove prefix
  packages/icons/src/icon/component.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/core.scss
  packages/scss/src/components/card/states.scss
  packages/scss/src/components/grid/index.scss
  packages/scss/src/components/titleSection/component.scss
  packages/scss/src/components/titleSection/index.scss
  packages/scss/src/components/toast/component.scss
  packages/scss/src/components/util/index.scss
Labels: :bookmark::sparkles: Feature, Next

#1738 replace components variables
  packages/scss/src/components/filters/mods.scss
  packages/scss/src/components/header/mods.scss
  packages/scss/src/components/navside/component.scss
  packages/scss/src/components/navside/vars.scss
Labels: Next

#1739 fix(storybook): use type code to avoid using "angular" language in prettier
  stories/documentation/forms/api/select/api-select.stories.ts
  stories/documentation/forms/date/calendar/calendar.stories.ts
  stories/documentation/forms/date/select/date-select.stories.ts
  stories/documentation/forms/department/department-select.stories.ts
  stories/documentation/forms/establishment-select/establishment-select.stories.ts
  stories/documentation/forms/qualification/qualification-select.stories.ts
  stories/documentation/forms/select/select.stories.ts
  stories/documentation/overlays/dropdown/dropdown-basic.stories.ts
  stories/documentation/overlays/dropdown/dropdown-component.stories.ts
  stories/documentation/overlays/dropdown/dropdown-directive.stories.ts
  stories/documentation/overlays/modal/modal.stories.ts
  stories/documentation/overlays/popover/popover.stories.ts
  stories/documentation/overlays/toasts/toasts.stories.ts
  stories/documentation/users/select/user-homonyms.stories.ts
  stories/documentation/users/select/user-select.stories.ts
  stories/documentation/users/tile/user-tile-format.stories.ts
  stories/documentation/users/tile/user-tile.stories.ts
Labels: :bookmark::bug: FIX, :hammer: Technical
