Repository LuccaSA/lucca-front, pull requests merged in 2022-01, with the labels that each got.

#1484 Mask the help text
  packages/scss/src/components/_nav-side.scss
Labels: package scss, minor, :bookmark::bug: FIX

#1453 feat(ng/user) MeOption improvements
  packages/ng/user/src/lib/select/input/user-select-input.component.html
  packages/ng/user/src/lib/select/input/user-select-input.component.ts
  packages/ng/user/src/lib/select/me/me-option.directive.ts
  packages/ng/user/src/lib/select/searcher/user-searcher.component.ts
Labels: :bookmark::sparkles: Feature

#1424 feat(scss) utilities color grey
  packages/scss/src/utilities/_text.scss
Labels: DS to LF

#1404 [sb] add ng/date/alendar story
  stories/ng/date/calendar/calendar.stories.html
  stories/ng/date/calendar/calendar.stories.ts
Labels: :see_no_evil: No log

#1454 Ability to put buttons in the nav side
  packages/scss/src/components/_nav-side.scss
Labels: package scss, minor, Accessibility, :bookmark::bug: FIX

#1468 Fix menu legacy regression
  packages/scss/src/components/_menu.scss
Labels: package scss, :bookmark::bug: FIX

#1504 fix(scss) breadcrumbs sizing and spacing
  packages/scss/src/components/_breadcrumbs.scss
Labels: :bookmark::bug: FIX, Graphic adjustment

#1462 Add utilities for gap
  packages/scss/src/utilities/_flex.scss
Labels: package scss, minor, :bookmark::sparkles: Feature

#1497 fix(scss) display for fieldset in framed forms
  packages/scss/src/components/inputs/checkbox/_checkboxesfield.scss
  packages/scss/src/components/inputs/radio/_radiosfield.scss
  stories/scss/form/framed/framed.stories.html
Labels: :bookmark::bug: FIX
