Repository LuccaSA/lucca-front, pull requests merged in 2022-10, with the labels that each got.

#1704 WIP Select
  packages/ng/select/src/lib/input/select-input.module.ts
  packages/ng/simple-select/README.md
  packages/ng/simple-select/ng-package.json
  packages/ng/simple-select/src/lib/index.ts
  packages/ng/simple-select/src/lib/input/index.ts
  packages/ng/simple-select/src/lib/input/select-input.component.html
  packages/ng/simple-select/src/lib/input/select-input.component.scss
  packages/ng/simple-select/src/lib/input/select-input.component.ts
  packages/ng/simple-select/src/lib/option/displayer.directive.ts
  packages/ng/simple-select/src/lib/option/index.ts
  packages/ng/simple-select/src/lib/option/option.component.html
  packages/ng/simple-select/src/lib/option/option.component.scss
  packages/ng/simple-select/src/lib/option/option.component.ts
  packages/ng/simple-select/src/lib/option/option.directive.ts
  packages/ng/simple-select/src/lib/panel/index.ts
  packages/ng/simple-select/src/lib/panel/panel.component.html
  packages/ng/simple-select/src/lib/panel/panel.component.scss
  packages/ng/simple-select/src/lib/panel/panel.component.ts
  packages/ng/simple-select/src/lib/select.model.ts
  packages/ng/simple-select/src/public-api.ts
  packages/scss/src/components/index.scss
  stories/documentation/forms/select/simple-select.stories.ts
Labels: 👥 Guilde Front, 👥 Guilde Design, 🎉 Feature

#1883 [icons] add icons rocket, floor, chair
  packages/icons/font/lucca-icons.eot
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.js
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: 👥 Guilde Design, :bookmark::sparkles: Feature

#1882 [Avatar] Remove unused code + add img on cdn
  packages/ng/styles/definitions/user/user-picture.scss
  stories/documentation/users/user.mocks.ts
Labels: 👥 Guilde Design, :hammer: Technical, :book: Documentation changes

#1884 [Sidepanel/Modal] More observable properties
  packages/ng/modal/src/lib/modal-panel.component.html
  packages/ng/modal/src/lib/modal-panel.component.ts
  packages/ng/modal/src/lib/modal.model.ts
  packages/ng/sidepanel/src/lib/sidepanel-panel.component.html
  stories/documentation/overlays/modal/modal.stories.ts
  stories/documentation/overlays/sidepanel/sidepanel.stories.ts
Labels: 👥 Guilde Front, :bookmark::sparkles: Feature, :hammer: Technical, :book: Documentation changes

#1891 [Dropdown] Cover icons on options
  packages/ng/styles/components/_dropdown.scss
  stories/documentation/overlays/dropdown/dropdown-basic.stories.html
  stories/documentation/overlays/dropdown/dropdown-basic.stories.ts
Labels: 👥 Guilde Design, :bookmark::sparkles: Feature, 🎨 UI Adjustments, :book: Documentation changes

#1899 chore: ref storybook config - no more empty application
  .storybook/src/app/app.component.ts
  .storybook/src/app/app.module.ts
  .storybook/src/environments/environment.ts
  .storybook/src/index.html
  .storybook/src/main.ts
  .storybook/src/polyfills.ts
  .storybook/src/styles.scss
  .storybook/styles.scss
  angular.json
  package.json
Labels: :hammer: Technical

#1892 [Tabbar] Fix vertical gap when collapsing
  packages/scss/src/components/menu/component.scss
Labels: 👥 Guilde Design, 🎨 UI Adjustments, :bookmark::bug: FIX
