Repository LuccaSA/lucca-front, pull requests merged in 2022-07, with the labels that each got.

#1745 Fix imports
  .storybook/src/styles.scss
  README.md
  angular.json
  gulpfile.js
  packages/ng/style/components/_input.scss
  packages/ng/style/definitions/select/_select-input.scss
  packages/scss/src/_icons.scss
  to-migrate/scss/components/mixins.html
Labels: dependencies, :bookmark::bug: FIX

#1708 [Spec] Initialisation de tests sur les stories de Storybook
  .storybook/tsconfig.json
  jest.config.json
  package-lock.json
  package.json
  packages/ng/api/src/lib/api.spec.ts
  setup-jest.ts
  stories/documentation/actions/button/button-basic.stories.ts
  stories/documentation/actions/button/button.spec.ts
  stories/documentation/forms/api/select/api-select.stories.ts
  tsconfig.json
  tsconfig.spec.json
Labels: :hammer: Technical

#1747 Skip links component
  packages/scss/src/components/index.scss
  packages/scss/src/components/skipLinks/component.scss
  packages/scss/src/components/skipLinks/exports.scss
  packages/scss/src/components/skipLinks/index.scss
  packages/scss/src/components/skipLinks/mods.scss
  packages/scss/src/components/skipLinks/states.scss
  packages/scss/src/components/skipLinks/vars.scss
  stories/documentation/navigation/skipLinks/skipLinks-basic.stories.ts
Labels: :bookmark::sparkles: Feature, Next

#1744 Package desc
  packages/scss/package.json
Labels: :bookmark::bug: FIX, Next

#1748 Readme documentation for LF10
  README.md
  packages/icons/README.md
Labels: Next

#1740 Container vars
  packages/scss/src/components/container/component.scss
  packages/scss/src/components/container/vars.scss
Labels: Next

#1758 Fix order declaration
  packages/scss/src/components/util/index.scss
Labels: package scss, :bookmark::bug: FIX

#1757 Fix timeline
  packages/scss/src/components/timeline/mods.scss
Labels: package scss, :bookmark::bug: FIX

#1761 Add removed utilities
  packages/scss/src/commons/core.scss
  packages/scss/src/components/util/index.scss
Labels: package scss, :bookmark::bug: FIX

#1775 Divider variables as global
  packages/scss/src/commons/base.scss
  packages/scss/src/components/divider/vars.scss
Labels: :bookmark::bug: FIX

#1770 [FIX] Fix LF9 -> LF10 migration script
  packages/ng/schematics/lib/scss-ast.ts
  packages/ng/schematics/migrations/css-vars/css-class-registry.ts
  packages/ng/schematics/migrations/css-vars/migration.spec.ts
  packages/ng/schematics/migrations/css-vars/migration.ts
  stories/documentation/integration/utilities/float.stories.ts
Labels: :bookmark::bug: FIX

#1768 feat(tooltip): display tooltip when text has an ellipsis
  packages/ng/popover/src/lib/trigger/popover-trigger.model.ts
  packages/ng/tooltip/src/lib/trigger/tooltip-trigger.directive.ts
  stories/documentation/overlays/tooltip/tooltip.stories.html
  stories/documentation/overlays/tooltip/tooltip.stories.ts
Labels: package ng, :bookmark::sparkles: Feature

#1777 feat(schematics): handle _color(text)
  packages/ng/schematics/migrations/css-vars/tests/colors-white.input.scss
  packages/ng/schematics/migrations/css-vars/tests/colors-white.output.scss
  packages/ng/schematics/migrations/css-vars/updaters/color.ts
Labels: :hammer: Technical
