Repository LuccaSA/lucca-front, pull requests merged in 2023-06, with the labels that each got.

#2132 Fix cursor on disabled button
  packages/scss/src/components/button/states.scss
Labels: :bookmark::bug: FIX

#2135 [Modal] Remove XXS from story
  stories/documentation/overlays/modal/modal.stories.ts
Labels: :hammer: Technical, 📖 Documentation changes, :book: Documentation changes

#2138 UI update (batch of simple components)
  packages/ng/styles/components/_popover.scss
  packages/ng/styles/definitions/tooltip/_tooltip.scss
  packages/scss/src/commons/utils/a11y.scss
  packages/scss/src/components/chip/component.scss
  packages/scss/src/components/chip/index.scss
  packages/scss/src/components/chip/mods.scss
  packages/scss/src/components/chip/states.scss
  packages/scss/src/components/chip/vars.scss
  packages/scss/src/components/filters/component.scss
  packages/scss/src/components/filters/vars.scss
  packages/scss/src/components/menu/component.scss
  packages/scss/src/components/menu/states.scss
  packages/scss/src/components/pageHeader/component.scss
  packages/scss/src/components/pageHeader/index.scss
  packages/scss/src/components/pageHeader/mods.scss
  packages/scss/src/components/pagination/component.scss
  packages/scss/src/components/pagination/index.scss
  packages/scss/src/components/pagination/mods.scss
  packages/scss/src/components/tag/component.scss
  packages/scss/src/components/tag/index.scss
  packages/scss/src/components/tag/mods.scss
  packages/scss/src/components/textfield/mods.scss
  packages/scss/src/components/textfield/states.scss
  packages/scss/src/components/timepicker/component.scss
  packages/scss/src/components/timepicker/index.scss
  packages/scss/src/components/timepicker/mods.scss
  packages/scss/src/components/timepicker/states.scss
  packages/scss/src/components/timepicker/vars.scss
  stories/documentation/forms/timepicker/timepicker-basic.stories.ts
  stories/documentation/listings/chip/chip.stories.ts
  stories/documentation/navigation/menu/menu-basic.stories.ts
  stories/documentation/navigation/pagination/pagination-basic.stories.ts
  stories/documentation/navigation/pagination/pagination-compact.stories.ts
  stories/documentation/structure/headers/headers-breadcrumb.stories.ts
  stories/documentation/structure/page-header/page-header-basic.stories.html
  stories/documentation/structure/page-header/page-header-basic.stories.ts
  stories/documentation/structure/page-header/page-header-breadcrumb.stories.ts
  stories/documentation/structure/page-header/page-header-menu.stories.ts
  stories/documentation/texts/tags/tags.stories.ts
  stories/qa/chip/chip.stories.html
  stories/qa/menu/menu.stories.html
  stories/qa/page-header/page-header.stories.html
  stories/qa/tags/tags.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2149 Fix radios without labels
  packages/scss/src/components/radio/component.scss
  packages/scss/src/components/radio/mods.scss
Labels: :bookmark::bug: FIX

#2141 [Componentsv3] Loading
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/utils/loading.scss
  packages/scss/src/components/loading/component.scss
  packages/scss/src/components/loading/mods.scss
  packages/scss/src/components/loading/vars.scss
Labels: :bookmark::sparkles: Feature

#2145 [Components v3] Table
  packages/scss/src/components/checkbox/mods.scss
  packages/scss/src/components/table/component.scss
  packages/scss/src/components/table/mods.scss
  packages/scss/src/components/table/vars.scss
  packages/scss/src/components/tableSorted/mods.scss
  packages/scss/src/components/tableSorted/states.scss
  stories/documentation/listings/table/table-basic.stories.ts
  stories/qa/table/table.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2142 [Components v3] Main menu
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/vars.scss
  packages/scss/src/components/navside/component.scss
  packages/scss/src/components/navside/mods.scss
  packages/scss/src/components/navside/vars.scss
  stories/qa/main-menu/main-menu.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2147 [Components v3] File
  packages/scss/src/components/file/component.scss
  packages/scss/src/components/file/index.scss
  packages/scss/src/components/file/mods.scss
  packages/scss/src/components/file/states.scss
  stories/documentation/forms/files/files-basic.stories.ts
  stories/documentation/forms/files/files-droppable.stories.ts
  stories/documentation/forms/files/files-error.stories.ts
  stories/documentation/forms/files/files-success.stories.ts
  stories/documentation/forms/files/files-uploading.stories.ts
  stories/qa/forms/files.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2139 [Components v3] Calendar
  packages/ng/date/src/lib/calendar/calendar-input.component.html
  packages/ng/date/src/lib/calendar/calendar-input.component.scss
  packages/ng/date/src/lib/calendar/calendar-input.component.ts
  packages/ng/styles/components/_calendar.scss
Labels: :bookmark::sparkles: Feature

#2151 [Components v3] Timeline
  packages/scss/src/components/timeline/component.scss
  packages/scss/src/components/timeline/index.scss
  packages/scss/src/components/timeline/mods.scss
  packages/scss/src/components/timeline/states.scss
  packages/scss/src/components/timeline/vars.scss
  stories/qa/timelines/timelines.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2146 [Components v3] Card
  packages/scss/src/components/card/component.scss
  packages/scss/src/components/card/index.scss
  packages/scss/src/components/card/mods.scss
  packages/scss/src/components/card/vars.scss
  stories/documentation/structure/cards/cards-action.stories.ts
  stories/documentation/structure/cards/cards-basic.stories.ts
  stories/documentation/structure/cards/cards-footer.stories.ts
  stories/qa/card/card.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2150 [Pagination] Remove border
  packages/scss/src/components/pagination/component.scss
  packages/scss/src/components/pagination/mods.scss
Labels: :bookmark::bug: FIX
