Repository LuccaSA/lucca-front, pull requests merged in 2023-09, with the labels that each got.

#2256 fix(wrappers): remove relicate inputs and fix Storybook control issues
  package-lock.json
  package.json
  stories/documentation/feedback/callout/angular/callout-basic.stories.ts
  stories/documentation/forms/inline-message/angular/inline-message-basic.stories.ts
Labels: 👥 Guilde Front, :hammer: Technical, :bookmark::bug: FIX, :book: Documentation changes

#2263 [Select] Remove !important on textfield padding
  packages/ng/styles/definitions/select/_select-input.scss
  packages/scss/src/components/field/component.scss
Labels: :hammer: Technical

#2260 [Button] Fix disabled + outlined + palette style
  packages/scss/src/components/button/states.scss
Labels: :bookmark::bug: FIX

#2266 [Clear] Fix color in callout context
  packages/scss/src/components/callout/component.scss
Labels: :bookmark::bug: FIX

#2275 Utils for overflow + Border radius !important
  packages/scss/src/commons/core.scss
  packages/scss/src/components/util/index.scss
Labels: :bookmark::sparkles: Feature

#2276 Icons & Button / Action icons
  packages/icons/src/icon/index.scss
  packages/icons/src/icon/mods.scss
  packages/scss/src/components/actionIcon/component.scss
  packages/scss/src/components/actionIcon/mods.scss
  packages/scss/src/components/button/component.scss
  packages/scss/src/components/button/mods.scss
  stories/documentation/texts/icons/icon-sizes.stories.ts
  stories/qa/icon/icon.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2279 Date format -> uppercase
  packages/ng/date/input/date-input.translate.ts
  packages/ng/date/select/date-select-input.translate.ts
Labels: :bookmark::bug: FIX

#2281 [Modal] Improve content padding
  packages/ng/styles/components/_popup.scss
Labels: :hammer: Technical

#2280 Add alternative palettes
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/vars.scss
  stories/qa/colors/colors.stories.html
  stories/qa/colors/colors.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2295 [Pagination] Fix icons
  stories/documentation/navigation/pagination/pagination-basic.stories.ts
  stories/documentation/navigation/pagination/pagination-compact.stories.ts
  stories/documentation/navigation/pagination/pagination-pages.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2216 refactor(icons): new LuccaIcon type
  build.js
  package.json
  packages/icons/README.md
  packages/icons/icons-list.js
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/package.json
  packages/icons/src/commons/config.scss
  packages/icons/update-icons.js
  packages/ng/callout/callout.component.ts
  stories/documentation/texts/icons/icon-basic.stories.html
  stories/documentation/texts/icons/icon-basic.stories.ts
  stories/documentation/texts/icons/icon-colors.stories.ts
  stories/documentation/texts/icons/icon-sizes.stories.ts
  stories/qa/icon/icon.stories.html
  stories/qa/icon/icon.stories.ts
  tsconfig.json
Labels: 👥 Guilde Front, :hammer: Technical, :book: Documentation changes
