Repository LuccaSA/lucca-front, pull requests merged in 2023-01, with the labels that each got.

#1950 Enh - expose function luUserDisplay
  packages/ng/user/src/lib/display/user-display.pipe.ts
Labels: :hammer: Technical

#1953 fix(sidepanel): Sidepanel where broken because of the new inject syntax
  packages/ng/modal/src/lib/modal.token.ts
Labels: :bookmark::bug: FIX

#1956 Fix missing overlaymodule
  packages/ng/popover/src/lib/trigger/popover-trigger.module.ts
  packages/ng/tooltip/src/lib/trigger/tooltip-trigger.module.ts
Labels: :bookmark::bug: FIX

#1960 Scrollbar stable
  packages/scss/src/commons/base.scss
Labels: :bookmark::sparkles: Feature

#1966 fix sidepanel overflow
  packages/ng/sidepanel/src/lib/sidepanel-panel.component.html
  packages/ng/styles/components/_sidepanel.scss
Labels: 👥 Guilde Design, :bookmark::bug: FIX

#1968 Fix date select
  packages/ng/core/src/lib/date/native/native-date.adapter.ts
  packages/ng/core/src/lib/date/string/string-date.adapter.spec.ts
  packages/ng/core/src/lib/date/string/string-date.adapter.ts
Labels: 👥 Guilde Front, :bookmark::bug: FIX

#1970 fix(establishment): pagination issues
  packages/ng/establishment/src/lib/select/searcher/establishment-searcher.component.html
  packages/ng/establishment/src/lib/select/searcher/establishment-searcher.component.ts
Labels: :bookmark::bug: FIX

#1952 Fix rxjs imports to support 6.x.x version in simple-select
  packages/ng/simple-select/src/lib/input/select-input.component.ts
  packages/ng/simple-select/src/lib/panel/panel.component.ts
Labels: :bookmark::bug: FIX

#1951 [v10.4.0] Fix rxjs imports to support 6.x.x version in simple-select
  packages/ng/simple-select/src/lib/input/select-input.component.ts
  packages/ng/simple-select/src/lib/panel/panel.component.ts
Labels: :bookmark::bug: FIX
