Repository LuccaSA/lucca-front, pull requests merged in 2023-10, with the labels that each got.

#2284 [Grid] Workaround classes
  stories/documentation/structure/grids/grids-responsive.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2299 Proposal to balance lines on titles
  packages/scss/src/components/title/component.scss
Labels: :bookmark::sparkles: Feature

#2285 Remove font variable option and remove utilities not present in DS
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/core.scss
Labels: :bookmark::bug: FIX

#2289 [Colors] Update decorative colors
  packages/scss/src/commons/config.scss
  stories/qa/colors/colors.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2305 Fix table sort + story
  packages/scss/src/components/tableSorted/states.scss
  stories/documentation/listings/table/table-sortable.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2242 Fieldset component
  packages/scss/src/components/fieldset/component.scss
  packages/scss/src/components/fieldset/exports.scss
  packages/scss/src/components/fieldset/index.scss
  packages/scss/src/components/fieldset/mods.scss
  packages/scss/src/components/fieldset/states.scss
  packages/scss/src/components/fieldset/vars.scss
  packages/scss/src/components/grid/component.scss
  packages/scss/src/components/index.scss
  stories/documentation/forms/fieldset/fieldset-basic.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2306 [Icons] October 23
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2309 FIX documentation
  README.md
Labels: :hammer: Technical

#2308 Add Lucca's palette
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/vars.scss
  stories/qa/colors/colors.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2312 Add utilitities for *-block and *-inline properties
  packages/scss/src/commons/core.scss
Labels: :bookmark::sparkles: Feature

#2313 remove refs to deleted text size classes
  stories/documentation/texts/text/text.stories.ts
  stories/qa/typography/typography.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2314 [Box] Arrow as mixin
  packages/scss/src/components/box/component.scss
  packages/scss/src/components/box/index.scss
  packages/scss/src/components/box/mods.scss
  packages/scss/src/components/box/vars.scss
  packages/scss/src/components/checkboxField/component.scss
  packages/scss/src/components/checkboxField/index.scss
  packages/scss/src/components/checkboxField/mods.scss
  packages/scss/src/components/radioField/component.scss
  packages/scss/src/components/radioField/index.scss
  packages/scss/src/components/radioField/mods.scss
  packages/scss/src/components/switchField/component.scss
  packages/scss/src/components/switchField/index.scss
  packages/scss/src/components/switchField/mods.scss
  stories/documentation/forms/arrow/arrow-basic.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2317 Icon-funnel is deprecated
  .storybook/styles.scss
Labels: :bookmark::bug: FIX

#2319 remove scrollbar-gutter
  packages/scss/src/commons/base.scss
Labels: :bookmark::bug: FIX

#2321 Fix typo on company icon
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/selection.json
Labels: :bookmark::bug: FIX

#2302 feat: new lu-icon component
  package.json
  packages/icons/README.md
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/src/commons/config.scss
  packages/icons/update-icons.js
  packages/ng/icon/icon.component.html
  packages/ng/icon/icon.component.scss
  packages/ng/icon/icon.component.ts
  packages/ng/icon/ng-package.json
  packages/ng/icon/public-api.ts
  stories/documentation/texts/icons/icon-basic.stories.ts
  stories/documentation/texts/icons/icon-colors.stories.ts
  stories/documentation/texts/icons/icon-sizes.stories.ts
Labels: 👥 Guilde Front, :bookmark::sparkles: Feature, :book: Documentation changes, :construction: Angular wrapper

#2267 refactor(core): support readonly in many inputs
  packages/ng/api/select/feeder/api-feeder.component.ts
  packages/ng/api/select/feeder/api-feeder.model.ts
  packages/ng/api/select/input/api-select-input.component.ts
  packages/ng/api/select/pager/api-pager.component.ts
  packages/ng/api/select/pager/api-pager.model.ts
  packages/ng/api/select/searcher/api-searcher.component.ts
  packages/ng/api/select/searcher/api-searcher.model.ts
  packages/ng/api/service/api-hybrid.service.ts
  packages/ng/api/service/api-service.model.ts
  packages/ng/api/service/api-v3.service.ts
  packages/ng/api/service/api-v4.service.ts
  packages/ng/department/select/feeder/department-feeder.component.ts
  packages/ng/department/select/input/department-select-input.component.ts
  packages/ng/department/service/department-v3.service.ts
  packages/ng/establishment/select/input/establishment-select-input.component.ts
  packages/ng/establishment/select/legal-unit-selector/legal-unit-selector.directive.ts
  packages/ng/establishment/select/searcher/establishment-searcher.component.ts
  packages/ng/establishment/select/select-all/establishment-select-all.component.ts
  packages/ng/establishment/service/establishment.service.ts
  packages/ng/establishment/service/legal-unit.service.ts
  packages/ng/formly/types/api.ts
  packages/ng/input/displayer/input-displayer.directive.ts
  packages/ng/input/displayer/input-displayer.model.ts
  packages/ng/option/operator/feeder/option-feeder.component.ts
  packages/ng/option/operator/for-options/for-options.directive.ts
  packages/ng/option/operator/option-operator.model.ts
  packages/ng/option/operator/pager/tree-option-pager.component.ts
  packages/ng/option/picker/option-picker-advanced.component.ts
  packages/ng/option/picker/option-picker.model.ts
  packages/ng/option/picker/tree-option-picker-advanced.component.ts
  packages/ng/option/picker/tree-option-picker.component.ts
  packages/ng/option/selector/all/select-all.component.ts
  packages/ng/option/selector/all/tree-select-all.component.ts
  packages/ng/option/selector/option-selector.model.ts
  packages/ng/picker/input-picker.model.ts
  packages/ng/popover/panel/popover-panel.model.ts
  packages/ng/qualification/select/input/qualification-select-input.component.ts
  packages/ng/schematics/lib/html-ast.ts
  packages/ng/schematics/lib/migration-test.ts
  packages/ng/schematics/lib/scss-ast.ts
  packages/ng/schematics/ng-add/tasks.ts
  packages/ng/select/input/select-input.model.ts
  packages/ng/simple-select/select.model.ts
  packages/ng/user/select/homonyms/user-homonyms.service.ts
  packages/ng/user/select/input/user-select-input.component.ts
  packages/ng/user/select/me/me-option.directive.ts
  packages/ng/user/select/searcher/user-searcher.component.ts
  packages/ng/user/service/user-v3.service.ts
  packages/scss/src/components/textfield/exports.scss
  stories/documentation/forms/department/department-select.stories.ts
  stories/documentation/texts/icons/icon-basic.stories.ts
  stories/helpers/stories.ts
  stories/qa/formly/formly.stories.ts
Labels: 👥 Guilde Front, :hammer: Technical, :book: Documentation changes

#2270 [Vertical navigation] Supports icon option
  packages/scss/src/components/verticalNavigation/component.scss
  packages/scss/src/components/verticalNavigation/index.scss
  packages/scss/src/components/verticalNavigation/mods.scss
  packages/scss/src/components/verticalNavigation/states.scss
  packages/scss/src/components/verticalNavigation/vars.scss
  stories/documentation/navigation/vertical-navigation/vertical-navigation-basic.stories.ts
  stories/qa/vertical-navigation/vertical-navigation.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2324 update grey 50/100/200
  packages/scss/src/commons/config.scss
Labels: :hammer: Technical

#2326 [Multiselect] Fix spacing and column height
  packages/ng/multi-select/panel/panel.component.scss
Labels: :bookmark::bug: FIX

#2328 fix left column spacing when search is not visible
  packages/ng/multi-select/panel/panel.component.scss
Labels: :bookmark::bug: FIX

#2327 feat(icons): automatic flags for deprecated icons
  .storybook/styles.scss
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/src/commons/config.scss
  packages/icons/update-icons.js
  packages/scss/src/components/textfield/exports.scss
  stories/documentation/texts/icons/icon-angular.stories.ts
  stories/documentation/texts/icons/icon-basic.stories.html
  stories/documentation/texts/icons/icon-basic.stories.ts
  stories/qa/icon/icon.stories.html
  stories/qa/icon/icon.stories.ts
Labels: 👥 Guilde Front, :hammer: Technical, :book: Documentation changes

#2329 Revert "refactor(core): support readonly in many inputs (#2267)"
  packages/ng/api/select/feeder/api-feeder.component.ts
  packages/ng/api/select/feeder/api-feeder.model.ts
  packages/ng/api/select/input/api-select-input.component.ts
  packages/ng/api/select/pager/api-pager.component.ts
  packages/ng/api/select/pager/api-pager.model.ts
  packages/ng/api/select/searcher/api-searcher.component.ts
  packages/ng/api/select/searcher/api-searcher.model.ts
  packages/ng/api/service/api-hybrid.service.ts
  packages/ng/api/service/api-service.model.ts
  packages/ng/api/service/api-v3.service.ts
  packages/ng/api/service/api-v4.service.ts
  packages/ng/department/select/feeder/department-feeder.component.ts
  packages/ng/department/select/input/department-select-input.component.ts
  packages/ng/department/service/department-v3.service.ts
  packages/ng/establishment/select/input/establishment-select-input.component.ts
  packages/ng/establishment/select/legal-unit-selector/legal-unit-selector.directive.ts
  packages/ng/establishment/select/searcher/establishment-searcher.component.ts
  packages/ng/establishment/select/select-all/establishment-select-all.component.ts
  packages/ng/establishment/service/establishment.service.ts
  packages/ng/establishment/service/legal-unit.service.ts
  packages/ng/formly/types/api.ts
  packages/ng/input/displayer/input-displayer.directive.ts
  packages/ng/input/displayer/input-displayer.model.ts
  packages/ng/option/operator/feeder/option-feeder.component.ts
  packages/ng/option/operator/for-options/for-options.directive.ts
  packages/ng/option/operator/option-operator.model.ts
  packages/ng/option/operator/pager/tree-option-pager.component.ts
  packages/ng/option/picker/option-picker-advanced.component.ts
  packages/ng/option/picker/option-picker.model.ts
  packages/ng/option/picker/tree-option-picker-advanced.component.ts
  packages/ng/option/picker/tree-option-picker.component.ts
  packages/ng/option/selector/all/select-all.component.ts
  packages/ng/option/selector/all/tree-select-all.component.ts
  packages/ng/option/selector/option-selector.model.ts
  packages/ng/picker/input-picker.model.ts
  packages/ng/popover/panel/popover-panel.model.ts
  packages/ng/qualification/select/input/qualification-select-input.component.ts
  packages/ng/schematics/lib/html-ast.ts
  packages/ng/schematics/lib/migration-test.ts
  packages/ng/schematics/lib/scss-ast.ts
  packages/ng/schematics/ng-add/tasks.ts
  packages/ng/select/input/select-input.model.ts
  packages/ng/simple-select/select.model.ts
  packages/ng/user/select/homonyms/user-homonyms.service.ts
  packages/ng/user/select/input/user-select-input.component.ts
  packages/ng/user/select/me/me-option.directive.ts
  packages/ng/user/select/searcher/user-searcher.component.ts
  packages/ng/user/service/user-v3.service.ts
  stories/documentation/forms/department/department-select.stories.ts
  stories/documentation/texts/icons/icon-basic.stories.ts
  stories/helpers/stories.ts
  stories/qa/formly/formly.stories.ts
Labels: 👥 Guilde Front, :bookmark::bug: FIX, :book: Documentation changes

#2331 Revert ligatures
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/selection.json
Labels: :bookmark::bug: FIX

#2332 fix ligatures
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/selection.json
Labels: :bookmark::bug: FIX

#2325 Numeric badge with a span
  packages/ng/numeric-badge/numeric-badge/numeric-badge.component.html
  packages/scss/src/components/textField/exports.scss
  stories/documentation/actions/button/button-counter.stories.ts
  stories/documentation/texts/numeric-badge/html&css/numeric-badge-basic.stories.ts
  stories/qa/button/button.stories.html
  stories/qa/numeric-badge/numeric-badge.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2335 chore(ci): use linux node
  Jenkinsfile
  packages/ng/establishment/establishment-select.spec.ts
  packages/scss/src/components/textField/component.scss
  packages/scss/src/components/textField/exports.scss
  packages/scss/src/components/textField/index.scss
  packages/scss/src/components/textField/mods.scss
  packages/scss/src/components/textField/states.scss
  packages/scss/src/components/textField/vars.scss
Labels: :hammer: Technical, :see_no_evil: No log

#2338 Status badge font weight
  packages/scss/src/components/statusBadge/component.scss
Labels: :bookmark::bug: FIX

#2361 Tag font weight
  packages/scss/src/components/tag/component.scss
Labels: :bookmark::bug: FIX

#2363 Skeleton in loaders folder
  stories/documentation/loaders/skeleton/skeleton-circle.stories.ts
  stories/documentation/loaders/skeleton/skeleton-dark.stories.ts
  stories/documentation/loaders/skeleton/skeleton-square.stories.ts
  stories/documentation/loaders/skeleton/skeleton-texts.stories.ts
  stories/documentation/loaders/skeleton/skeleton-titles.stories.ts
  stories/documentation/loaders/skeleton/skeleton-width.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2365 skeletons docs fixes
  stories/documentation/loaders/skeleton/skeleton-circle.stories.ts
  stories/documentation/loaders/skeleton/skeleton-dark.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2368 Box arrow as form-field
  packages/scss/src/components/checkboxField/index.scss
  packages/scss/src/components/checkboxField/mods.scss
  packages/scss/src/components/form/component.scss
  packages/scss/src/components/form/index.scss
  packages/scss/src/components/form/mods.scss
  packages/scss/src/components/switchField/index.scss
  packages/scss/src/components/switchField/mods.scss
  stories/documentation/structure/box/box-arrow.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2374 fix(icons): fix missing type export in built bundle
  build.js
  packages/icons/package.json
Labels: :hammer: Technical, :bookmark::bug: FIX

#2373 chore(ci): use linux node
  Jenkinsfile
  packages/ng/establishment/establishment-select.spec.ts
  packages/ng/form-field/form-field.component.scss
Labels: :hammer: Technical, :see_no_evil: No log

#2371 fix(select): invalid initial v4 sort
  packages/ng/simple-select/api/api-v4.directive.ts
Labels: :bookmark::bug: FIX

#2377 docs(core): Component docs improvements
  package-lock.json
  package.json
  packages/ng/forms/checkboxfield/checkboxfield.component.html
  packages/ng/forms/switchfield/switchfield.component.html
  stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
  stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
  stories/helpers/stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2372 feat(button): new button Angular directive
  .eslintrc
  angular.json
  packages/ng/button/button.component.scss
  packages/ng/button/button.component.ts
  packages/ng/button/ng-package.json
  packages/ng/button/public-api.ts
  stories/documentation/actions/button/button-wrapper.stories.ts
Labels: 👥 Guilde Front, :bookmark::sparkles: Feature, :book: Documentation changes, :construction: Angular wrapper

#2384 Fix select touched
  packages/ng/core-select/input/select-input.component.ts
Labels: :bookmark::bug: FIX

#2343 [Card] Fix unused variables
  packages/scss/src/components/card/component.scss
Labels: :bookmark::bug: FIX

#2354 refactor(core): components cleanup/upgrade
  packages/ng/form-field/form-field.component.html
  packages/ng/form-field/form-field.component.ts
  packages/ng/inline-message/inline-message.component.html
  packages/ng/inline-message/inline-message.component.ts
  packages/ng/multi-select/input/select-input.component.html
  packages/ng/multi-select/input/select-input.component.ts
  packages/ng/new-badge/new-badge.component.html
  packages/ng/new-badge/new-badge.component.ts
  packages/ng/numeric-badge/numeric-badge.component.html
  packages/ng/numeric-badge/numeric-badge.component.scss
  packages/ng/numeric-badge/numeric-badge.component.ts
  packages/ng/numeric-badge/numeric-badge/numeric-badge.component.html
  packages/ng/numeric-badge/numeric-badge/numeric-badge.component.ts
  packages/ng/numeric-badge/public-api.ts
  packages/ng/simple-select/input/select-input.component.html
  packages/ng/simple-select/input/select-input.component.ts
  packages/ng/simple-select/src/lib/input/select-input.component.html
Labels: 👥 Guilde Front, :hammer: Technical

#2316 Remove shrink/grow auto + remove font-weight
  packages/scss/src/commons/core.scss
Labels: :bookmark::bug: FIX

#2375 Stories format & HTML components
  stories/documentation/texts/icons/HTML&CSS/icon-sizes.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2334 fix icons nomenclature (open, close, bubble)
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :hammer: Technical

#2381 Fix date-select search with year granularity
  packages/ng/core/date/native/native-date.adapter.ts
Labels: :bookmark::bug: FIX

#2390 [Numeric Badge] Fix navside scope
  packages/scss/src/components/navside/component.scss
Labels: :bookmark::bug: FIX

#2386 [Textfield] mod-search + size incompatibility
  packages/scss/src/components/textfields/mods.scss
Labels: :bookmark::bug: FIX

#2391 [New badge] Lucca's palette instead of primary
  packages/scss/src/components/newBadge/component.scss
Labels: :bookmark::bug: FIX

#2393 [Inline message] Stories
  stories/documentation/forms/inline-message/html&css/inline-message-basic.stories.ts
  stories/documentation/forms/inline-message/html&css/inline-message-size.stories.ts
  stories/documentation/forms/inline-message/html&css/inline-message-states.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2387 [Radiobutton / Button] Box shadow
  packages/scss/src/components/button/mods.scss
  packages/scss/src/components/button/states.scss
  packages/scss/src/components/radioButtons/component.scss
  packages/scss/src/components/radioButtons/states.scss
Labels: :bookmark::bug: FIX

#2388 [luIcon] Fix component root size
  packages/ng/icon/icon.component.scss
Labels: :bookmark::bug: FIX
