Repository LuccaSA/lucca-front, pull requests merged in 2023-03, with the labels that each got.

#2023 feat(schematics): migrate lu-modal-header-close
  packages/ng/schematics/migrations/tshirt-size/mapping.ts
  packages/ng/schematics/migrations/tshirt-size/tests/template.input.html
  packages/ng/schematics/migrations/tshirt-size/tests/template.output.html
Labels: :hammer: Technical

#2024 [POC] docs(button): add dedicated mdx file
  .storybook/main.mjs
  stories/documentation/actions/button/button.mdx
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#1918 Merge Sidepanel into Modal
  packages/ng/modal/src/lib/modal-config.default.ts
  packages/ng/modal/src/lib/modal-config.model.ts
  packages/ng/modal/src/lib/modal-panel.component.html
  packages/ng/modal/src/lib/modal-panel.component.ts
  packages/ng/modal/src/lib/modal-ref.factory.ts
  packages/ng/modal/src/lib/modal-ref.model.ts
  packages/ng/modal/src/lib/modal.module.ts
  packages/ng/modal/src/lib/modal.service.ts
  packages/ng/modal/src/lib/modal.token.ts
  packages/ng/popup/src/lib/popup-ref.model.ts
  packages/ng/popup/src/lib/popup.service.ts
  packages/ng/sidepanel/src/lib/index.ts
  packages/ng/sidepanel/src/lib/sidepanel-config.default.ts
  packages/ng/sidepanel/src/lib/sidepanel-config.model.ts
  packages/ng/sidepanel/src/lib/sidepanel-panel.component.html
  packages/ng/sidepanel/src/lib/sidepanel-panel.component.scss
  packages/ng/sidepanel/src/lib/sidepanel-panel.component.ts
  packages/ng/sidepanel/src/lib/sidepanel-ref.factory.ts
  packages/ng/sidepanel/src/lib/sidepanel-ref.model.ts
  packages/ng/sidepanel/src/lib/sidepanel.model.ts
  packages/ng/sidepanel/src/lib/sidepanel.module.ts
  packages/ng/sidepanel/src/lib/sidepanel.service.ts
  packages/ng/sidepanel/src/lib/sidepanel.token.ts
  packages/ng/sidepanel/src/lib/sidepanel.translate.ts
  stories/documentation/overlays/sidepanel/sidepanel.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2032 fix(popup): size class
  packages/ng/popup/src/lib/popup-ref.model.ts
Labels: :bookmark::bug: FIX

#2034 [checkbox] UI improvments
  packages/scss/src/components/checkbox/component.scss
  packages/scss/src/components/checkbox/mods.scss
  packages/scss/src/components/checkbox/vars.scss
Labels: :bookmark::bug: FIX

#2026 [textfield/select] Increase cross size & fix colors
  packages/ng/api/src/lib/select/input/api-select-input.component.scss
  packages/ng/department/src/lib/select/input/department-select-input.component.scss
  packages/ng/establishment/src/lib/select/input/establishment-select-input.component.scss
  packages/ng/styles/definitions/select/_select-clearer.scss
  packages/ng/styles/definitions/select/_select-input.scss
  packages/ng/user/src/lib/select/input/user-select-input.component.scss
  packages/scss/src/components/actionIcon/component.scss
  packages/scss/src/components/textfield/index.scss
  packages/scss/src/components/textfield/mods.scss
  packages/scss/src/components/textfield/states.scss
Labels: 🎨 UI Adjustments, :bookmark::bug: FIX

#2038 [Checkbox] Fix vertical alignment
  packages/scss/src/components/checkbox/component.scss
  packages/scss/src/components/checkbox/mods.scss
Labels: :bookmark::bug: FIX

#2039 [Button] Fix vertical alignement if button have icon
  packages/scss/src/components/button/component.scss
Labels: :bookmark::bug: FIX

#2040 Bunch of Simple Select features
  .storybook/main.mjs
  .storybook/msw/handlers.ts
  .storybook/msw/mocks.ts
  packages/ng/simple-select/api/ng-package.json
  packages/ng/simple-select/api/src/lib/api-v3.directive.spec.ts
  packages/ng/simple-select/api/src/lib/api-v3.directive.ts
  packages/ng/simple-select/api/src/lib/api-v4.directive.ts
  packages/ng/simple-select/api/src/lib/api.directive.ts
  packages/ng/simple-select/api/src/public-api.ts
  packages/ng/simple-select/src/lib/index.ts
  packages/ng/simple-select/src/lib/input/panel-ref.factory.ts
  packages/ng/simple-select/src/lib/input/select-input.component.html
  packages/ng/simple-select/src/lib/input/select-input.component.ts
  packages/ng/simple-select/src/lib/input/select-input.models.ts
  packages/ng/simple-select/src/lib/option/default-option.component.ts
  packages/ng/simple-select/src/lib/option/disabled.directive.ts
  packages/ng/simple-select/src/lib/option/index.ts
  packages/ng/simple-select/src/lib/option/option-outlet.directive.ts
  packages/ng/simple-select/src/lib/option/option.component.html
  packages/ng/simple-select/src/lib/option/option.component.scss
  packages/ng/simple-select/src/lib/option/option.component.ts
  packages/ng/simple-select/src/lib/option/option.token.ts
  packages/ng/simple-select/src/lib/panel/index.ts
  packages/ng/simple-select/src/lib/panel/panel.component.html
  packages/ng/simple-select/src/lib/panel/panel.component.scss
  packages/ng/simple-select/src/lib/panel/panel.component.ts
  packages/ng/simple-select/src/lib/panel/panel.models.ts
  packages/ng/simple-select/src/lib/select.model.ts
  packages/ng/simple-select/src/lib/select.translate.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2044 ref(modal): add backdropclick to modal
  packages/ng/modal/src/lib/modal-panel.component.ts
  packages/ng/popup/src/lib/popup-ref.model.ts
  stories/documentation/overlays/modal/modal.stories.ts
  stories/documentation/overlays/sidepanel/sidepanel.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2047 Better.modal.typings
  packages/ng/modal/src/lib/modal-config.default.ts
  packages/ng/modal/src/lib/modal-config.model.ts
  packages/ng/modal/src/lib/modal-ref.model.ts
  packages/ng/sidepanel/src/lib/sidepanel.model.ts
Labels: :hammer: Technical

#2049 Story Sidepanel
  stories/documentation/overlays/sidepanel/sidepanel.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2051 ref(modal): no more popup inheritance + "open" correct return type
  packages/ng/modal/src/lib/modal-ref.model.ts
  packages/ng/modal/src/lib/modal.service.spec.ts
  packages/ng/modal/src/lib/modal.service.ts
  packages/ng/modal/src/lib/modal.token.ts
  packages/ng/popup/src/lib/popup.service.ts
  packages/ng/popup/src/lib/popup.token.ts
  packages/ng/sidepanel/src/lib/sidepanel.service.ts
Labels: :hammer: Technical

#2053 [BREAKING] Ref modal typings
  packages/ng/modal/src/lib/modal-ref.factory.ts
  packages/ng/modal/src/lib/modal-ref.model.ts
  packages/ng/modal/src/lib/modal.model.ts
  packages/ng/modal/src/lib/modal.service.ts
  packages/ng/popup/src/lib/popup-ref.model.ts
  packages/ng/popup/src/lib/popup.service.ts
  packages/ng/sidepanel/src/lib/sidepanel.model.ts
  packages/ng/sidepanel/src/lib/sidepanel.service.ts
Labels: :hammer: Technical

#2068 [Button] Text & XS
  packages/scss/src/components/button/index.scss
  packages/scss/src/components/button/mods.scss
Labels: :bookmark::sparkles: Feature

#2067 [Icons] March 23
  packages/icons/font/lucca-icons.eot
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.js
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: 👥 Guilde Design, :bookmark::sparkles: Feature, :book: Documentation changes

#2070 [Select] mod-S clearer position
  packages/ng/styles/definitions/select/_select-input.scss
Labels: :bookmark::bug: FIX
