Repository LuccaSA/lucca-front, pull requests merged in 2023-12, with the labels that each got.

#2429 Divider with text or action
  packages/scss/src/components/divider/component.scss
  packages/scss/src/components/divider/index.scss
  packages/scss/src/components/divider/mods.scss
  packages/scss/src/components/divider/vars.scss
  stories/documentation/structure/divider/divider-basic.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2435 [Icons] Fix icon default size
  packages/icons/src/icon/component.scss
  packages/scss/src/components/actionIcon/component.scss
  packages/scss/src/components/calloutAccordion/component.scss
  packages/scss/src/components/calloutDisclosure/component.scss
  packages/scss/src/components/calloutPopover/component.scss
Labels: 🎨 UI Adjustments, :bookmark::bug: FIX

#2445 fix inline message icon size + remove style encapsulation
  packages/ng/inline-message/inline-message.component.ts
  packages/scss/src/components/inlineMessage/component.scss
  packages/scss/src/components/inlineMessage/mods.scss
  packages/scss/src/components/inlineMessage/vars.scss
Labels: :bookmark::bug: FIX

#2447 Fix table sort icon direction
  packages/scss/src/components/tableSorted/mods.scss
  packages/scss/src/components/tableSorted/states.scss
Labels: :bookmark::bug: FIX

#2448 Fix table sort icon direction
  packages/scss/src/components/tableSorted/mods.scss
  packages/scss/src/components/tableSorted/states.scss
Labels: :bookmark::bug: FIX

#2454 FIX distorted avatars
  packages/ng/styles/definitions/user/user-picture.scss
Labels: 📖 Documentation changes, :bookmark::bug: FIX

#2453 FIX distorted avatars
  packages/ng/styles/definitions/user/user-picture.scss
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2450 Update README.md
  README.md
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2456 [Legacy Textfield] Fix clearer background
  packages/scss/src/components/textfields/mods.scss
  stories/qa/forms/textfield-legacy.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2460 Fix all palettes
  packages/scss/src/commons/config.scss
Labels: :bookmark::bug: FIX

#2459 fix(ngClazz): change detection not applied properly on ngClass value change
  packages/ng/core/tools/ng-clazz.directive.ts
  packages/ng/icon/icon.component.ts
  packages/ng/inline-message/inline-message.component.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#2455 chore(ci): bump Jenkins Shared Lib
  Jenkinsfile
Labels: :hammer: Technical

#2379 [Select] Add group by feature
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/option/group.directive.ts
  packages/ng/core-select/option/index.ts
  packages/ng/core-select/option/option.directive.ts
  packages/ng/core-select/panel/index.ts
  packages/ng/core-select/panel/panel.utils.ts
  packages/ng/core-select/select.model.ts
  packages/ng/forms/multi-select-field/multi-select-field.component.ts
  packages/ng/forms/simple-select-field/simple-select-field.component.ts
  packages/ng/multi-select/displayer/default-displayer.component.ts
  packages/ng/multi-select/displayer/displayer-input.directive.ts
  packages/ng/multi-select/input/panel-ref.factory.ts
  packages/ng/multi-select/input/select-input.component.ts
  packages/ng/multi-select/panel/panel.component.html
  packages/ng/multi-select/panel/panel.component.scss
  packages/ng/multi-select/panel/panel.component.ts
  packages/ng/multi-select/select.model.ts
  packages/ng/simple-select/api/api-v3.directive.spec.ts
  packages/ng/simple-select/input/select-input.component.ts
  packages/ng/simple-select/panel/panel.component.html
  packages/ng/simple-select/panel/panel.component.scss
  packages/ng/simple-select/panel/panel.component.ts
  packages/ng/simple-select/select.model.ts
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/select.utils.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2463 Master to rc
  Jenkinsfile
  package-lock.json
  package.json
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
  packages/ng/core-select/displayer/displayer.directive.ts
  packages/ng/core-select/option/option.directive.ts
  packages/ng/date/select/date-select-input.component.scss
  packages/ng/styles/definitions/user/user-picture.scss
  packages/scss/src/components/inlineMessage/component.scss
  packages/scss/src/components/inlineMessage/mods.scss
  packages/scss/src/components/inlineMessage/vars.scss
  packages/scss/src/components/textfields/mods.scss
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
  stories/documentation/overlays/modal/modal.stories.ts
  stories/qa/forms/textfield-legacy.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2466 [Callouts] Fix components height
  packages/scss/src/components/callout/component.scss
  packages/scss/src/components/calloutDisclosure/component.scss
  packages/scss/src/components/calloutPopover/component.scss
Labels: :bookmark::bug: FIX

#2451 [Icons] Add XXS to documentation
  packages/ng/icon/icon.component.ts
  stories/documentation/texts/icons/HTML&CSS/icon-sizes.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2468 New icon schematics
  packages/ng/form-field/form-field.component.html
  packages/ng/forms/textfield/textfield.component.html
  packages/ng/schematics/collection.json
  packages/ng/schematics/lib/angular-template.ts
  packages/ng/schematics/lib/file-update.ts
  packages/ng/schematics/lib/html-ast.ts
  packages/ng/schematics/lib/local-deps/package-lock.json
  packages/ng/schematics/lib/local-deps/package.json
  packages/ng/schematics/lib/migration-test.ts
  packages/ng/schematics/lib/scss-ast.ts
  packages/ng/schematics/lib/typescript-ast.ts
  packages/ng/schematics/migrations.json
  packages/ng/schematics/migrations/tshirt-size/mapping.ts
  packages/ng/schematics/migrations/tshirt-size/migration.ts
  packages/ng/schematics/migrations/tshirt-size/tests/component.input.ts
  packages/ng/schematics/migrations/tshirt-size/tests/component.output.ts
  packages/ng/schematics/migrations/tshirt-size/tests/styles.input.scss
  packages/ng/schematics/migrations/tshirt-size/tests/styles.output.scss
  packages/ng/schematics/migrations/tshirt-size/tests/template.input.html
  packages/ng/schematics/migrations/tshirt-size/tests/template.output.html
  packages/ng/schematics/new-icons/index.ts
  packages/ng/schematics/new-icons/mapping.ts
  packages/ng/schematics/new-icons/migration.spec.ts
  packages/ng/schematics/new-icons/migration.ts
  packages/ng/schematics/new-icons/tests/component.input.scss
  packages/ng/schematics/new-icons/tests/component.input.ts
  packages/ng/schematics/new-icons/tests/component.output.scss
  packages/ng/schematics/new-icons/tests/component.output.ts
  packages/ng/schematics/new-icons/tests/template.input.html
  packages/ng/schematics/new-icons/tests/template.output.html
  packages/ng/toast/toasts.component.ts
  stories/documentation/feedback/callout/html&css/callout-icons.stories.ts
  stories/documentation/feedback/callout/html&css/callout-tiny.stories.ts
  stories/documentation/forms/checkbox/checkbox-basic.stories.ts
  stories/documentation/forms/fields/text/html&css/textfield-info.stories.ts
  stories/documentation/forms/fields/text/html&css/textfield-search-clear.stories.ts
  stories/documentation/forms/form-label/form-label.stories.ts
  stories/documentation/forms/radio/radio-basic.stories.ts
  stories/documentation/forms/switch/switch-basic.stories.ts
  stories/documentation/listings/sortable-list/sortable-list-basic.stories.ts
  stories/documentation/navigation/vertical-navigation/vertical-navigation-basic.stories.ts
  stories/documentation/navigation/vertical-navigation/vertical-navigation-disabled.stories.ts
  stories/qa/form-label/form-label.stories.html
  stories/qa/forms/checkbox.stories.html
  stories/qa/forms/radio.stories.html
  stories/qa/forms/switch.stories.html
  stories/qa/forms/textfield-legacy.stories.html
  stories/qa/forms/textfield.stories.html
  stories/qa/vertical-navigation/vertical-navigation.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2473 [FIX] - translation deselect
  packages/ng/option/selector/all/select-all.translate.ts
Labels: 👥 Guilde Front, :bookmark::bug: FIX

#2458 [2457] Add open banana box on lu-callout-disclosure
  packages/ng/callout/callout-disclosure/callout-disclosure.component.html
  packages/ng/callout/callout-disclosure/callout-disclosure.component.ts
  stories/documentation/feedback/callout-disclosure/angular/callout-disclosure.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2449 Fix compilation for grid legacy stories
  stories/documentation/structure/grids-legacy/grids-auto-width.stories.ts
  stories/documentation/structure/grids-legacy/grids-basic.stories.ts
  stories/documentation/structure/grids-legacy/grids-horizontal-alignment.stories.ts
  stories/documentation/structure/grids-legacy/grids-justify.stories.ts
  stories/documentation/structure/grids-legacy/grids-offset.stories.ts
  stories/documentation/structure/grids-legacy/grids-sort.stories.ts
  stories/documentation/structure/grids-legacy/grids-vertical-alignment.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2437 [File upload] Fix cursor mode
  packages/scss/src/components/file/component.scss
  packages/scss/src/components/file/states.scss
Labels: :bookmark::bug: FIX
