Repository LuccaSA/lucca-front, pull requests merged in 2023-11, with the labels that each got.

#2392 [Card][Clickable] Add focus style
  packages/scss/src/components/card/mods.scss
  stories/qa/card/card.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2394 [Textfield] Remove outdated vars
  packages/scss/src/components/textfields/vars.scss
Labels: :hammer: Technical, :book: Documentation changes

#2395 [Select] Fix multi displayer, click zone and padding
  packages/ng/multi-select/displayer/default-displayer.component.scss
  packages/ng/styles/definitions/select/_select-input.scss
Labels: :bookmark::bug: FIX

#2399 fix(simple-select): URI encoding done twice instead of just once
  packages/ng/simple-select/api/api-v3.directive.ts
  packages/ng/simple-select/api/api-v4.directive.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#2400 Remove svg and ttf files for icofonts
  packages/icons/src/commons/base.scss
Labels: :bookmark::sparkles: Feature

#2389 [numericBadge] Nested compatibility
  packages/scss/src/components/button/states.scss
  packages/scss/src/components/menu/states.scss
  packages/scss/src/components/numericBadge/mods.scss
  packages/scss/src/components/numericBadge/states.scss
  packages/scss/src/components/radioButtons/component.scss
  packages/scss/src/components/radioButtons/states.scss
  stories/documentation/texts/status/status-basic.stories.ts
  stories/qa/button/button.stories.html
  stories/qa/forms/radio-buttons.stories.html
  stories/qa/menu/menu.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2401 refactor(wrappers): size now defaults to inherit rather than M
  packages/ng/button/button.component.ts
  packages/ng/callout/callout.component.ts
  packages/ng/form-field/form-field.component.ts
  packages/ng/forms/checkboxfield/checkboxfield.component.ts
  packages/ng/forms/switchfield/switchfield.component.ts
  packages/ng/forms/textfield/textfield.component.ts
  packages/ng/icon/icon.component.ts
  packages/ng/inline-message/inline-message.component.ts
  packages/ng/numeric-badge/numeric-badge.component.ts
Labels: 👥 Guilde Front, :hammer: Technical, :bookmark::bug: FIX

#2402 docs(button): new stories for luButton with icon and with counter
  stories/documentation/actions/button/angular/button-basic.stories.ts
  stories/documentation/actions/button/angular/button-counter.stories.ts
  stories/documentation/actions/button/angular/button-icon.stories.ts
Labels: 👥 Guilde Front, :hammer: Technical, 📖 Documentation changes, :book: Documentation changes

#2403 Fix NG wrap specificity
  packages/ng/styles/definitions/select/_select-input.scss
  packages/scss/src/components/button/component.scss
  packages/scss/src/components/button/mods.scss
  packages/scss/src/components/clear/component.scss
  packages/scss/src/components/clear/mods.scss
  packages/scss/src/components/clear/vars.scss
  packages/scss/src/components/numericBadge/index.scss
  packages/scss/src/components/numericBadge/mods.scss
  packages/scss/src/components/textfields/mods.scss
  stories/documentation/actions/button/angular/button-counter.stories.ts
  stories/qa/button/button.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2359 [UserPicture] Use initials in case of pictureHref error
  packages/ng/user/picture/user-picture.component.html
  packages/ng/user/picture/user-picture.component.ts
  stories/documentation/users/picture/picture.stories.ts
  stories/documentation/users/user.mocks.ts
Labels: 👥 Guilde Front, :bookmark::sparkles: Feature, :book: Documentation changes

#2411 chore: bump Jenkins Shared Lib
  Jenkinsfile
Labels: :hammer: Technical

#2412 Master to rc
  Jenkinsfile
Labels: :hammer: Technical

#2415 [Icon] Fix primary color
  packages/ng/icon/icon.component.scss
Labels: :bookmark::bug: FIX

#2417 [Button] Icon story typo
  stories/documentation/actions/button/button-icon.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2414 fix(button): fix compilation error when using luButton without a value
  packages/ng/button/button.component.ts
  stories/documentation/actions/button/angular/button-basic.stories.ts
  stories/documentation/actions/button/angular/button-counter.stories.ts
  stories/documentation/actions/button/angular/button-icon.stories.ts
Labels: 👥 Guilde Front, :bookmark::bug: FIX, :book: Documentation changes, :construction: Angular wrapper

#2419 [Vertical navigation] Fix active colors
  packages/scss/src/components/verticalNavigation/states.scss
Labels: :bookmark::bug: FIX

#2418 Fix color for decorative glacier 200
  packages/scss/src/commons/config.scss
Labels: :bookmark::bug: FIX

#2410 chore(deps): angular 17 support
  .eslintrc
  .storybook/main.mjs
  .storybook/msw/browser.ts
  .storybook/msw/handlers.ts
  .storybook/public/mockServiceWorker.js
  package-lock.json
  package.json
  packages/ng/package.json
Labels: 👥 Guilde Front, :hammer: Technical

#2425 LF 17.0
  .eslintrc
  .storybook/main.mjs
  .storybook/msw/browser.ts
  .storybook/msw/handlers.ts
  .storybook/public/mockServiceWorker.js
  package-lock.json
  package.json
  packages/ng/package.json
Labels: :hammer: Technical

#2427 [Icons] add spider & video
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2432 [Modal] Remove XXL from documentation
  stories/documentation/overlays/modal/modal.stories.ts
Labels: 📖 Documentation changes, :bookmark::bug: FIX, :book: Documentation changes

#2433 docs(core-select): typos + wrong import from simple-select
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :hammer: Technical, :book: Documentation changes
