Repository LuccaSA/lucca-front, pull requests merged in 2024-01, with the labels that each got.

#2470 [Card] Component focus style
  packages/scss/src/components/card/mods.scss
Labels: 👥 UI, :hammer: Technical

#2480 fix(callout): issue #2464 icon not displayed when iconless
  packages/ng/callout/callout-popover/callout-popover.component.html
Labels: :bookmark::bug: FIX

#2452 [Wrapped components] Fix style import on a bunch of new components
  packages/ng/callout/callout/callout.component.ts
  packages/ng/new-badge/new-badge.component.ts
  packages/ng/numeric-badge/numeric-badge.component.ts
Labels: :bookmark::bug: FIX

#2438 Action icon as a button mod
  packages/ng/multi-select/panel/panel.component.html
  packages/scss/src/components/actionIcon/index.scss
  packages/scss/src/components/button/index.scss
  packages/scss/src/components/button/mods.scss
  stories/documentation/actions/button/button-basic.stories.ts
  stories/documentation/actions/button/button-basic2.stories.ts
  stories/documentation/actions/button/button-icon.stories.ts
  stories/documentation/actions/button/button.mdx
  stories/documentation/actions/button/html&css/button-block.stories.ts
  stories/documentation/actions/button/html&css/button-counter.stories.ts
  stories/documentation/actions/button/html&css/button-disabled.stories.ts
  stories/documentation/actions/button/html&css/button-group.stories.ts
  stories/documentation/actions/button/html&css/button-only-icon.stories.ts
  stories/documentation/actions/button/html&css/button-palette.stories.ts
  stories/documentation/actions/button/html&css/button-size.stories.ts
  stories/documentation/actions/button/html&css/button-states.stories.ts
  stories/documentation/actions/button/html&css/button-style.stories.ts
  stories/documentation/actions/button/html&css/button-with-icon.stories.ts
  stories/documentation/navigation/skip-links/skip-links-basic.stories.ts
  stories/qa/button/button.stories.html
Labels: :hammer: Technical, :book: Documentation changes, 🦕 Deprecate

#2487 Update CODEOWNERS
  CODEOWNERS
Labels: :hammer: Technical, :see_no_evil: No log

#2485 chore(skip-links): use inject syntax
  packages/ng/a11y/skip-links/skip-links.component.ts
  tsconfig.json
Labels: 👥 Front, :hammer: Technical

#2489 Grid mod auto + rwd
  packages/scss/src/components/grid/index.scss
Labels: :bookmark::sparkles: Feature

#2491 [Callout Popover] Fix XS icon size & radius
  packages/scss/src/components/calloutPopover/mods.scss
Labels: :bookmark::bug: FIX

#2493 New shades for decoratives colors
  packages/scss/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2486 fix(commons): deprecated / as a division operator
  packages/scss/src/commons/utils/media.scss
Labels: :hammer: Technical

#2479 Demos for responsive grid (#2478)
  stories/documentation/structure/grids/grids-position-responsive.stories.ts
  stories/documentation/structure/grids/grids-responsive.stories.ts
  stories/documentation/structure/grids/grids-span-responsive.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2428 feat(stories): new function to generate story template args
  packages/ng/forms/abstract-field-component.ts
  stories/documentation/actions/button/angular/button-basic.stories.ts
  stories/documentation/actions/button/angular/button-counter.stories.ts
  stories/documentation/actions/button/angular/button-icon.stories.ts
  stories/documentation/feedback/callout-disclosure/angular/callout-disclosure.stories.ts
  stories/documentation/feedback/callout-popover/angular/callout-popover.stories.ts
  stories/documentation/feedback/callout/angular/callout-basic.stories.ts
  stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
  stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/helpers/stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2483 Pre-line
  packages/scss/src/commons/core.scss
Labels: :bookmark::sparkles: Feature

#2481 Dialog title
  packages/ng/styles/components/_popup.scss
Labels: :bookmark::sparkles: Feature

#2482 Radiofield
  packages/scss/src/components/checkboxField/mods.scss
  packages/scss/src/components/form/component.scss
  packages/scss/src/components/form/index.scss
  packages/scss/src/components/form/mods.scss
  packages/scss/src/components/inlineMessage/component.scss
  packages/scss/src/components/radioField/component.scss
  packages/scss/src/components/radioField/index.scss
  packages/scss/src/components/radioField/mods.scss
  packages/scss/src/components/radioField/states.scss
  packages/scss/src/components/radioField/vars.scss
  stories/documentation/forms/fields/checkbox/html&css/checkboxfield.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield-disabled.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield-invalid.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield-size.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield.stories.ts
  stories/documentation/forms/radio/radio-basic.stories.ts
  stories/documentation/structure/box/box-arrow.stories.ts
  stories/qa/forms/radio.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2488 enh(userSelect): issue #2422 allow to disable principal
  packages/ng/user/select/input/user-select-input.component.html
  packages/ng/user/select/input/user-select-input.component.ts
  stories/documentation/users/select/user-select.stories.html
  stories/documentation/users/select/user-select.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#2501 Border-radius full
  packages/ng/styles/definitions/user/user-picture.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/utils/loading.scss
  packages/scss/src/components/chip/component.scss
  packages/scss/src/components/clear/component.scss
  packages/scss/src/components/field/states.scss
  packages/scss/src/components/label/component.scss
  packages/scss/src/components/radio/component.scss
  packages/scss/src/components/radioField/component.scss
  packages/scss/src/components/radioField/vars.scss
  packages/scss/src/components/skeleton/mods.scss
  packages/scss/src/components/status/component.scss
  packages/scss/src/components/statusBadge/component.scss
  packages/scss/src/components/switch/component.scss
  packages/scss/src/components/switchField/component.scss
  packages/scss/src/components/textfields/mods.scss
  packages/scss/src/components/timeline/component.scss
  packages/scss/src/components/timeline/mods.scss
  packages/scss/src/components/toast/mods.scss
  stories/documentation/structure/grids-legacy/grids-auto-width.stories.ts
  stories/documentation/structure/grids-legacy/grids-basic.stories.ts
  stories/documentation/structure/grids-legacy/grids-horizontal-alignment.stories.ts
  stories/documentation/structure/grids-legacy/grids-justify.stories.ts
  stories/documentation/structure/grids-legacy/grids-offset.stories.ts
  stories/documentation/structure/grids-legacy/grids-sort.stories.ts
  stories/documentation/structure/grids-legacy/grids-vertical-alignment.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2503 Fixed dompurify dependency for ESBuild + Vite compatibility
  package-lock.json
  package.json
  packages/ng/package.json
  packages/ng/safe-content/safe-external-svg.pipe.ts
  packages/ng/safe-content/safe-html.pipe.ts
Labels: 👥 Front, 💥 Breaking change, :hammer: Technical

#2504 [Empty State] Increase content width
  packages/scss/src/components/emptyState/component.scss
Labels: :bookmark::bug: FIX

#2502 refactor(form-fields): changed the way fields are used in order to make them more flexible
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/option/option-outlet.directive.ts
  packages/ng/form-field/form-field.component.html
  packages/ng/form-field/form-field.component.ts
  packages/ng/form-field/public-api.ts
  packages/ng/forms/abstract-field-component.ts
  packages/ng/forms/checkbox-input/checkbox-input.component.html
  packages/ng/forms/checkbox-input/checkbox-input.component.ts
  packages/ng/forms/checkboxfield/checkboxfield.component.html
  packages/ng/forms/checkboxfield/checkboxfield.component.ts
  packages/ng/forms/multi-select-field/multi-select-field.component.html
  packages/ng/forms/multi-select-field/multi-select-field.component.ts
  packages/ng/forms/public-api.ts
  packages/ng/forms/simple-select-field/simple-select-field.component.html
  packages/ng/forms/simple-select-field/simple-select-field.component.ts
  packages/ng/forms/switch-input/switch-input.component.html
  packages/ng/forms/switch-input/switch-input.component.ts
  packages/ng/forms/switchfield/switchfield.component.html
  packages/ng/forms/switchfield/switchfield.component.ts
  packages/ng/forms/text-input/text-input-addon.ts
  packages/ng/forms/text-input/text-input.component.html
  packages/ng/forms/text-input/text-input.component.ts
  packages/ng/forms/text-input/text-input.translate.ts
  packages/ng/forms/textfield/textfield.component.html
  packages/ng/multi-select/displayer/default-displayer.component.ts
  packages/scss/src/components/simpleSelect/component.scss
  stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
  stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
  stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
  stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield-password.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
Labels: 👥 Front, 💥 Breaking change, :hammer: Technical, 🔺High priority, :book: Documentation changes

#2511 Empty state: fixes
  packages/ng/empty-state/empty-state-page/empty-state-page.component.html
  packages/ng/empty-state/empty-state-page/empty-state-page.component.scss
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
  packages/scss/src/components/emptyState/component.scss
  stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2512 Grid: fixes
  packages/scss/src/components/grid/index.scss
  packages/scss/src/components/grid/mods.scss
  stories/documentation/structure/grids/grids-auto-responsive.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2513 Fix RC 17.2
  packages/ng/multi-select/input/select-input.component.scss
  packages/ng/styles/components/_popup.scss
  packages/scss/src/components/button/index.scss
  packages/scss/src/components/button/mods.scss
  packages/scss/src/components/multiSelect/mods.scss
  stories/qa/button/button.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2515 Fix background color default for empty states
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/scss/src/components/emptyState/vars.scss
  stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.scss
  stories/qa/empty-state/empty-state-page.stories.scss
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2516 Change backgrounds colors
  .storybook/preview.mjs
  stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2517 New icon weatherLightning
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2523 [Storybook] Fixes related to grey 25 as default background color
  stories/documentation/integration/utilities/borders-radius.stories.ts
  stories/documentation/integration/utilities/borders.stories.ts
  stories/documentation/integration/utilities/shadows.stories.ts
  stories/documentation/structure/box/box-arrow.stories.ts
  stories/documentation/structure/box/box-basic.stories.ts
  stories/documentation/structure/box/box-killable.stories.ts
  stories/documentation/structure/box/box-toggle.stories.ts
  stories/documentation/structure/grids/grids-alignments.stories.ts
  stories/documentation/structure/grids/grids-auto-responsive.stories.ts
  stories/documentation/structure/grids/grids-auto.stories.ts
  stories/documentation/structure/grids/grids-basic.stories.ts
  stories/documentation/structure/grids/grids-form.stories.ts
  stories/documentation/structure/grids/grids-gap.stories.ts
  stories/documentation/structure/grids/grids-position-responsive.stories.ts
  stories/documentation/structure/grids/grids-position.stories.ts
  stories/documentation/structure/grids/grids-responsive.stories.ts
  stories/documentation/structure/grids/grids-span-responsive.stories.ts
  stories/documentation/structure/grids/grids-span.stories.ts
  stories/documentation/toolbox/animations/animations.scss
Labels: :hammer: Technical, :book: Documentation changes

#2519 [Gauge / Progress] Fix height & background color
  packages/scss/src/components/gauge/component.scss
  packages/scss/src/components/gauge/vars.scss
  packages/scss/src/components/progress/component.scss
  packages/scss/src/components/progress/vars.scss
Labels: :bookmark::bug: FIX

#2524 17.2 stories improvements
  stories/documentation/actions/button/html&css/button-only-icon.stories.ts
  stories/documentation/feedback/callout-disclosure/angular/callout-disclosure.stories.ts
  stories/documentation/feedback/callout-popover/angular/callout-popover.stories.ts
  stories/documentation/feedback/callout/angular/callout-basic.stories.ts
  stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
  stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
  stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
  stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/structure/grids/grids-gap.stories.ts
  stories/qa/colors/colors.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2521 Fix NgClazz directive.
  packages/ng/button/button.component.ts
  packages/ng/callout/callout-feedback-list/callout-feedback-list.component.ts
  packages/ng/core/public-api.ts
  packages/ng/core/tools/class.ts
  packages/ng/core/tools/ng-clazz.directive.ts
  packages/ng/form-field/form-field.component.ts
  packages/ng/inline-message/inline-message.component.ts
  packages/ng/numeric-badge/numeric-badge.component.ts
Labels: 👥 Front, :bookmark::bug: FIX

#2528 [Empty State] Content background / shadow only on page option
  packages/scss/src/components/emptyState/component.scss
  packages/scss/src/components/emptyState/mods.scss
Labels: :bookmark::bug: FIX

#2529 Hotfix/17.2.1
  packages/ng/button/button.component.ts
  packages/ng/callout/callout-feedback-list/callout-feedback-list.component.ts
  packages/ng/core/public-api.ts
  packages/ng/core/tools/class.ts
  packages/ng/core/tools/ng-clazz.directive.ts
  packages/ng/form-field/form-field.component.ts
  packages/ng/inline-message/inline-message.component.ts
  packages/ng/numeric-badge/numeric-badge.component.ts
  packages/scss/src/components/emptyState/component.scss
  packages/scss/src/components/emptyState/mods.scss
Labels: :bookmark::bug: FIX

#2532 docs(stories): stories and code display improvements
  stories/documentation/feedback/callout-popover/angular/callout-popover.stories.ts
  stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
  stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
  stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
  stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
  stories/documentation/users/select/user-select.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2537 17.3 Empty states stories
  stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.html
  stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.scss
  stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section-center.stories.html
  stories/documentation/feedback/empty-state/html&css/empty-state-section-center.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section-palette.stories.html
  stories/documentation/feedback/empty-state/html&css/empty-state-section-palette.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section.stories.html
  stories/documentation/feedback/empty-state/html&css/empty-state-section.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2538 Empty states stories format
  stories/documentation/feedback/empty-state/html&css/empty-state-section-center.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section-palette.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2539 Docs/stories improvements
  stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
  stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
  stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
  stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/select/multi-select.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2534 Button cleanup
  packages/scss/src/components/button/component.scss
  packages/scss/src/components/button/index.scss
  packages/scss/src/components/button/mods.scss
  packages/scss/src/components/button/states.scss
  packages/scss/src/components/button/vars.scss
  packages/scss/src/components/buttonGroup/mods.scss
  stories/documentation/actions/button/html&css/button-palette.stories.ts
  stories/documentation/actions/button/html&css/button-size.stories.ts
  stories/documentation/actions/button/html&css/button-states.stories.ts
  stories/documentation/actions/button/html&css/button-style.stories.ts
  stories/qa/button/button.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2541 [Icons] Add bank import
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature
