Repository LuccaSA/lucca-front, pull requests merged in 2024-03, with the labels that each got.

#2614 fix(lu-modal): panelClass settings + old select deprecation
  packages/ng/callout/callout-feedback-item/callout-feedback-item.component.ts
  packages/ng/dialog/dialog.service.ts
  packages/ng/dialog/model/dialog-config.ts
  packages/ng/establishment/establishment.module.ts
  packages/ng/establishment/select/establishment-select.module.ts
  packages/ng/establishment/select/input/establishment-select-input.component.ts
  packages/ng/modal/modal.service.ts
  packages/ng/qualification/qualification.module.ts
  packages/ng/qualification/select/input/qualification-select-input.component.ts
  packages/ng/qualification/select/input/qualification-select-input.module.ts
  packages/ng/qualification/select/qualification-select.module.ts
  packages/ng/select/input/select-input.component.ts
  packages/ng/select/input/select-input.module.ts
  packages/ng/select/select.module.ts
  packages/ng/user/select/input/user-select-input.component.ts
  packages/ng/user/select/input/user-select-input.module.ts
  packages/ng/user/select/user-select.module.ts
Labels: 👥 Front, :bookmark::bug: FIX

#2617 fix(core-select/select-input): placeholder
  packages/ng/core-select/input/select-input.component.ts
Labels: :bookmark::bug: FIX

#2619 fix(simple-select): disabled state not applied visually until new cd cycle
  packages/ng/core-select/input/select-input.component.ts
Labels: :bookmark::bug: FIX

#2587 Remove rgba colors – Add transparentize function
  .storybook/preview-head.html
  packages/ng/styles/components/cdk/_overlay.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/utils/color.scss
  packages/scss/src/commons/utils/index.scss
  packages/scss/src/commons/utils/loading.scss
  packages/scss/src/components/actionIcon/mods.scss
  packages/scss/src/components/checkbox/component.scss
  packages/scss/src/components/file/states.scss
  packages/scss/src/components/header/component.scss
  packages/scss/src/components/loading/mods.scss
  packages/scss/src/components/navside/component.scss
  packages/scss/src/components/progress/vars.scss
  packages/scss/src/components/textfields/states.scss
  stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.ts
  stories/documentation/integration/utilities/borders-radius.stories.ts
  stories/documentation/integration/utilities/borders.stories.ts
  stories/documentation/toolbox/animations/animations.scss
  stories/qa/tokens/tokens.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2620 HTML documentation for links
  stories/documentation/actions/links/link-basic.stories.ts
  stories/documentation/actions/links/link-disabled.stories.ts
  stories/documentation/actions/links/link-external.stories.ts
  stories/documentation/actions/links/link-hover.stories.ts
  stories/documentation/actions/links/link-nowrap.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2623 fix(select): position not updating when new options are set
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/panel/panel.models.ts
  packages/ng/multi-select/input/panel.model.ts
  packages/ng/simple-select/input/panel-ref.factory.ts
Labels: 👥 Front, :bookmark::bug: FIX

#2624 [Departement] Fix hozitontal spacing
  packages/ng/option/item/tree-option-item.component.scss
Labels: :bookmark::bug: FIX

#2625 [New selects] Add horizontal padding on empty state
  packages/ng/styles/components/_picker.scss
Labels: :bookmark::bug: FIX

#2627 [Schematics] Fix icons list
  packages/ng/schematics/new-icons/mapping.ts
Labels: :bookmark::bug: FIX

#2628 [Documentation] Link disabled stories
  stories/documentation/actions/links/link-disabled.stories.ts
  stories/documentation/actions/links/link-nowrap.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2632 fix(dialog): header missing customisation possibilities
  packages/ng/dialog/dialog-header/dialog-header.component.html
  packages/ng/dialog/dialog-header/dialog-header.component.ts
  packages/ng/modal/dialog-adapter/dialog-content-adapter/dialog-content-adapter.component.html
  packages/scss/src/components/dialog/component.scss
  packages/scss/src/components/dialog/vars.scss
  stories/documentation/overlays/dialog/dialog-basic.stories.ts
  stories/documentation/overlays/dialog/dialog-drawer.stories.ts
  stories/documentation/overlays/dialog/dialog-drawerFromBottom.stories.ts
  stories/documentation/overlays/dialog/dialog.stories.ts
Labels: 👥 Front, 👥 UI, :bookmark::bug: FIX, :book: Documentation changes

#2636 Stronger sticky header for dialogs
  packages/scss/src/components/dialog/component.scss
Labels: :bookmark::bug: FIX

#2638 [Navside] Reset numericBadge position in Compact mod
  packages/scss/src/components/navside/mods.scss
Labels: :bookmark::bug: FIX

#2630 [Utilities] Unit & commas deprecated
  packages/scss/src/components/util/index.scss
Labels: :hammer: Technical, 🦕 Deprecate

#2637 Fix styles for checkbox component
  packages/ng/forms/checkbox-input/checkbox-input.component.scss
  packages/ng/forms/checkbox-input/checkbox-input.component.ts
Labels: :bookmark::bug: FIX

#2640 [FormField] Fix component size with ? tooltip icon
  packages/scss/src/components/formLabel/component.scss
Labels: :bookmark::bug: FIX

#2641 fix(dialog): better id management for header title
  packages/ng/dialog/dialog-header/dialog-header.component.ts
Labels: :bookmark::bug: FIX

#2642 fix(core-select): wrong HttpParams when calling establishmentsCount and legalUnitsCount
  packages/ng/core-select/establishment/establishment-grouping.service.ts
Labels: :bookmark::bug: FIX

#2644 fix(core-select): missing filters input / fields / exportAs on LuCoreSelectUsersDirective
  packages/ng/core-select/user/users.directive.ts
Labels: :bookmark::bug: FIX

#2643 fix(form-field): ariaInvalid sometimes not applied properly and throwing error
  packages/ng/form-field/form-field.component.ts
Labels: :bookmark::bug: FIX

#2651 [Button] Succes & Error specificity
  packages/scss/src/components/button/index.scss
  stories/qa/button/button.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2650 fix(establishment): wrong query filter (use search instead of clue)
  packages/ng/core-select/establishment/establishments.directive.ts
  packages/ng/core-select/job-qualification/job-qualifications.directive.ts
Labels: :bookmark::bug: FIX

#2657 [Form Label] Fix * size
  packages/scss/src/components/formLabel/component.scss
Labels: :bookmark::bug: FIX

#2654 fix(dialog): fix result$ type being `T | void` while it shouldn't
  packages/ng/dialog/model/dialog-config.ts
  stories/documentation/overlays/dialog/dialog-service.stories.ts
Labels: :hammer: Technical, :bookmark::bug: FIX, :book: Documentation changes

#2660 feat(text-field): add `step` input and `noSpinButtons` flag to remove spin buttons
  packages/ng/forms/text-input/text-input.component.html
  packages/ng/forms/text-input/text-input.component.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2659 feat: Better sorting and display for grouped select
  .storybook/msw/handlers.ts
  .storybook/msw/helpers.ts
  packages/ng/core-select/establishment/establishments.directive.ts
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/job-qualification/job-qualifications.directive.ts
  packages/ng/core-select/option/group.pipe.ts
  packages/ng/core-select/option/index.ts
  packages/ng/core-select/option/option.component.html
  packages/ng/core-select/option/option.component.ts
  packages/ng/core-select/panel/index.ts
  packages/ng/core-select/panel/panel.utils.ts
  packages/ng/multi-select/panel/panel.component.html
  packages/ng/multi-select/panel/panel.component.ts
  packages/ng/simple-select/input/select-input.component.html
  packages/ng/simple-select/panel/panel.component.html
  packages/ng/simple-select/panel/panel.component.ts
  packages/ng/styles/components/_picker.scss
  packages/ng/styles/definitions/option/_option-item.scss
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/select.utils.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2665 [Icons] Money Check & Weather Stars
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2673 fix(select): panel position not updating on api data changes
  packages/ng/core-select/api/api.directive.ts
  stories/documentation/overlays/dialog/dialog-service.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2672 fix(multi-select): placeholder not showing on custom displayers
  packages/ng/multi-select/displayer/displayer-input.directive.ts
  stories/documentation/forms/select/multi-select.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2581 Tags with icon
  packages/scss/src/components/tag/component.scss
  packages/scss/src/components/tag/mods.scss
  stories/qa/tags/tags.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2605 Component callout refacto
  packages/scss/src/components/breadcrumbs/component.scss
  packages/scss/src/components/breadcrumbs/index.scss
  packages/scss/src/components/callout/component.scss
  packages/scss/src/components/callout/mods.scss
  packages/scss/src/components/callout/vars.scss
  stories/documentation/navigation/breadcrumbs/breadcrumbs-compact.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2661 feat(form-field): label can now be a ng-template or a string
  packages/ng/form-field/form-field.component.html
  packages/ng/form-field/form-field.component.ts
Labels: :bookmark::sparkles: Feature

#2678 [Textfield] Fix palettes
  packages/scss/src/components/textField/vars.scss
Labels: :bookmark::bug: FIX

#2601 feat(form-fields): new textarea-input wrapper
  packages/ng/form-field/form-field.component.ts
  packages/ng/forms/public-api.ts
  packages/ng/forms/textarea-input/textarea-input.component.html
  packages/ng/forms/textarea-input/textarea-input.component.ts
  packages/scss/src/components/textField/component.scss
  stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes, :triangular_ruler: Angular wrapper

#2674 feat(fields): new radio wrapper components
  packages/ng/form-field/form-field.component.html
  packages/ng/form-field/form-field.component.ts
  packages/ng/form-field/input.directive.ts
  packages/ng/forms/public-api.ts
  packages/ng/forms/radio-group-input/radio-group-input.component.scss
  packages/ng/forms/radio-group-input/radio-group-input.component.ts
  packages/ng/forms/radio-group-input/radio-group-token.ts
  packages/ng/forms/radio-group-input/radio/radio.component.html
  packages/ng/forms/radio-group-input/radio/radio.component.scss
  packages/ng/forms/radio-group-input/radio/radio.component.ts
  packages/scss/src/components/form/index.scss
  stories/documentation/forms/fields/radio/angular/radiofield.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield-size.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes, :triangular_ruler: Angular wrapper

#2612 Feat filter bar component
  packages/scss/src/components/divider/component.scss
  packages/scss/src/components/filterBar/component.scss
  packages/scss/src/components/filterBar/exports.scss
  packages/scss/src/components/filterBar/index.scss
  packages/scss/src/components/filterBar/mods.scss
  packages/scss/src/components/filterBar/states.scss
  packages/scss/src/components/filterBar/vars.scss
  packages/scss/src/components/grid/component.scss
  packages/scss/src/components/index.scss
  stories/documentation/structure/filter-bar/filter-bar-basic.stories.ts
  stories/qa/filterBar/filter-bar.stories.html
  stories/qa/filterBar/filter-bar.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2679 feat(checkbox): mixed input
  packages/ng/forms/checkbox-input/checkbox-input.component.html
  packages/ng/forms/checkbox-input/checkbox-input.component.ts
  stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#2681 [Secondary nav] Compact alert palette
  packages/scss/src/components/navside/vars.scss
Labels: :bookmark::bug: FIX

#2682 fix(input + dialog): undefined placeholder and modal flag
  packages/ng/dialog/dialog.service.ts
  packages/ng/forms/text-input/text-input.component.ts
Labels: :bookmark::bug: FIX

#2675 fix(establishment): wrong operations query param
  packages/ng/core-select/establishment/establishments.directive.ts
Labels: :bookmark::bug: FIX

#2500 Formlabel counter
  packages/ng/core/translate/index.ts
  packages/ng/core/translate/intl-params.pipe.spec.ts
  packages/ng/core/translate/intl-params.pipe.ts
  packages/ng/form-field/form-field.component.html
  packages/ng/form-field/form-field.component.ts
  packages/ng/form-field/form-field.translate.ts
  packages/ng/forms/text-input/text-input.component.ts
  packages/ng/forms/textarea-input/textarea-input.component.ts
  packages/scss/src/components/form/component.scss
  packages/scss/src/components/formLabel/component.scss
  packages/scss/src/components/formLabel/index.scss
  packages/scss/src/components/formLabel/mods.scss
  packages/scss/src/components/formLabel/states.scss
  packages/scss/src/components/formLabel/vars.scss
  packages/scss/src/components/textField/component.scss
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/fields/text/html&css/textfield-counter.stories.ts
  stories/documentation/forms/fields/text/html&css/textfield.stories.ts
  stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2685 Cloud Control palette
  packages/scss/src/commons/config.scss
Labels: :bookmark::bug: FIX

#2686 fix(multi-select): chip click opening panel
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/multi-select/input/select-input.component.ts
Labels: 👥 Front, :bookmark::bug: FIX

#2687 [Table] Parent & Collasped story
  stories/documentation/listings/table/table-basic.stories.ts
  stories/documentation/listings/table/table-parent.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2688 ref(user): use a more specific type for user related components
  packages/ng/user/display/user-display.pipe.ts
  packages/ng/user/picture/index.ts
  packages/ng/user/picture/user-picture.component.ts
  packages/ng/user/tile/user-tile.component.ts
Labels: :hammer: Technical

#2668 feat(schematics): new CssMapper class for easy CSS schematics along with 3 schematics
  packages/ng/dialog/dialog-header/dialog-header.component.html
  packages/ng/form-field/form-field.component.html
  packages/ng/forms/text-input/text-input.component.html
  packages/ng/schematics/action-icon/index.ts
  packages/ng/schematics/action-icon/migration.spec.ts
  packages/ng/schematics/action-icon/migration.ts
  packages/ng/schematics/action-icon/schema.json
  packages/ng/schematics/action-icon/tests/component.input.scss
  packages/ng/schematics/action-icon/tests/component.output.scss
  packages/ng/schematics/action-icon/tests/template.input.html
  packages/ng/schematics/action-icon/tests/template.output.html
  packages/ng/schematics/collection.json
  packages/ng/schematics/lib/css-mapper.ts
  packages/ng/schematics/palettes/index.ts
  packages/ng/schematics/palettes/migration.spec.ts
  packages/ng/schematics/palettes/schema.json
  packages/ng/schematics/palettes/tests/component.input.scss
  packages/ng/schematics/palettes/tests/component.input.ts
  packages/ng/schematics/palettes/tests/component.output.scss
  packages/ng/schematics/palettes/tests/component.output.ts
  packages/ng/schematics/palettes/tests/template.input.html
  packages/ng/schematics/palettes/tests/template.output.html
  packages/ng/schematics/tokens-spacing/index.ts
  packages/ng/schematics/tokens-spacing/migration.spec.ts
  packages/ng/schematics/tokens-spacing/schema.json
  packages/ng/schematics/tokens-spacing/tests/component.input.scss
  packages/ng/schematics/tokens-spacing/tests/component.input.ts
  packages/ng/schematics/tokens-spacing/tests/component.output.scss
  packages/ng/schematics/tokens-spacing/tests/component.output.ts
  packages/ng/schematics/tokens-spacing/tests/template.input.html
  packages/ng/schematics/tokens-spacing/tests/template.output.html
  stories/documentation/navigation/vertical-navigation/vertical-navigation-iconless.stories.ts
  stories/qa/vertical-navigation/vertical-navigation.stories.html
Labels: 👥 Front, :hammer: Technical, :book: Documentation changes

#2579 Expand clickable zone for chips button
  packages/scss/src/components/chip/component.scss
  packages/scss/src/components/chip/mods.scss
Labels: :bookmark::bug: FIX

#2631 Component sample
  packages/scss/src/components/_sample/component.scss
  packages/scss/src/components/_sample/exports.scss
  packages/scss/src/components/_sample/index.scss
  packages/scss/src/components/_sample/mods.scss
  packages/scss/src/components/_sample/states.scss
  packages/scss/src/components/_sample/vars.scss
Labels: :hammer: Technical

#2615 Fix overflow for table card with clickable lines
  packages/scss/src/components/table/mods.scss
  stories/documentation/listings/table/table-card.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes
