Repository LuccaSA/lucca-front, pull requests merged in 2024-04, with the labels that each got.

#2693 fix(core-select): stop escape propagation
  packages/ng/core-select/input/select-input.component.ts
Labels: :bookmark::bug: FIX

#2692 fix(core-select): fix operations query filter on users API
  packages/ng/core-select/user/users.directive.ts
Labels: :bookmark::bug: FIX

#2694 Fix icon size fallback
  packages/icons/src/icon/component.scss
  packages/icons/src/icon/vars.scss
Labels: :bookmark::bug: FIX

#2695 [Callout] Fix gap
  packages/scss/src/components/callout/mods.scss
  packages/scss/src/components/callout/vars.scss
Labels: :bookmark::bug: FIX

#2590 Component.index.table
  packages/scss/src/commons/utils/media.scss
  packages/scss/src/components/index.scss
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/indexTable/exports.scss
  packages/scss/src/components/indexTable/index.scss
  packages/scss/src/components/indexTable/mods.scss
  packages/scss/src/components/indexTable/states.scss
  packages/scss/src/components/indexTable/vars.scss
  packages/scss/src/components/indexTableSorted/component.scss
  packages/scss/src/components/indexTableSorted/exports.scss
  packages/scss/src/components/indexTableSorted/index.scss
  packages/scss/src/components/indexTableSorted/mods.scss
  packages/scss/src/components/indexTableSorted/states.scss
  packages/scss/src/components/indexTableSorted/vars.scss
  stories/documentation/listings/index-table/index-table-actions.stories.ts
  stories/documentation/listings/index-table/index-table-basic.stories.ts
  stories/documentation/listings/index-table/index-table-empty-state.stories.ts
  stories/documentation/listings/index-table/index-table-footer.stories.ts
  stories/documentation/listings/index-table/index-table-interactive-nested-selectable.stories.html
  stories/documentation/listings/index-table/index-table-interactive-nested-selectable.stories.ts
  stories/documentation/listings/index-table/index-table-layout-fixed.stories.ts
  stories/documentation/listings/index-table/index-table-mass-selection-and-pagination.stories.ts
  stories/documentation/listings/index-table/index-table-nested-selectable.stories.ts
  stories/documentation/listings/index-table/index-table-nested.stories.ts
  stories/documentation/listings/index-table/index-table-responsive-card-list.stories.ts
  stories/documentation/listings/index-table/index-table-selectable.stories.ts
  stories/documentation/listings/index-table/index-table-sorted.stories.ts
  stories/documentation/listings/index-table/index-table-stackable.stories.ts
  stories/documentation/listings/index-table/index-table-sticky-header.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2602 Component container refacto
  packages/scss/src/components/container/component.scss
  packages/scss/src/components/container/mods.scss
  packages/scss/src/components/container/vars.scss
  stories/documentation/structure/containers/containers-basic.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2691 Skeletons : mod alignRight + mod alignCenter
  packages/scss/src/components/skeleton/index.scss
  packages/scss/src/components/skeleton/mods.scss
  packages/scss/src/components/skeleton/states.scss
  packages/scss/src/components/skeleton/vars.scss
  stories/documentation/loaders/skeleton/skeleton-align.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2698 Fix.index table
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/indexTable/mods.scss
Labels: :bookmark::bug: FIX

#2699 Apply schematics on last 17.4 PR
  packages/ng/styles/components/_picker.scss
  packages/scss/src/components/callout/mods.scss
  packages/scss/src/components/callout/vars.scss
  packages/scss/src/components/filterBar/component.scss
  packages/scss/src/components/formLabel/component.scss
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/indexTable/mods.scss
  packages/scss/src/components/indexTable/vars.scss
  packages/scss/src/components/tag/component.scss
  stories/qa/tags/tags.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2704 fix(schematics): export schema.json during build
  build.js
Labels: :hammer: Technical, :bookmark::bug: FIX

#2705 fix(core-select): wrong users loading params and too much nextPage events
  .storybook/msw/mocks.ts
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/user/user-homonym.service.ts
  packages/ng/core-select/user/users.directive.ts
Labels: :bookmark::bug: FIX

#2703 fix(core-select): do not submit englobing form when hitting enter
  packages/ng/core-select/input/select-input.component.ts
Labels: :bookmark::bug: FIX

#2706 [CDK autoresize] Fix generated height
  packages/ng/styles/components/cdk/_textarea.scss
Labels: :bookmark::bug: FIX

#2707 [Timeline] Misc mod combo fixes & stories
  packages/scss/src/components/timeline/index.scss
  packages/scss/src/components/timeline/mods.scss
  packages/scss/src/components/timeline/states.scss
  stories/documentation/listings/timelines/timelines-dashed.stories.ts
  stories/qa/timelines/timelines.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2708 chore: add mandatory button type eslint rule
  .eslintrc
  packages/ng/forms/text-input/text-input.component.html
  packages/ng/multi-select/input/select-input.component.html
Labels: :bookmark::bug: FIX

#2711 Update 17.4 RC
  .eslintrc
  .storybook/msw/mocks.ts
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/user/user-homonym.service.ts
  packages/ng/core-select/user/users.directive.ts
  packages/ng/forms/number-input/number-input.component.html
  packages/ng/forms/text-input/text-input.component.html
  packages/ng/multi-select/input/select-input.component.html
  packages/scss/src/components/indexTable/component.scss
Labels: :hammer: Technical

#2649 User Popover
  .storybook/msw/handlers.ts
  .storybook/msw/mocks.ts
  docs/user-popover.md
  package-lock.json
  package.json
  packages/ng/popup-employee/README.md
  packages/ng/popup-employee/card/panel/user-popover-panel.component.html
  packages/ng/popup-employee/card/panel/user-popover-panel.component.scss
  packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
  packages/ng/popup-employee/card/panel/user-popover-panel.model.ts
  packages/ng/popup-employee/card/pipe/inject-parameter.pipe.ts
  packages/ng/popup-employee/card/pipe/is-future.pipe.ts
  packages/ng/popup-employee/card/pipe/leave-ends-display.pipe.ts
  packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts
  packages/ng/popup-employee/ng-package.json
  packages/ng/popup-employee/popup-employee.translate.ts
  packages/ng/popup-employee/public-api.ts
  packages/ng/popup-employee/service/user-popover-service.model.ts
  packages/ng/popup-employee/service/user-popover.store.ts
  packages/ng/popup-employee/user-popover.model.ts
  packages/ng/popup-employee/user-popover.providers.ts
  packages/ng/styles/definitions/user/user-picture.scss
  packages/scss/src/components/index.scss
  packages/scss/src/components/userPopover/component.scss
  packages/scss/src/components/userPopover/exports.scss
  packages/scss/src/components/userPopover/index.scss
  packages/scss/src/components/userPopover/mods.scss
  packages/scss/src/components/userPopover/states.scss
  packages/scss/src/components/userPopover/vars.scss
  stories/documentation/users/popover/popover.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#2712 fix(schematics): template schematics skipping control flow blocks
  packages/ng/schematics/lib/html-ast.ts
  packages/ng/schematics/tokens-spacing/tests/template.input.html
  packages/ng/schematics/tokens-spacing/tests/template.output.html
Labels: 👥 Front, :hammer: Technical

#2717 fix(core-select): do not make id overridable in getMe method
  packages/ng/core-select/user/users.directive.ts
Labels: :bookmark::bug: FIX

#2713 test(dialog): new testing entrypoint for data testing provider
  packages/ng/dialog/testing/ng-package.json
  packages/ng/dialog/testing/providers.ts
  packages/ng/dialog/testing/public-api.ts
Labels: 👥 Front, :hammer: Technical

#2714 chore(deps): Storybook 8
  .editorconfig
  .storybook/preview.mjs
  package-lock.json
  package.json
  stories/documentation/structure/grids/grids-auto-responsive-container.stories.ts
  stories/documentation/structure/grids/grids-auto-responsive.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2718 [ZH] Test fix control type Select
  stories/documentation/texts/numeric-badge/html&css/numeric-badge-basic.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2719 Fix detect changes in user popover
  packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2723 [Tokens Spacings] Add 25
  packages/scss/src/commons/config.scss
  packages/scss/src/components/calloutPopover/mods.scss
  packages/scss/src/components/checkboxField/vars.scss
  packages/scss/src/components/formLabel/component.scss
  packages/scss/src/components/radioField/vars.scss
  packages/scss/src/components/switchField/component.scss
  stories/qa/tokens/tokens.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2722 fix(empty-state): http request for icon still fired even when it's null
  packages/ng/empty-state/empty-state-page/empty-state-page.component.html
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/ng/empty-state/empty-state-section/empty-state-section.component.html
  packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
  packages/ng/safe-content/safe-external-svg.pipe.ts
Labels: 👥 Front, :bookmark::bug: FIX

#2727 fix(portal): handle string update
  packages/ng/core/portal/portal.directive.spec.ts
  packages/ng/core/portal/portal.directive.ts
Labels: :bookmark::bug: FIX

#2729 [17.4] Format stories
  stories/documentation/forms/fields/radio/angular/radiofield.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield-disabled.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield-invalid.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield-size.stories.ts
  stories/documentation/forms/fields/radio/html&css/radiofield.stories.ts
  stories/documentation/forms/form-label/form-label-basic.stories.ts
  stories/documentation/forms/form-label/form-label-counter.stories.ts
  stories/documentation/forms/form-label/form-label-error.stories.ts
  stories/documentation/forms/form-label/form-label-size.stories.ts
  stories/documentation/forms/form-label/form-label.stories.ts
  stories/documentation/listings/index-table/index-table-actions-touch-detection.stories.ts
  stories/documentation/listings/index-table/index-table-layout-fixed-responsive.stories.ts
  stories/documentation/listings/index-table/index-table-nested-sub-totals.stories.ts
  stories/documentation/listings/index-table/index-table-nested.stories.ts
  stories/documentation/listings/index-table/index-table-responsive-card-list-custom.stories.ts
  stories/documentation/listings/index-table/index-table-responsive-card-list-label.stories.ts
  stories/documentation/listings/index-table/index-table-responsive-card-list-nested.stories.ts
  stories/documentation/users/popover/popover.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2730 [Index Table] Prevent row to go over sticky header
  packages/scss/src/components/indexTable/mods.scss
Labels: :bookmark::bug: FIX

#2731 fix(user-popover): fix initial position after employee is loaded
  packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
  packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts
Labels: :bookmark::bug: FIX

#2725 [EmptyState] Tweaks for narrow views
  packages/scss/src/components/emptyState/mods.scss
Labels: 👥 UI, :bookmark::sparkles: Feature, :book: Documentation changes

#2732 [17.4] RC > Master
  contributing.md
  packages/ng/core-select/user/users.directive.ts
  packages/ng/dialog/testing/ng-package.json
  packages/ng/dialog/testing/providers.ts
  packages/ng/dialog/testing/public-api.ts
  packages/ng/empty-state/empty-state-page/empty-state-page.component.html
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/ng/empty-state/empty-state-section/empty-state-section.component.html
  packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
  packages/ng/safe-content/safe-external-svg.pipe.ts
  packages/ng/schematics/lib/html-ast.ts
  packages/ng/schematics/tokens-spacing/tests/template.input.html
  packages/ng/schematics/tokens-spacing/tests/template.output.html
  packages/scss/src/components/emptyState/mods.scss
Labels: :hammer: Technical, :bookmark::bug: FIX

#2734 [Callout feedback] Decrease gap
  packages/scss/src/components/calloutFeedbackList/component.scss
  packages/scss/src/components/calloutFeedbackList/mods.scss
  packages/scss/src/components/calloutFeedbackList/vars.scss
Labels: :bookmark::bug: FIX

#2728 feat(core-select): addOption button
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/select.translate.ts
  packages/ng/multi-select/panel/panel.component.html
  packages/ng/multi-select/panel/panel.component.ts
  packages/ng/simple-select/panel/panel.component.html
  packages/ng/simple-select/panel/panel.component.ts
  packages/ng/styles/components/_picker.scss
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/select.utils.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2735 [Form label] Mandatory asterisk ui
  packages/scss/src/components/formLabel/component.scss
Labels: :bookmark::bug: FIX

#2738 17.4 Format stories
  stories/documentation/actions/button/angular/button-basic.stories.ts
  stories/documentation/actions/button/angular/button-counter.stories.ts
  stories/documentation/actions/button/angular/button-icon.stories.ts
  stories/documentation/forms/fields/radio/angular/radiofield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
  stories/documentation/forms/fields/textarea/html&css/textareafield.stories.ts
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2740 fix(users.directive): formerEmployee query param & avoid infinite recursion
  packages/ng/core-select/user/users.directive.ts
Labels: :bookmark::bug: FIX

#2749 Add wrapper with .u-mask
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
Labels: :bookmark::sparkles: Feature

#2753 feat(date): add humanize pipe
  packages/ng/date/humanize/humanize.formatter.ts
  packages/ng/date/humanize/humanize.model.ts
  packages/ng/date/humanize/humanize.pipe.ts
  packages/ng/date/humanize/humanize.utils.spec.ts
  packages/ng/date/humanize/humanize.utils.ts
  packages/ng/date/humanize/index.ts
  packages/ng/date/public-api.ts
  stories/documentation/toolbox/date/humanize.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2754 fix(user-popover): background color not matching user-picture
  packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
Labels: :bookmark::bug: FIX

#2748 docs(core-select): API and Users guides
  .editorconfig
  .storybook/msw/handlers.ts
  .storybook/msw/helpers.ts
  docs/core-select-api-directive.md
  docs/core-select-users-directive.md
  packages/ng/core-select/user/user-option.component.ts
  packages/ng/core-select/user/user-option.model.ts
  packages/ng/core-select/user/users.directive.ts
  stories/documentation/forms/select/custom-api-example.component.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2756 [Simple & Multi Select] Expose MAGIC_PAGE_SIZE and update doc.
  docs/core-select-users-directive.md
  packages/ng/core-select/api/api-v3.directive.spec.ts
  packages/ng/core-select/api/api.directive.ts
  packages/ng/core-select/api/public-api.ts
Labels: :hammer: Technical, :book: Documentation changes

#2761 [Secondary nav] Fix inverted deprecated alert color when item is active
  packages/scss/src/components/navside/states.scss
Labels: :bookmark::bug: FIX

#2763 Color fix for elevations and box shadows
  packages/scss/src/commons/config.scss
Labels: :bookmark::bug: FIX

#2757 Fix for border on checkbox and revert with only one pseudo-element
  packages/scss/src/components/checkbox/component.scss
  packages/scss/src/components/checkbox/states.scss
  stories/qa/forms/checkbox-legacy.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2765 [Schematics] Remove chart levels from icons schematics
  packages/ng/schematics/new-icons/mapping.ts
Labels: :bookmark::bug: FIX

#2770 [Datepicker] Invalid cover
  packages/ng/styles/definitions/select/_select-input.scss
Labels: :bookmark::bug: FIX

#2769 feat(text-input): add url as valid type
  packages/ng/forms/text-input/text-input.component.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2764 fix(lu-select): panel position not updating when options change
  packages/ng/option/picker/option-picker.component.ts
  packages/ng/option/picker/tree-option-picker.component.ts
  packages/ng/popover/panel/popover-panel.model.ts
  packages/ng/popover/trigger/popover-trigger.model.ts
  packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
  packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#2772 [Documentation] Add version to Angular textfield url option
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
Labels: :hammer: Technical, :book: Documentation changes
