Repository LuccaSA/lucca-front, pull requests merged in 2024-09, with the labels that each got.

#3056 fix(phone-number-input): catch libphonenumber-js exceptions
  packages/ng/forms/phone-number-input/phone-number-input.component.ts
Labels: :bookmark::bug: FIX

#3049 feat(phone-number-input): country name display & search
  packages/ng/forms/phone-number-input/phone-number-input.component.html
  packages/ng/forms/phone-number-input/phone-number-input.component.ts
Labels: :bookmark::sparkles: Feature

#3063 date pipe custom format options
  packages/ng/date/input/date-input.directive.ts
  packages/ng/date/select/date-select-input.component.ts
Labels: :bookmark::bug: FIX

#3054 feat(popover): add exportAs and provide close method
  packages/ng/popover2/popover.directive.ts
Labels: :bookmark::sparkles: Feature

#3051 Fix tooltip + popover
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
Labels: :bookmark::bug: FIX

#3057 Fix tag outlined color
  packages/scss/src/components/tag/component.scss
  packages/scss/src/components/tag/mods.scss
  packages/scss/src/components/tag/vars.scss
Labels: :bookmark::bug: FIX

#3066 [Pagination] content adjustement
  stories/documentation/listings/index-table/index-table-mass-selection-and-pagination.stories.ts
  stories/documentation/navigation/pagination/pagination-basic.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3053 Fix ellipsis calculation
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
  stories/documentation/overlays/tooltip/tooltip-ellipsis.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3064 Fix selector specificity for nested components
  packages/ng/dialog/dialog-header/dialog-header.component.html
  packages/ng/popover2/content/popover-content/popover-content.component.html
  packages/ng/toast/toasts.component.html
  packages/scss/src/components/calloutAccordion/mods.scss
  packages/scss/src/components/calloutDisclosure/mods.scss
  packages/scss/src/components/calloutPopover/mods.scss
  packages/scss/src/components/dialog/component.scss
  packages/scss/src/components/footer/component.scss
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/multiSelect/mods.scss
  packages/scss/src/components/plgPush/component.scss
  packages/scss/src/components/popover/component.scss
  packages/scss/src/components/simpleSelect/mods.scss
  packages/scss/src/components/switchField/component.scss
  packages/scss/src/components/tableSortable/index.scss
  packages/scss/src/components/textField/mods.scss
  packages/scss/src/components/textfields/mods.scss
  packages/scss/src/components/toast/component.scss
  packages/scss/src/components/userPopover/component.scss
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3047 [MultiSelect] Fix placeholder color for invalid state
  packages/scss/src/components/multiSelect/component.scss
Labels: :bookmark::bug: FIX

#3067 [Footer] Fix container width
  packages/scss/src/components/footer/component.scss
  packages/scss/src/components/footer/vars.scss
Labels: :bookmark::bug: FIX

#3055 segmentedControl
  Jenkinsfile
  e2e/NuGet.Config
  packages/scss/src/components/index.scss
  packages/scss/src/components/segmentedControl/component.scss
  packages/scss/src/components/segmentedControl/exports.scss
  packages/scss/src/components/segmentedControl/index.scss
  packages/scss/src/components/segmentedControl/mods.scss
  packages/scss/src/components/segmentedControl/states.scss
  packages/scss/src/components/segmentedControl/vars.scss
  packages/scss/src/components/viewTabs/component.scss
  packages/scss/src/components/viewTabs/index.scss
  packages/scss/src/components/viewTabs/mods.scss
  packages/scss/src/components/viewTabs/states.scss
  packages/scss/src/components/viewTabs/vars.scss
  stories/documentation/navigation/segmentedControl/segmentedControl-filter.stories.ts
  stories/documentation/navigation/segmentedControl/segmentedControl-tabs.stories.ts
  stories/documentation/navigation/viewTabs/viewTabs-basic.stories.ts
Labels: :bookmark::sparkles: Feature, :hammer: Technical, :book: Documentation changes

#3060 feat(phone-number-input): set country and format incomplete
  packages/ng/forms/phone-number-input/phone-number-input.component.html
  packages/ng/forms/phone-number-input/phone-number-input.component.ts
  packages/ng/forms/phone-number-input/validators.ts
  stories/documentation/forms/fields/phone-number-input/angular/phone-number-input.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#3074 fix(phone-number-input): validator wasn't using missing the country code
  packages/ng/forms/phone-number-input/validators.ts
Labels: 👥 Front, :hammer: Technical, :bookmark::bug: FIX, :book: Documentation changes

#3075 feat(dialog): handle all Route config options in dialogRouteFactory
  packages/ng/dialog/dialog-routing/dialog-routing.models.ts
  packages/ng/dialog/dialog-routing/dialog-routing.utils.spec.ts
  packages/ng/dialog/dialog-routing/dialog-routing.utils.ts
Labels: :bookmark::sparkles: Feature

#2972 v4 departments api
  packages/ng/department/department-select.spec.ts
  packages/ng/department/select/feeder/department-feeder.component.ts
  packages/ng/department/service/department-v3.service.ts
  packages/ng/department/service/department-v4.service.ts
  packages/ng/department/service/index.ts
Labels: :hammer: Technical

#3077 [18.2.2] Update RC
  packages/ng/date/input/date-input.directive.ts
  packages/ng/date/select/date-select-input.component.ts
  packages/ng/dialog/dialog-header/dialog-header.component.html
  packages/ng/forms/phone-number-input/phone-number-input.component.html
  packages/ng/forms/phone-number-input/phone-number-input.component.ts
  packages/ng/forms/phone-number-input/validators.ts
  packages/ng/popover2/content/popover-content/popover-content.component.html
  packages/ng/popover2/popover.directive.ts
  packages/ng/toast/toasts.component.html
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
  packages/scss/src/components/calloutAccordion/mods.scss
  packages/scss/src/components/calloutDisclosure/mods.scss
  packages/scss/src/components/calloutPopover/mods.scss
  packages/scss/src/components/dialog/component.scss
  packages/scss/src/components/footer/component.scss
  packages/scss/src/components/footer/vars.scss
  packages/scss/src/components/index.scss
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/link/mods.scss
  packages/scss/src/components/multiSelect/component.scss
  packages/scss/src/components/multiSelect/mods.scss
  packages/scss/src/components/plgPush/component.scss
  packages/scss/src/components/popover/component.scss
  packages/scss/src/components/segmentedControl/component.scss
  packages/scss/src/components/segmentedControl/exports.scss
  packages/scss/src/components/segmentedControl/index.scss
  packages/scss/src/components/segmentedControl/mods.scss
  packages/scss/src/components/segmentedControl/states.scss
  packages/scss/src/components/segmentedControl/vars.scss
  packages/scss/src/components/simpleSelect/mods.scss
  packages/scss/src/components/switchField/component.scss
  packages/scss/src/components/tableSortable/index.scss
  packages/scss/src/components/tag/component.scss
  packages/scss/src/components/tag/mods.scss
  packages/scss/src/components/tag/vars.scss
  packages/scss/src/components/textField/mods.scss
  packages/scss/src/components/textfields/mods.scss
  packages/scss/src/components/toast/component.scss
  packages/scss/src/components/userPopover/component.scss
  packages/scss/src/components/viewTabs/component.scss
  packages/scss/src/components/viewTabs/index.scss
  packages/scss/src/components/viewTabs/mods.scss
  packages/scss/src/components/viewTabs/states.scss
  packages/scss/src/components/viewTabs/vars.scss
  stories/documentation/actions/links/link-basic.stories.ts
  stories/documentation/actions/links/link-disabled.stories.ts
  stories/documentation/actions/links/link-hover.stories.ts
  stories/documentation/actions/links/link-nowrap.stories.ts
  stories/documentation/feedback/plg-push/angular/plg-push-basic.stories.ts
  stories/documentation/feedback/plg-push/html&css/plg-push-basic.stories.ts
  stories/documentation/feedback/plg-push/html&css/plg-push-title.stories.ts
  stories/documentation/forms/fields/phone-number-input/angular/phone-number-input.stories.ts
  stories/documentation/listings/index-table/index-table-mass-selection-and-pagination.stories.ts
  stories/documentation/navigation/pagination/pagination-basic.stories.ts
  stories/documentation/navigation/segmentedControl/segmentedControl-filter.stories.ts
  stories/documentation/navigation/segmentedControl/segmentedControl-tabs.stories.ts
  stories/documentation/navigation/viewTabs/viewTabs-basic.stories.ts
  stories/documentation/overlays/tooltip/tooltip-ellipsis.stories.ts
  stories/qa/plg-push/plg-push.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#3079 [Gauge] Radius on bar
  packages/scss/src/components/gauge/component.scss
  stories/documentation/listings/table/table-basic.stories.ts
  stories/documentation/loaders/gauge/gauge-basic.stories.ts
  stories/documentation/structure/cards/cards-basic.stories.ts
  stories/qa/gauge/gauge.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes, :skull: Deprecate

#3083 [Link] Fix color when PLG push is included
  packages/scss/src/components/plgPush/component.scss
Labels: :bookmark::bug: FIX

#3034 Checkbox unchecked mixed
  packages/scss/src/components/checkboxField/index.scss
  stories/qa/forms/checkbox.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3042 [grid] Fix QA + max-width
  packages/scss/src/components/grid/component.scss
  stories/qa/grid/grid.stories.html
  stories/qa/grid/grid.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3058 Fix form field margins
  packages/scss/src/components/form/component.scss
Labels: :bookmark::bug: FIX

#3089 [Select multi] Group search UI
  packages/ng/forms/phone-number-input/phone-number-input.component.html
  packages/ng/forms/phone-number-input/phone-number-input.component.scss
  packages/ng/styles/definitions/option/_option-item.scss
Labels: :bookmark::bug: FIX

#3076 Fix for long formLabel
  packages/scss/src/components/formLabel/component.scss
  packages/scss/src/components/formLabel/mods.scss
  packages/scss/src/components/formLabel/vars.scss
Labels: :bookmark::bug: FIX

#3091 fix(schematics): local deps package.json was excluded by Angular
  build.js
  packages/ng/schematics/action-icon/index.ts
  packages/ng/schematics/empty-state-title/index.ts
  packages/ng/schematics/lib/local-deps/installer.ts
  packages/ng/schematics/new-icons/index.ts
  packages/ng/schematics/palettes/index.ts
  packages/ng/schematics/tokens-spacing/index.ts
Labels: :bookmark::bug: FIX

#3092 [File upload] Fix states contrasts
  packages/scss/src/components/file/states.scss
  stories/documentation/forms/files/files-basic.stories.ts
  stories/documentation/forms/files/files-droppable.stories.ts
  stories/documentation/forms/files/files-error.stories.ts
  stories/documentation/forms/files/files-success.stories.ts
  stories/documentation/forms/files/files-uploading.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3090 [loading] fix margins
  packages/scss/src/components/loading/component.scss
  packages/scss/src/components/loading/mods.scss
  packages/scss/src/components/loading/vars.scss
  stories/documentation/loaders/loadings/loadings-basic.stories.ts
  stories/qa/loadings/loadings.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3084 [Callout] Set callout state input multiple times doesn't work
  packages/ng/callout/callout-disclosure/callout-disclosure.component.html
  packages/ng/callout/callout-disclosure/callout-disclosure.component.ts
  packages/ng/callout/callout-icon.pipe.ts
  packages/ng/callout/callout-popover/callout-popover.component.html
  packages/ng/callout/callout-popover/callout-popover.component.ts
  packages/ng/callout/callout-state.ts
  packages/ng/callout/callout.utils.spec.ts
  packages/ng/callout/callout.utils.ts
  packages/ng/callout/callout/callout.component.html
  packages/ng/callout/callout/callout.component.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3078 [Multiselect / Textfield] UI fixes
  packages/ng/multi-select/displayer/default-displayer.component.scss
  packages/scss/src/components/multiSelect/component.scss
  packages/scss/src/components/multiSelect/index.scss
  packages/scss/src/components/multiSelect/states.scss
  packages/scss/src/components/textField/component.scss
  packages/scss/src/components/textField/states.scss
Labels: :bookmark::bug: FIX

#3082 fix: add date-fns on peer deps
  packages/ng/package.json
Labels: :bookmark::bug: FIX

#3094 [numericBadge] inherit mixin
  packages/scss/src/components/button/component.scss
  packages/scss/src/components/menu/states.scss
  packages/scss/src/components/numericBadge/mods.scss
  packages/scss/src/components/radioButtons/component.scss
  packages/scss/src/components/segmentedControl/states.scss
  stories/documentation/actions/button/html&css/button-counter.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3099 [sortable] multilines
  packages/scss/src/components/tableSortable/component.scss
Labels: :bookmark::bug: FIX

#3097 [Loading] Remove default 100% width
  packages/ng/multi-select/panel/panel.component.html
  packages/ng/simple-select/panel/panel.component.html
  packages/scss/src/components/loading/component.scss
  packages/scss/src/components/loading/mods.scss
  packages/scss/src/components/loading/vars.scss
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3100 [Empty state] Improve documentation options readability
  stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3101 [Doc] Fix QA textfield DOM
  stories/documentation/forms/fields/text/html&css/textfield-info.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3102 [File upload] Update QA story
  stories/qa/forms/files.stories.html
Labels: :bookmark::bug: FIX

#3105 [popover2] documentation for luPopoverTrigger
  docs/popover2.md
Labels: :hammer: Technical, :book: Documentation changes
