Repository LuccaSA/lucca-front, pull requests merged in 2024-05, with the labels that each got.

#2773 feat(button): add `delete` input that adds `mod-delete` to button classes
  packages/ng/button/button.component.ts
Labels: 👥 Front, :bookmark::sparkles: Feature

#2771 Update core-select-users-directive.md
  docs/core-select-users-directive.md
Labels: :bookmark::bug: FIX

#2778 fix(number-input): default placeholder should be '' not `undefined`
  packages/ng/forms/number-input/number-input.component.ts
Labels: :bookmark::bug: FIX

#2746 fix(front): indexTable inconsistent cell padding
  packages/scss/src/components/indexTable/component.scss
Labels: :bookmark::bug: FIX

#2776 fix(form-field): get validators from descendants to handle deep inputs
  packages/ng/form-field/form-field.component.ts
Labels: :bookmark::bug: FIX

#2785 [Core Select] displayMeOption documentation
  docs/core-select-users-directive.md
Labels: :hammer: Technical, :book: Documentation changes

#2782 fix(radio): disabled attribute and autogenerated name
  packages/ng/forms/radio-group-input/radio-group-input.component.ts
  packages/ng/forms/radio-group-input/radio/radio.component.html
  packages/ng/forms/radio-group-input/radio/radio.component.ts
Labels: :hammer: Technical, :bookmark::bug: FIX, :book: Documentation changes

#2786 [Icons] File plus, Arrow corner expand & Arrow center reduce
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2789 feat(user): allow string union type for luUserInput format
  packages/ng/core/type/enum.ts
  packages/ng/core/type/index.ts
  packages/ng/user/display/display-format.model.ts
Labels: 👥 Front, :hammer: Technical

#2788 Add support for the `rows` attribute
  packages/ng/forms/textarea-input/textarea-input.component.html
  packages/ng/forms/textarea-input/textarea-input.component.ts
  packages/scss/src/components/textField/component.scss
  stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
  stories/documentation/forms/fields/textarea/html&css/textareafield.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2791 fix(user): do not depend on setter order in LuUserPictureComponent
  packages/ng/user/picture/user-picture.component.ts
Labels: 👥 Front, :bookmark::bug: FIX

#2795 fix(core-select): handle option value falsy not displaying
  packages/ng/core-select/option/option-outlet.directive.ts
Labels: :bookmark::bug: FIX

#2793 docs(core): fix EnumValue example
  packages/ng/core/type/enum.ts
Labels: :hammer: Technical

#2733 fixed(lu-dialog): handled canClose option in LuDialogService
  packages/ng/dialog/dialog.service.ts
  packages/ng/dialog/model/dialog-config.ts
Labels: :bookmark::bug: FIX

#2790 fix(userDisplay): handle user with empty firstName or lastName
  packages/ng/user/display/user-display.pipe.spec.ts
  packages/ng/user/display/user-display.pipe.ts
Labels: 👥 Front, :bookmark::bug: FIX, :book: Documentation changes

#2794 fix(core-select): wrong naming for if-clue-empty startegy
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/select.model.ts
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2798 [Icon] Food cutlery
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2792 Remove invalid properties
  packages/scss/src/commons/utils/index.scss
Labels: :bookmark::sparkles: Feature

#2777 docs(textfield): clearer set to `false` by default in story
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2799 [Toast] Fix misaligned kill button in Safari iOS
  README.md
  packages/scss/src/components/toast/component.scss
Labels: 👥 UI, :bookmark::bug: FIX

#2802 fix(radio): add missing radio input id suffix
  packages/ng/forms/radio-group-input/radio/radio.component.html
Labels: :hammer: Technical, :bookmark::bug: FIX

#2804 fix(select): strange selection behavior on empty search result
  packages/ng/multi-select/input/panel-ref.factory.ts
  packages/ng/multi-select/panel/panel.component.ts
  packages/ng/simple-select/input/panel-ref.factory.ts
  packages/ng/simple-select/panel/panel.component.ts
Labels: :bookmark::bug: FIX

#2750 refactor(lu-tooltip): simplify code and implement ellipsis system
  packages/ng/styles/_definitions.scss
  packages/ng/styles/definitions/tooltip/_tooltip.scss
  packages/ng/tooltip/panel/tooltip-panel.component.html
  packages/ng/tooltip/panel/tooltip-panel.component.scss
  packages/ng/tooltip/panel/tooltip-panel.component.ts
  packages/ng/tooltip/trigger/tooltip-trigger.directive.spec.ts
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
  packages/scss/src/components/index.scss
  packages/scss/src/components/tooltip/component.scss
  packages/scss/src/components/tooltip/exports.scss
  packages/scss/src/components/tooltip/index.scss
  packages/scss/src/components/tooltip/mods.scss
  packages/scss/src/components/tooltip/states.scss
  packages/scss/src/components/tooltip/vars.scss
  stories/documentation/overlays/tooltip/tooltip-ellipsis.stories.ts
  stories/documentation/overlays/tooltip/tooltip-html.stories.ts
  stories/documentation/overlays/tooltip/tooltip.stories.ts
Labels: 👥 Front, :hammer: Technical, :book: Documentation changes, :triangular_ruler: Angular wrapper

#2775 feat(button): apply default type set to `button` when not present on the button
  packages/ng/button/button.component.ts
  stories/documentation/actions/button/angular/button-basic.stories.ts
Labels: 👥 Front, :hammer: Technical, :book: Documentation changes

#2803 Focus visible for tooltip informations in labels
  packages/ng/form-field/form-field.component.html
  packages/scss/src/components/formLabel/component.scss
  stories/documentation/forms/checkbox/checkbox-basic.stories.ts
  stories/documentation/forms/fields/number/angular/numberfield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/fields/text/html&css/textfield-info.stories.ts
  stories/documentation/forms/fields/textarea/angular/textarea.stories.ts
  stories/documentation/forms/form-label/form-label-basic.stories.ts
  stories/documentation/forms/form-label/form-label-counter.stories.ts
  stories/documentation/forms/form-label/form-label-error.stories.ts
  stories/documentation/forms/form-label/form-label-size.stories.ts
  stories/documentation/forms/switch/switch-basic.stories.ts
  stories/documentation/integration/utilities/help.stories.ts
  stories/qa/form-label/form-label.stories.html
  stories/qa/forms/checkbox.stories.html
  stories/qa/forms/switch.stories.html
  stories/qa/forms/textfield.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2811 Adjustements for comment component
  packages/scss/src/commons/utils/media.scss
  packages/scss/src/components/comment/component.scss
  packages/scss/src/components/comment/exports.scss
  packages/scss/src/components/comment/index.scss
  packages/scss/src/components/comment/mods.scss
  packages/scss/src/components/comment/vars.scss
  packages/scss/src/components/form/mods.scss
  stories/documentation/texts/comment/basic.stories.ts
  stories/documentation/texts/comment/no-avatar.stories.ts
  stories/documentation/texts/comment/richText.stories.ts
  stories/documentation/texts/comment/small.stories.ts
  stories/documentation/texts/comment/wrapper-compact.stories.ts
  stories/documentation/texts/comment/wrapper.stories.ts
  stories/qa/comment/comment.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2813 docs(readme): replace quotes in code blocks
  README.md
Labels: :hammer: Technical, :see_no_evil: No log

#2816 fix(core-select): do not send empty fields / wrong operation parameter name
  packages/ng/core-select/api/api-v3.directive.ts
  packages/ng/core-select/user/users.directive.ts
Labels: :bookmark::bug: FIX

#2810 Remove border for prefix and suffix and add mod-alignRight
  packages/ng/forms/text-input/text-input.component.html
  packages/ng/forms/text-input/text-input.component.ts
  packages/scss/src/components/textField/component.scss
  packages/scss/src/components/textField/index.scss
  packages/scss/src/components/textField/mods.scss
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/fields/text/html&css/textfield-valueAlignRight.stories.ts
  stories/qa/forms/textfield.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2812 User Popover : adjustments + HTML story
  packages/ng/popup-employee/card/panel/user-popover-panel.component.html
  packages/scss/src/components/userPopover/component.scss
  stories/documentation/users/popover/angular/popover.stories.ts
  stories/documentation/users/popover/html&css/popover.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2814 Empty state titles
  packages/ng/empty-state/empty-state-page/empty-state-page.component.html
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/ng/empty-state/empty-state-section/empty-state-section.component.html
  packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
  packages/scss/src/components/emptyState/component.scss
  packages/scss/src/components/emptyState/mods.scss
  stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2626 Component loading refacto
  packages/scss/src/components/dialog/component.scss
  packages/scss/src/components/dialog/mods.scss
  packages/scss/src/components/dialog/vars.scss
  packages/scss/src/components/loading/component.scss
  packages/scss/src/components/loading/index.scss
  packages/scss/src/components/loading/mods.scss
  packages/scss/src/components/loading/vars.scss
  stories/documentation/loaders/loadings/loadings-basic.stories.ts
Labels: :hammer: Technical, :book: Documentation changes, 🦕 Deprecate

#2817 Rc.master.update
  .editorconfig
  .storybook/msw/handlers.ts
  .storybook/msw/helpers.ts
  README.md
  docs/core-select-api-directive.md
  docs/core-select-users-directive.md
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
  packages/ng/core-select/api/api-v3.directive.spec.ts
  packages/ng/core-select/api/api-v3.directive.ts
  packages/ng/core-select/api/api.directive.ts
  packages/ng/core-select/api/public-api.ts
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/option/option-outlet.directive.ts
  packages/ng/core-select/select.model.ts
  packages/ng/core-select/user/user-option.component.ts
  packages/ng/core-select/user/user-option.model.ts
  packages/ng/core-select/user/users.directive.ts
  packages/ng/form-field/form-field.component.ts
  packages/ng/forms/number-input/number-input.component.ts
  packages/ng/forms/radio-group-input/radio-group-input.component.ts
  packages/ng/forms/radio-group-input/radio/radio.component.html
  packages/ng/forms/radio-group-input/radio/radio.component.ts
  packages/ng/forms/text-input/text-input.component.ts
  packages/ng/multi-select/input/panel-ref.factory.ts
  packages/ng/multi-select/panel/panel.component.ts
  packages/ng/option/picker/option-picker.component.ts
  packages/ng/option/picker/tree-option-picker.component.ts
  packages/ng/popover/panel/popover-panel.model.ts
  packages/ng/popover/trigger/popover-trigger.model.ts
  packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
  packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts
  packages/ng/schematics/new-icons/mapping.ts
  packages/ng/simple-select/input/panel-ref.factory.ts
  packages/ng/simple-select/panel/panel.component.ts
  packages/ng/styles/definitions/select/_select-input.scss
  packages/ng/user/display/user-display.pipe.spec.ts
  packages/ng/user/display/user-display.pipe.ts
  packages/ng/user/picture/user-picture.component.ts
  packages/scss/src/commons/config.scss
  packages/scss/src/components/checkbox/component.scss
  packages/scss/src/components/checkbox/states.scss
  packages/scss/src/components/formLabel/component.scss
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/navside/states.scss
  packages/scss/src/components/toast/component.scss
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/select/custom-api-example.component.ts
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
  stories/qa/forms/checkbox-legacy.stories.html
Labels: :hammer: Technical, :book: Documentation changes, :see_no_evil: No log

#2818 fix(tooltip): wrong disable transform
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
Labels: :bookmark::bug: FIX

#2819 [Base] Fix firefox default placeholder opacity
  packages/scss/src/commons/base.scss
Labels: :bookmark::bug: FIX

#2796 [comment] New component
  packages/scss/src/commons/utils/media.scss
  packages/scss/src/components/comment/component.scss
  packages/scss/src/components/comment/exports.scss
  packages/scss/src/components/comment/index.scss
  packages/scss/src/components/comment/mods.scss
  packages/scss/src/components/comment/states.scss
  packages/scss/src/components/comment/vars.scss
  packages/scss/src/components/form/mods.scss
  packages/scss/src/components/index.scss
  stories/documentation/texts/comment/basic.stories.ts
  stories/documentation/texts/comment/no-avatar.stories.ts
  stories/documentation/texts/comment/richText.stories.ts
  stories/documentation/texts/comment/small.stories.ts
  stories/documentation/texts/comment/wrapper-compact.stories.ts
  stories/documentation/texts/comment/wrapper.stories.ts
  stories/qa/comment/comment.stories.html
  stories/qa/comment/comment.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2821 [Base] Remove useless placeholder opacity
  packages/scss/src/components/textfields/component.scss
Labels: :hammer: Technical

#2824 [Table] Reduce shadow intensity
  packages/scss/src/components/tableSticked/mods.scss
  packages/scss/src/components/tableSticked/vars.scss
Labels: :bookmark::bug: FIX

#2774 refactor(empty-states): make title and description optional
  packages/ng/empty-state/empty-state-page/empty-state-page.component.html
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/ng/empty-state/empty-state-section/empty-state-section.component.html
  packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
  packages/scss/src/components/emptyState/component.scss
  stories/documentation/feedback/empty-state/html&css/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section-center.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section-palette.stories.ts
  stories/documentation/feedback/empty-state/html&css/empty-state-section.stories.ts
  stories/documentation/listings/index-table/index-table-empty-state.stories.ts
  stories/qa/empty-state/empty-state-page.stories.html
  stories/qa/empty-state/empty-state-section.stories.html
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#2801 Add an option to change font family
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/vars.scss
Labels: :bookmark::sparkles: Feature

#2825 [User popover] longDate > shortDate
  packages/ng/popup-employee/card/panel/user-popover-panel.component.html
  packages/scss/src/components/userPopover/component.scss
  stories/documentation/users/popover/html&css/popover.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2808 Fix small typo
  stories/documentation/forms/fields/switch/html&css/switchfield-invalid.stories.ts
  stories/qa/forms/checkbox.stories.html
  stories/qa/forms/framed.stories.html
  stories/qa/forms/switch.stories.html
  stories/qa/forms/textfield.stories.html
  stories/qa/grid/grid.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2563 [Form] Full form example & header classes
  packages/scss/src/commons/base.scss
  packages/scss/src/components/form/component.scss
  packages/scss/src/components/form/index.scss
  packages/scss/src/components/form/mods.scss
  packages/scss/src/components/form/vars.scss
  packages/scss/src/components/textfields/component.scss
  stories/documentation/forms/examples/angular/form-basic.stories.ts
  stories/documentation/forms/examples/html&css/form-basic.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2826 feat(date): allow string union type for `lu-date-select`,`lu-date-picker`,`luDateInput` and `lu-calendar`
  packages/ng/core/date/date-adapter.class.ts
  packages/ng/core/date/date-adapter.interface.ts
  packages/ng/core/date/date-granularity.enum.ts
  packages/ng/core/date/native/native-date.adapter.ts
  packages/ng/core/date/string/string-date.adapter.ts
  packages/ng/date/calendar/calendar-input.component.ts
  packages/ng/date/calendar/calendar-item.class.ts
  packages/ng/date/calendar/calendar-item.interface.ts
  packages/ng/date/input/date-input.directive.ts
  packages/ng/date/picker/date-picker.component.ts
  packages/ng/date/select/date-select-input.component.ts
Labels: 👥 Front, :hammer: Technical

#2823 chore(deps): angular18 upgrade
  .storybook/public/mockServiceWorker.js
  package-lock.json
  package.json
  packages/ng/core-select/api/api.directive.ts
  packages/ng/core-select/establishment/establishments.directive.ts
  packages/ng/core-select/panel/panel.utils.ts
  packages/ng/core-select/user/user-displayer.component.ts
  packages/ng/core-select/user/user-option.component.ts
  packages/ng/core/portal/portal.directive.spec.ts
  packages/ng/date/calendar/calendar-item.class.ts
  packages/ng/date/input/date-input.directive.ts
  packages/ng/dialog/model/dialog-ref.ts
  packages/ng/dropdown/trigger/dropdown-trigger.directive.ts
  packages/ng/input/input.directive.ts
  packages/ng/input/input.model.ts
  packages/ng/modal/modal-panel.component.ts
  packages/ng/modal/modal-ref.factory.ts
  packages/ng/multi-select/input/panel-ref.factory.ts
  packages/ng/option/operator/for-groups/for-groups.directive.ts
  packages/ng/option/operator/for-options/for-options.directive.ts
  packages/ng/option/picker/option-picker.component.ts
  packages/ng/popover/trigger/popover-trigger.directive.ts
  packages/ng/popover/trigger/popover-trigger.model.ts
  packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
  packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts
  packages/ng/popup-employee/service/user-popover.store.ts
  packages/ng/popup/popup-ref.factory.ts
  packages/ng/popup/popup-ref.model.ts
  packages/ng/schematics/lib/css-mapper.ts
  packages/ng/schematics/lib/html-ast.ts
  packages/ng/schematics/lib/local-deps/package-lock.json
  packages/ng/schematics/lib/local-deps/package.json
  packages/ng/schematics/lib/scss-value-ast.ts
  packages/ng/simple-select/input/panel-ref.factory.ts
  packages/ng/title/title.service.ts
  packages/ng/title/title.strategy.ts
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
  packages/ng/user/select/homonyms/user-homonyms.service.ts
  setup-jest.ts
  stories/documentation/overlays/modal/modal.stories.ts
  stories/helpers/common-arg-types.ts
Labels: :hammer: Technical, :book: Documentation changes

#2827 [Error page] Title color, font size & apostrophe
  packages/scss/src/components/errorPage/component.scss
  packages/scss/src/components/errorPage/vars.scss
  stories/documentation/feedback/error-page/error-page-basic.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2828 [Breadcrumb] Icon & color
  packages/scss/src/components/breadcrumbs/component.scss
  packages/scss/src/components/breadcrumbs/mods.scss
  packages/scss/src/components/breadcrumbs/states.scss
Labels: :bookmark::sparkles: Feature

#2565 Refacto menu + mod-vertical + scrollBox
  packages/scss/src/components/index.scss
  packages/scss/src/components/menu/component.scss
  packages/scss/src/components/menu/index.scss
  packages/scss/src/components/menu/mods.scss
  packages/scss/src/components/menu/states.scss
  packages/scss/src/components/menu/vars.scss
  packages/scss/src/components/scrollBox/component.scss
  packages/scss/src/components/scrollBox/exports.scss
  packages/scss/src/components/scrollBox/index.scss
  packages/scss/src/components/scrollBox/mods.scss
  packages/scss/src/components/scrollBox/states.scss
  packages/scss/src/components/scrollBox/vars.scss
  stories/documentation/navigation/menu/menu-basic.stories.ts
  stories/documentation/navigation/menu/menu-count.stories.ts
  stories/documentation/navigation/menu/menu-scrollbox.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes
