Repository LuccaSA/lucca-front, pull requests merged in 2024-07, with the labels that each got.

#2908 fix(core-select): remove double URI encoding in API directives
  packages/ng/core-select/establishment/establishments.directive.ts
  packages/ng/core-select/job-qualification/job-qualifications.directive.ts
  packages/ng/core-select/user/users.directive.ts
Labels: :bookmark::bug: FIX

#2910 Remove header and footer roles
  packages/ng/dialog/dialog-footer/dialog-footer.component.ts
  packages/ng/dialog/dialog-header/dialog-header.component.ts
Labels: 👥 Accessibility, :bookmark::bug: FIX

#2906 fix(dialog): close can be disabled specifically for click on backdrop
  packages/ng/dialog/dialog.service.ts
  packages/ng/dialog/model/dialog-config.ts
  stories/documentation/overlays/dialog/dialog-canClose.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2913 fix(option-picker): overlayRef may be null
  packages/ng/option/picker/option-picker.component.ts
Labels: 👥 Front, :hammer: Technical, :bookmark::bug: FIX

#2930 fix(popover2): add overlayref recycling to avoid multiplying bounding boxes
  packages/ng/popover2/popover.directive.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#2900 Font weight for icon generation
  packages/icons/src/commons/utils/icon.scss
Labels: :bookmark::bug: FIX

#2902 Fix contrasts
  packages/scss/src/commons/config.scss
Labels: :bookmark::bug: FIX

#2938 Add shield icons
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2939 Break word for dialog titles
  packages/scss/src/components/dialog/component.scss
Labels: :bookmark::bug: FIX

#2914 Remove clear if select is disabled
  packages/ng/simple-select/input/select-input.component.html
  stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2904 Revert translate for loading position
  packages/scss/src/components/loading/mods.scss
Labels: :bookmark::bug: FIX

#2943 Change default icon color
  packages/scss/src/components/emptyState/component.scss
Labels: :bookmark::bug: FIX

#2942 Add ellipsis for multi displayer
  packages/ng/core-select/option/default-option.component.ts
  packages/scss/src/components/multiSelect/component.scss
  packages/scss/src/components/multiSelect/mods.scss
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2888 feat(time-picker): AM/PM support
  packages/ng/time/core/date.utils.ts
  packages/ng/time/core/time-picker-part.component.html
  packages/ng/time/core/time-picker-part.component.ts
  packages/ng/time/time-picker/time-picker.component.html
  packages/ng/time/time-picker/time-picker.component.ts
  packages/scss/src/components/timepicker/component.scss
  packages/scss/src/components/timepicker/mods.scss
  packages/scss/src/components/timepicker/vars.scss
  stories/documentation/forms/time/time-picker-angular.stories.ts
  stories/documentation/forms/time/time-picker-basic.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#2945 [Colors] Add Core HR colors
  packages/scss/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2952 Fix Angular components host selectors
  packages/ng/new-badge/new-badge.component.scss
  packages/ng/numeric-badge/numeric-badge.component.scss
Labels: :bookmark::bug: FIX

#2949 fix(users): no highlighted item after clue change
  packages/ng/core-select/api/api-v3.directive.ts
  packages/ng/core-select/api/api-v4.directive.ts
  packages/ng/core-select/api/api.directive.ts
  packages/ng/core-select/establishment/establishments.directive.ts
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/job-qualification/job-qualifications.directive.ts
  packages/ng/core-select/user/user-homonym.service.ts
  packages/ng/core-select/user/users.directive.ts
  packages/ng/multi-select/panel/panel.component.html
  packages/ng/multi-select/panel/panel.component.ts
  packages/ng/simple-select/panel/panel.component.html
  packages/ng/simple-select/panel/panel.component.ts
Labels: :bookmark::bug: FIX

#2951 Remove scroll block for popover2
  packages/ng/popover2/popover.directive.ts
Labels: :bookmark::bug: FIX

#2954 Update stories for utilities
  .storybook/styles.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/core.scss
  packages/scss/src/commons/utils/index.scss
  packages/scss/src/commons/utils/reset.scss
  stories/documentation/integration/utilities/borders-radius.stories.ts
  stories/documentation/integration/utilities/borders.stories.ts
  stories/documentation/integration/utilities/comma.stories.ts
  stories/documentation/integration/utilities/content.stories.ts
  stories/documentation/integration/utilities/display.stories.ts
  stories/documentation/integration/utilities/ellipsis.stories.ts
  stories/documentation/integration/utilities/float.stories.ts
  stories/documentation/integration/utilities/help.stories.ts
  stories/documentation/integration/utilities/min-width.stories.html
  stories/documentation/integration/utilities/min-width.stories.ts
  stories/documentation/integration/utilities/position.stories.ts
  stories/documentation/integration/utilities/print.stories.html
  stories/documentation/integration/utilities/print.stories.ts
  stories/documentation/integration/utilities/reset.stories.ts
  stories/documentation/integration/utilities/shadows.stories.ts
  stories/documentation/integration/utilities/sizes.stories.ts
  stories/documentation/integration/utilities/text-color.stories.ts
  stories/documentation/integration/utilities/text-size.stories.ts
  stories/documentation/integration/utilities/text-style.stories.ts
  stories/documentation/integration/utilities/vertical-align.stories.ts
  stories/documentation/integration/utilities/visibility.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#2957 Replace title with heading
  packages/ng/empty-state/empty-state-page/empty-state-page.component.html
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/ng/empty-state/empty-state-section/empty-state-section.component.html
  packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
  stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
  stories/qa/forms/textfield.stories.html
Labels: 💥 Breaking change, :bookmark::bug: FIX, :book: Documentation changes

#2960 [Empty State] Revert heading > title (postponed to 18.2)
  packages/ng/empty-state/empty-state-page/empty-state-page.component.html
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/ng/empty-state/empty-state-section/empty-state-section.component.html
  packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
  stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#2965 Fix missing name radio input
  packages/ng/forms/radio-group-input/radio/radio.component.html
Labels: :bookmark::bug: FIX

#2964 fix(core-select): missing clue filter in users directive under some conditions
  packages/ng/core-select/api/api.directive.spec.ts
  packages/ng/core-select/api/api.directive.ts
  packages/ng/core-select/panel/index.ts
  packages/ng/core-select/panel/key-manager.spec.ts
  packages/ng/core-select/panel/key-manager.ts
  packages/ng/core-select/user/user-homonym.service.ts
  packages/ng/core-select/user/users.directive.spec.ts
  packages/ng/core-select/user/users.directive.ts
  packages/ng/multi-select/input/panel-ref.factory.ts
  packages/ng/multi-select/panel/panel.component.ts
  packages/ng/simple-select/panel/panel.component.ts
Labels: :bookmark::bug: FIX

#2971 fix(date): date adapter format should not be overridden
  packages/ng/date/input/date-input.directive.ts
  packages/ng/date/input/date-input.translate.ts
  packages/ng/date/input/translations.ts
  packages/ng/date/select/date-select-input.component.ts
  packages/ng/date/select/date-select-input.translate.ts
  packages/ng/date/select/translations.ts
Labels: :bookmark::bug: FIX

#2973 chore(ng): update translations
  packages/ng/a11y/skip-links/translations.ts
  packages/ng/callout/translations.ts
  packages/ng/core-select/translations.ts
  packages/ng/core-select/user/translations.ts
  packages/ng/date/input/translations.ts
  packages/ng/date/select/translations.ts
  packages/ng/department/select/input/translations.ts
  packages/ng/dialog/dialog-header/translations.ts
  packages/ng/establishment/select/input/translations.ts
  packages/ng/form-field/translations.ts
  packages/ng/forms/number-format-input/translations.ts
  packages/ng/forms/number-input/translations.ts
  packages/ng/forms/text-input/translations.ts
  packages/ng/modal/translations.ts
  packages/ng/multi-select/displayer/translations.ts
  packages/ng/multi-select/translations.ts
  packages/ng/option/item/translations.ts
  packages/ng/option/placeholder/translations.ts
  packages/ng/option/selector/all/translations.ts
  packages/ng/popover2/translations.ts
  packages/ng/popup-employee/translations.ts
  packages/ng/qualification/select/input/translations.ts
  packages/ng/simple-select/translations.ts
  packages/ng/time/duration-picker/translations.ts
  packages/ng/time/time-picker/translations.ts
  packages/ng/toast/translations.ts
  packages/ng/user/select/input/translations.ts
  packages/ng/user/select/searcher/translations.ts
Labels: :hammer: Technical

#2975 [Icons] Add medical + arrow line
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#2979 Update icons
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/selection.json
Labels: :hammer: Technical

#2980 fix(intl): remove breaking change by accepting legacy type in getIntl
  packages/ng/core/translate/intl.model.ts
Labels: :bookmark::bug: FIX

#2985 [Cards] Improve documentation stories
  stories/documentation/structure/cards/cards-arrow-action.stories.ts
  stories/documentation/structure/cards/cards-basic.stories.ts
  stories/documentation/structure/cards/cards-clickable.stories.ts
  stories/qa/card/card.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2981 [Icons] Add CSSvar to font family
  packages/icons/src/icon/component.scss
  packages/icons/src/icon/index.scss
  packages/icons/src/icon/vars.scss
Labels: :hammer: Technical

#2986 [Status badge] Fix vertical alignement in tables
  packages/scss/src/components/statusBadge/component.scss
Labels: :bookmark::bug: FIX

#2974 Add option luTooltipOnlyForDisplay for tooltips
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
  stories/documentation/overlays/tooltip/tooltip.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2987 [18.1.3] Update RC
  packages/icons/src/icon/component.scss
  packages/icons/src/icon/index.scss
  packages/icons/src/icon/vars.scss
  packages/ng/core/translate/intl.model.ts
  stories/documentation/structure/cards/cards-arrow-action.stories.ts
  stories/documentation/structure/cards/cards-basic.stories.ts
  stories/documentation/structure/cards/cards-clickable.stories.ts
  stories/qa/card/card.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#2895 feat(popover2): hover+focus trigger mode
  packages/ng/popover2/content/popover-content/popover-content.component.ts
  packages/ng/popover2/popover.directive.ts
  packages/ng/popover2/popover2.translate.ts
  stories/documentation/overlays/popover2/popover2.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#2928 columnSticky is deprecated
  packages/scss/src/components/tableStickedDeprecated/mods.scss
  stories/documentation/listings/table-legacy/table-sticky-columns-breakpoints.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes, :skull: Deprecate

#2911 feat(plgPush): add new component and all stories
  packages/ng/plg-push/ng-package.json
  packages/ng/plg-push/plg-push.component.html
  packages/ng/plg-push/plg-push.component.scss
  packages/ng/plg-push/plg-push.component.ts
  packages/ng/plg-push/public-api.ts
  packages/scss/src/components/index.scss
  packages/scss/src/components/link/mods.scss
  packages/scss/src/components/plgPush/component.scss
  packages/scss/src/components/plgPush/exports.scss
  packages/scss/src/components/plgPush/index.scss
  packages/scss/src/components/plgPush/vars.scss
  stories/documentation/feedback/plg-push/angular/plg-push-basic.stories.ts
  stories/documentation/feedback/plg-push/html&css/plg-push-basic.stories.ts
  stories/documentation/feedback/plg-push/html&css/plg-push-title.stories.ts
  stories/qa/plg-push/plg-push.stories.html
  stories/qa/plg-push/plg-push.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#2933 Fix footer on dialogs with Safari
  packages/scss/src/components/dialog/component.scss
Labels: :bookmark::bug: FIX

#2993 no wrap
  packages/scss/src/components/numericBadge/component.scss
Labels: :bookmark::bug: FIX

#2958 Remove tooltip generated by Safari desktop
  packages/scss/src/components/tooltip/component.scss
Labels: :bookmark::bug: FIX

#2838 Show index table link
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/indexTable/states.scss
  stories/documentation/listings/index-table/index-table-actions-touch-detection.stories.ts
  stories/documentation/listings/index-table/index-table-actions.stories.ts
  stories/documentation/listings/index-table/index-table-basic.stories.ts
  stories/documentation/listings/index-table/index-table-footer.stories.ts
  stories/documentation/listings/index-table/index-table-interactive-nested-selectable.stories.html
  stories/documentation/listings/index-table/index-table-layout-fixed-responsive.stories.ts
  stories/documentation/listings/index-table/index-table-layout-fixed.stories.ts
  stories/documentation/listings/index-table/index-table-mass-selection-and-pagination.stories.ts
  stories/documentation/listings/index-table/index-table-nested-selectable.stories.ts
  stories/documentation/listings/index-table/index-table-nested-sub-totals.stories.ts
  stories/documentation/listings/index-table/index-table-nested.stories.ts
  stories/documentation/listings/index-table/index-table-responsive-card-list-custom.stories.ts
  stories/documentation/listings/index-table/index-table-responsive-card-list-label.stories.ts
  stories/documentation/listings/index-table/index-table-responsive-card-list-nested.stories.ts
  stories/documentation/listings/index-table/index-table-responsive-card-list.stories.ts
  stories/documentation/listings/index-table/index-table-selectable.stories.ts
  stories/documentation/listings/index-table/index-table-sorted.stories.ts
  stories/documentation/listings/index-table/index-table-stackable.stories.ts
  stories/documentation/listings/index-table/index-table-sticky-header.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes, :skull: Deprecate

#2967 Add grid display into utilities
  packages/scss/src/commons/core.scss
  stories/documentation/integration/utilities/display.stories.ts
  stories/documentation/integration/utilities/print.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#2966 Change disabled colors
  packages/ng/core-select/option/option.component.scss
  packages/ng/date/calendar/calendar-input.component.scss
  packages/ng/option/item/option-item.component.scss
  packages/ng/option/item/tree-option-item.component.scss
  packages/ng/styles/components/_dropdown.scss
  packages/ng/styles/definitions/option/_option-item.scss
  packages/ng/styles/definitions/select/_select-input.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/components/actionIcon/states.scss
  packages/scss/src/components/button/component.scss
  packages/scss/src/components/button/mods.scss
  packages/scss/src/components/button/states.scss
  packages/scss/src/components/buttonGroup/mods.scss
  packages/scss/src/components/checkbox/states.scss
  packages/scss/src/components/checkboxField/states.scss
  packages/scss/src/components/chip/states.scss
  packages/scss/src/components/clear/states.scss
  packages/scss/src/components/field/mods.scss
  packages/scss/src/components/field/states.scss
  packages/scss/src/components/file/states.scss
  packages/scss/src/components/formLabel/states.scss
  packages/scss/src/components/inlineMessage/states.scss
  packages/scss/src/components/link/states.scss
  packages/scss/src/components/menu/states.scss
  packages/scss/src/components/multiSelect/states.scss
  packages/scss/src/components/numericBadge/states.scss
  packages/scss/src/components/radio/states.scss
  packages/scss/src/components/radioButtons/states.scss
  packages/scss/src/components/radioField/states.scss
  packages/scss/src/components/simpleSelect/states.scss
  packages/scss/src/components/switch/states.scss
  packages/scss/src/components/switchField/states.scss
  packages/scss/src/components/tableOfContent/states.scss
  packages/scss/src/components/textField/states.scss
  packages/scss/src/components/textfields/mods.scss
  packages/scss/src/components/textfields/states.scss
  packages/scss/src/components/textfields/vars.scss
  packages/scss/src/components/timepicker/component.scss
  packages/scss/src/components/timepicker/states.scss
  packages/scss/src/components/timepickerDeprecated/states.scss
  packages/scss/src/components/verticalNavigation/states.scss
Labels: :bookmark::sparkles: Feature

#2922 docs(radio-input): add base usage docs
  docs/radio-input.md
Labels: :hammer: Technical, :book: Documentation changes
