Repository LuccaSA/lucca-front, pull requests merged in 2024-12, with the labels that each got.

#3247 fix(users-select): remove extra encoding
  packages/ng/core-select/api/api-v4.directive.ts
  packages/ng/core-select/establishment/establishments.directive.ts
  packages/ng/core-select/job-qualification/job-qualifications.directive.ts
  packages/ng/core-select/select.utils.ts
  packages/ng/core-select/user/users.directive.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#3238 feat(fancy box): add component
  packages/scss/src/components/fancyBox/component.scss
  packages/scss/src/components/fancyBox/exports.scss
  packages/scss/src/components/fancyBox/index.scss
  packages/scss/src/components/fancyBox/mods.scss
  packages/scss/src/components/fancyBox/states.scss
  packages/scss/src/components/fancyBox/vars.scss
  packages/scss/src/components/index.scss
  stories/qa/fancy-box/fancy-box.stories.html
  stories/qa/fancy-box/fancy-box.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3256 fix(dialog-header): _addAriaLabelledBy call is now null-safe
  packages/ng/dialog/dialog-header/dialog-header.component.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#3255 [Table] Card + actions padding
  packages/scss/src/components/table/mods.scss
  stories/qa/table/table.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3237 [Index table] Fix css triggered by lint
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/indexTable/mods.scss
Labels: :bookmark::bug: FIX

#3261 [Sidepanel] Fix content height in legacy sidepanels
  packages/ng/styles/components/_popup.scss
  packages/ng/styles/components/_sidepanel.scss
  stories/documentation/navigation/sidepanel/sidepanel.stories.ts
  stories/documentation/overlays/modal/modal.stories.ts
  stories/documentation/overlays/sidepanel/sidepanel.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3257 [Textfield] Fix wrapping prefix
  packages/scss/src/components/textField/component.scss
Labels: :bookmark::bug: FIX

#3245 [Empty state] Actions padding & alignment
  packages/scss/src/components/emptyState/component.scss
  stories/documentation/feedback/empty-state/angular/empty-state-page.stories.ts
  stories/documentation/feedback/empty-state/angular/empty-state-section.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3242 [Navside] Fix loading colors
  packages/scss/src/components/navside/component.scss
Labels: :bookmark::bug: FIX

#3254 Apply focus style by default on buttons
  packages/scss/src/commons/base.scss
  stories/qa/menu/menu.stories.html
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3260 feat(select): add required validator for multiselection control
  packages/ng/multi-select/public-api.ts
  packages/ng/multi-select/select.validators.ts
Labels: 👥 Front, :bookmark::sparkles: Feature

#3263 [indexTable] adjust paddings
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/indexTable/mods.scss
  packages/scss/src/components/indexTable/vars.scss
Labels: :bookmark::bug: FIX

#3265 [Focus] Reset default focus style on buttons
  packages/scss/src/commons/base.scss
Labels: :bookmark::bug: FIX

#3240 fix(panel): fix searchable when using luOptionGroup on lu-simple-select or lu-multi-select
  packages/ng/core-select/panel/panel.utils.ts
  packages/ng/multi-select/panel/panel.component.ts
  packages/ng/simple-select/panel/panel.component.ts
  stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3250 fix(date-input): validators logic fixes
  packages/ng/date2/date-input/date-input.component.html
  packages/ng/date2/date-input/date-input.component.ts
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#3230 refactor(select): do not override overlay container
  packages/ng/core-select/input/select-input.models.ts
  packages/ng/multi-select/input/panel-ref.factory.ts
  packages/ng/multi-select/input/select-input.component.ts
  packages/ng/simple-select/input/panel-ref.factory.ts
  packages/ng/simple-select/input/select-input.component.ts
Labels: :hammer: Technical, :book: Documentation changes

#3266 [utils] reset list
  packages/scss/src/commons/utils/reset.scss
  stories/documentation/integration/utilities/reset.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3259 [skeletonIndexTable] [skeletonTable] components
  packages/ng/skeleton/public-api.ts
  packages/ng/skeleton/skeleton-index-table/skeleton-index-table.component.html
  packages/ng/skeleton/skeleton-index-table/skeleton-index-table.component.scss
  packages/ng/skeleton/skeleton-index-table/skeleton-index-table.component.ts
  packages/ng/skeleton/skeleton-table/skeleton-table.component.html
  packages/ng/skeleton/skeleton-table/skeleton-table.component.scss
  packages/ng/skeleton/skeleton-table/skeleton-table.component.ts
  stories/documentation/loaders/skeleton-index-table/angular/skeleton-index-table-body.stories.ts
  stories/documentation/loaders/skeleton-index-table/angular/skeleton-index-table.stories.ts
  stories/documentation/loaders/skeleton-table/angular/skeleton-table-body.stories.ts
  stories/documentation/loaders/skeleton-table/angular/skeleton-table.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3252 Font face cursive (for caveat)
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/core.scss
  packages/scss/src/commons/utils/index.scss
  packages/scss/src/commons/vars.scss
  stories/documentation/texts/text/text.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3249 [sample] stories
  stories/documentation/_sample/angular/basic.stories.ts
  stories/documentation/_sample/html&css/basic.stories.ts
  stories/qa/_sample/sample.stories.html
  stories/qa/_sample/sample.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3209 [divider] angular wrapper + mod-vertical
  packages/ng/divider/divider.component.scss
  packages/ng/divider/divider.component.ts
  packages/ng/divider/ng-package.json
  packages/ng/divider/public-api.ts
  packages/scss/src/components/divider/component.scss
  packages/scss/src/components/divider/index.scss
  packages/scss/src/components/divider/mods.scss
  packages/scss/src/components/divider/vars.scss
  stories/documentation/structure/divider/angular/divider-basic.stories.ts
  stories/documentation/structure/divider/divider-basic.stories.ts
  stories/documentation/structure/divider/html&css/divider-basic.stories.ts
  stories/qa/divider/divider.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes, :triangular_ruler: Angular wrapper

#3268 [utils] color palette
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/utils/color.scss
Labels: :bookmark::sparkles: Feature

#3258 [fancyBox] angular wrapper
  packages/ng/fancy-box/fancy-box.component.html
  packages/ng/fancy-box/fancy-box.component.scss
  packages/ng/fancy-box/fancy-box.component.ts
  packages/ng/fancy-box/ng-package.json
  packages/ng/fancy-box/public-api.ts
  packages/scss/src/components/fancyBox/component.scss
  packages/scss/src/components/fancyBox/index.scss
  packages/scss/src/components/fancyBox/mods.scss
  packages/scss/src/components/fancyBox/vars.scss
  stories/documentation/structure/fancy-box/angular/fancy-box-basic.stories.ts
  stories/documentation/structure/fancy-box/html&css/fancy-box-basic.stories.ts
  stories/qa/fancy-box/fancy-box.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes, :triangular_ruler: Angular wrapper

#3134 [numericBadge] loading
  packages/ng/numeric-badge/numeric-badge.component.ts
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/utils/loading.scss
  packages/scss/src/components/numericBadge/component.scss
  packages/scss/src/components/numericBadge/index.scss
  packages/scss/src/components/numericBadge/states.scss
  packages/scss/src/components/numericBadge/vars.scss
  stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
  stories/documentation/texts/numeric-badge/html&css/numeric-badge-basic.stories.ts
  stories/qa/numeric-badge/numeric-badge.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3267 [dropdown] divider
  packages/ng/styles/components/_dropdown.scss
  stories/documentation/overlays/dropdown/dropdown-basic.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3270 [Dialog] Size as select control & show mod-neutralBackground version
  stories/documentation/overlays/dialog/dialog-basic.stories.ts
  stories/documentation/overlays/dialog/dialog.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3269 fix(tooltip): missing tabindex when using without ellipsis logic
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#3272 [fontFace] use mixin for Source Sans 3
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
Labels: :hammer: Technical

#3251 fix(number-input): fix tentative for min & max validators
  packages/ng/forms/number-input/number-input.component.html
  packages/ng/forms/number-input/number-input.component.ts
  stories/documentation/forms/fields/number/angular/numberfield.stories.ts
Labels: :hammer: Technical, :bookmark::bug: FIX, :book: Documentation changes

#3276 [Toast] Content as paragraph
  packages/ng/toast/toasts.component.html
  packages/scss/src/components/toast/component.scss
Labels: 👥 Accessibility, :bookmark::bug: FIX

#3277 fix(user-popover): remove useless alt and add alts on icons
  packages/ng/popup-employee/card/panel/user-popover-panel.component.html
  packages/ng/popup-employee/card/panel/user-popover-panel.component.ts
  packages/ng/popup-employee/popup-employee.translate.ts
  packages/ng/popup-employee/translations.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#3280 Remove circular dependency
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/utils/color.scss
  packages/scss/src/components/callout/component.scss
  packages/scss/src/components/calloutFeedbackList/component.scss
Labels: :bookmark::sparkles: Feature, :hammer: Technical

#3285 [Textfield] Wrong token for placeholder / error
  packages/scss/src/components/textField/states.scss
Labels: :bookmark::bug: FIX

#3288 [fieldset] expandable - change icon
  packages/scss/src/components/fieldset/component.scss
  packages/scss/src/components/fieldset/index.scss
  packages/scss/src/components/fieldset/states.scss
  packages/scss/src/components/fieldset/vars.scss
  stories/documentation/forms/fieldset/fieldset-basic.stories.ts
  stories/qa/fieldset/fieldset.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3290 [divider] css var [utils] reset list
  packages/scss/src/commons/utils/reset.scss
  packages/scss/src/components/divider/component.scss
  packages/scss/src/components/divider/vars.scss
Labels: :bookmark::sparkles: Feature

#3297 fix(ng): fix the fixing fix
  packages/ng/core-select/input/select-input.component.ts
Labels: :bookmark::bug: FIX

#3291 [navside] Add support for ESR
  packages/scss/src/components/navside/mods.scss
Labels: :bookmark::sparkles: Feature

#3299 [18.3][navside] Add support for ESR
  packages/scss/src/components/navside/mods.scss
Labels: :bookmark::bug: FIX

#3300 [19.1] Stories
  packages/ng/skeleton/skeleton-data-table/skeleton-data-table.component.html
  packages/ng/skeleton/skeleton-index-table/skeleton-index-table.component.html
  packages/ng/skeleton/skeleton-table/skeleton-table.component.html
  stories/documentation/actions/links/angular.stories.ts
  stories/documentation/listings/data-table/html&css/alignement-horizontal.stories.ts
  stories/documentation/listings/data-table/html&css/alignement-vertical.stories.ts
  stories/documentation/listings/data-table/html&css/basic.stories.ts
  stories/documentation/listings/data-table/html&css/cell-border.stories.ts
  stories/documentation/listings/data-table/html&css/draggable.stories.ts
  stories/documentation/listings/data-table/html&css/editable.stories.ts
  stories/documentation/listings/data-table/html&css/filter.stories.ts
  stories/documentation/listings/data-table/html&css/fixed-columns-responsive.stories.ts
  stories/documentation/listings/data-table/html&css/fixed-columns.stories.ts
  stories/documentation/listings/data-table/html&css/group.stories.ts
  stories/documentation/listings/data-table/html&css/overflow-both.stories.ts
  stories/documentation/listings/data-table/html&css/overflow-horizontal.stories.ts
  stories/documentation/listings/data-table/html&css/overflow-vertical.stories.ts
  stories/documentation/listings/data-table/html&css/quick-actions.stories.ts
  stories/documentation/listings/data-table/html&css/selectable.stories.ts
  stories/documentation/listings/data-table/html&css/sticky-columns-multiple.stories.ts
  stories/documentation/listings/data-table/html&css/sticky-columns.stories.ts
  stories/documentation/listings/data-table/html&css/sticky-header-columns.stories.ts
  stories/documentation/listings/data-table/html&css/sticky-header.stories.ts
  stories/documentation/listings/data-table/html&css/tree.stories.ts
  stories/documentation/loaders/skeleton-data-table/angular/skeleton-data-table-body.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3301 [19.1] Format stories
  packages/ng/skeleton/skeleton-data-table/skeleton-data-table.component.ts
  packages/ng/skeleton/skeleton-index-table/skeleton-index-table.component.ts
  packages/ng/skeleton/skeleton-table/skeleton-table.component.ts
  stories/documentation/actions/links/angular.stories.ts
  stories/documentation/actions/links/link-basic.stories.ts
  stories/documentation/actions/links/link-disabled.stories.ts
  stories/documentation/actions/links/link-hover.stories.ts
  stories/documentation/actions/links/link-nowrap.stories.ts
  stories/documentation/integration/utilities/reset.stories.ts
  stories/documentation/loaders/skeleton-data-table/angular/skeleton-data-table.stories.ts
  stories/documentation/loaders/skeleton-index-table/angular/skeleton-index-table.stories.ts
  stories/documentation/loaders/skeleton-table/angular/skeleton-table.stories.ts
  stories/documentation/structure/divider/angular/divider-basic.stories.ts
  stories/documentation/structure/divider/html&css/divider-basic.stories.ts
  stories/documentation/structure/fancy-box/angular/fancy-box-basic.stories.ts
  stories/documentation/structure/fancy-box/html&css/fancy-box-basic.stories.ts
  stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
  stories/documentation/texts/numeric-badge/html&css/numeric-badge-basic.stories.ts
  stories/documentation/texts/numeric-badge/html&css/numeric-badge-loading.stories.ts
  stories/documentation/texts/numeric-badge/html&css/numeric-badge-palette.stories.ts
  stories/documentation/texts/numeric-badge/html&css/numeric-badge-size.stories.ts
  stories/documentation/texts/status-badge/html&css/status-badge-basic.stories.ts
  stories/documentation/texts/status-badge/html&css/status-badge-palettes.stories.ts
  stories/documentation/texts/status-badge/html&css/status-badge-size.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3303 [19.1] Format stories (2)
  stories/documentation/integration/utilities/reset.stories.ts
  stories/documentation/structure/divider/angular/divider-basic.stories.ts
  stories/documentation/structure/divider/html&css/divider-basic.stories.ts
  stories/documentation/structure/fancy-box/html&css/fancy-box-basic.stories.ts
  stories/documentation/texts/numeric-badge/html&css/numeric-badge-size.stories.ts
  stories/documentation/texts/status-badge/html&css/status-badge-palettes.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3307 [caveat] disabled by default
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/vars.scss
Labels: :bookmark::bug: FIX

#3302 [19.1] Removed elements
  README.md
  packages/ng/multi-select/panel/panel.component.html
  packages/ng/simple-select/panel/panel.component.html
  packages/scss/src/commons/config.scss
  packages/scss/src/commons/core.scss
  packages/scss/src/commons/utils/index.scss
  packages/scss/src/commons/vars.scss
  packages/scss/src/components/actionIcon/component.scss
  packages/scss/src/components/actionIcon/exports.scss
  packages/scss/src/components/actionIcon/index.scss
  packages/scss/src/components/actionIcon/mods.scss
  packages/scss/src/components/actionIcon/states.scss
  packages/scss/src/components/actionIcon/vars.scss
  packages/scss/src/components/button/index.scss
  packages/scss/src/components/card/mods.scss
  packages/scss/src/components/emptyStateDeprecated/component.scss
  packages/scss/src/components/emptyStateDeprecated/exports.scss
  packages/scss/src/components/emptyStateDeprecated/index.scss
  packages/scss/src/components/emptyStateDeprecated/mods.scss
  packages/scss/src/components/emptyStateDeprecated/states.scss
  packages/scss/src/components/emptyStateDeprecated/vars.scss
  packages/scss/src/components/gridLegacy/component.scss
  packages/scss/src/components/gridLegacy/exports.scss
  packages/scss/src/components/gridLegacy/index.scss
  packages/scss/src/components/gridLegacy/mods.scss
  packages/scss/src/components/gridLegacy/states.scss
  packages/scss/src/components/gridLegacy/vars.scss
  packages/scss/src/components/index.scss
  packages/scss/src/components/list/mods.scss
  stories/documentation/actions/action-icon/action-icon-basic.stories.ts
  stories/documentation/integration/utilities/comma.stories.ts
  stories/documentation/integration/utilities/units.stories.ts
  stories/documentation/listings/list/list-basic.stories.ts
  stories/documentation/structure/empty-state-deprecated/empty-state-basic.stories.ts
  stories/documentation/structure/grids-legacy/grids-auto-width.stories.ts
  stories/documentation/structure/grids-legacy/grids-basic.stories.ts
  stories/documentation/structure/grids-legacy/grids-horizontal-alignment.stories.ts
  stories/documentation/structure/grids-legacy/grids-justify.stories.ts
  stories/documentation/structure/grids-legacy/grids-offset.stories.ts
  stories/documentation/structure/grids-legacy/grids-sort.stories.ts
  stories/documentation/structure/grids-legacy/grids-vertical-alignment.stories.ts
  stories/documentation/users/display/display.stories.html
  stories/documentation/users/popover/html&css/popover.stories.ts
  stories/qa/button/button.stories.html
  stories/qa/empty-state-deprecated/empty-state-deprecated.stories.html
  stories/qa/empty-state-deprecated/empty-state-deprecated.stories.ts
  stories/qa/list/list.stories.html
  stories/qa/table/table.stories.html
  stories/qa/tokens/tokens.stories.html
Labels: 💥 Breaking change, :hammer: Technical, :book: Documentation changes

#3308 [Date] Clean story's controls
  stories/documentation/forms/date2/date-input.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3309 MD format
  docs/dialog.md
  docs/user-popover.md
Labels: :hammer: Technical, :book: Documentation changes

#3315 Format markdown files for ZH integration
  docs/core-select-api-directive.md
  docs/core-select-users-directive.md
  docs/date-input.md
  docs/multi-select-all.md
  docs/popover2.md
  docs/radio-input.md
  docs/user-popover.md
Labels: :hammer: Technical, :book: Documentation changes

#3316 MD format
  docs/core-select-api-directive.md
  docs/core-select-users-directive.md
  docs/multi-select-all.md
  docs/user-popover.md
Labels: :hammer: Technical, :book: Documentation changes

#3329 [multilanguage] fix gap
  packages/ng/forms/multilanguage-input/multilanguage-input.component.html
Labels: :bookmark::bug: FIX

#3293 [dialog] close + popover
  packages/ng/dialog/dialog-header/dialog-header.component.html
Labels: :bookmark::sparkles: Feature
