Repository LuccaSA/lucca-front, pull requests merged in 2025-04, with the labels that each got.

#3543 [icons] pen star
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::bug: FIX

#3545 [19.2.5] Master 2 rc
  package.json
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
  packages/ng/core-select/user/users.directive.ts
  packages/ng/date2/abstract-date-component.ts
  packages/ng/date2/date-input/date-input.component.ts
  packages/ng/date2/date-range-input/date-range-input.component.ts
  packages/ng/dialog/dialog-header/dialog-header.component.scss
  packages/ng/empty-state/empty-state-page/empty-state-page.component.ts
  packages/ng/empty-state/empty-state-section/empty-state-section.component.ts
  packages/ng/empty-state/empty-state.model.ts
  packages/ng/multi-select/panel/panel.component.html
  packages/ng/simple-select/input/select-input.component.ts
  packages/ng/styles/definitions/select/_select-input.scss
  packages/ng/tag/tag.component.html
  packages/scss/src/components/dataTable/component.scss
  packages/scss/src/components/indexTable/component.scss
  packages/scss/src/components/tag/vars.scss
  stories/documentation/forms/date2/date-input.stories.ts
  stories/documentation/forms/date2/date-range-input.stories.ts
  stories/documentation/overlays/dropdown/dropdown-basic.stories.ts
  stories/qa/data-table/data-table.stories.html
  stories/qa/data-table/data-table.stories.ts
  stories/qa/index-table/index-table.stories.html
  stories/qa/index-table/index-table.stories.ts
Labels: :bookmark::sparkles: Feature, :bookmark::bug: FIX, :book: Documentation changes

#3548 [highlightData] illustration source
  packages/ng/highlight-data/highlight-data.component.ts
Labels: :bookmark::sparkles: Feature

#3547 [footer] buttons with wrap
  packages/scss/src/components/footer/component.scss
Labels: :bookmark::sparkles: Feature

#3546 [button] disclosure input
  packages/ng/button/button.component.ts
Labels: :bookmark::sparkles: Feature

#3528 [link] contrasted hover
  packages/scss/src/commons/config.scss
  packages/scss/src/components/button/component.scss
  packages/scss/src/components/callout/component.scss
  packages/scss/src/components/calloutAccordion/component.scss
  packages/scss/src/components/calloutDisclosure/component.scss
  packages/scss/src/components/highlightData/component.scss
  packages/scss/src/components/link/mods.scss
  stories/qa/button/button.stories.html
Labels: 👥 Accessibility, :bookmark::sparkles: Feature, :book: Documentation changes

#3530 [icon] display alignment
  packages/ng/callout/callout-disclosure/callout-disclosure.component.html
  packages/ng/callout/callout-popover/callout-popover.component.html
  packages/ng/date2/date-input/date-input.component.html
  packages/ng/dialog/dialog-header/dialog-header.component.html
  packages/ng/filter-pills/filter-bar/filter-bar.component.html
  packages/ng/filter-pills/filter-pill/filter-pill.component.html
  packages/ng/form-field/form-field.component.html
  packages/ng/icon/icon.component.scss
  packages/ng/plg-push/plg-push.component.html
  packages/ng/popover2/content/popover-content/popover-content.component.html
  packages/ng/popup-employee/card/panel/user-popover-panel.component.html
  packages/ng/tag/tag.component.html
  stories/documentation/actions/button/angular/button-icon.stories.ts
  stories/documentation/feedback/plg-push/angular/plg-push-basic.stories.ts
  stories/documentation/forms/filterPills/html&css/filter-bar.stories.ts
  stories/documentation/overlays/tooltip/tooltip.stories.ts
  stories/documentation/texts/icons/icon-basic.stories.ts
  stories/qa/button/button.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3536 fix(front) : fix - no forced layoutFixed for responsive
  packages/scss/src/components/indexTable/mods.scss
Labels: :bookmark::bug: FIX

#3549 feat(form-field): add extra describedBy input
  packages/ng/form-field/form-field.component.ts
  stories/documentation/forms/fields/form-field.stories.ts
  stories/qa/index-table/index-table.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3514 [DateInputComponent] fix: the min/max in month mode
  packages/ng/date2/abstract-date-component.ts
  packages/ng/date2/date-input/date-input.component.ts
Labels: 👥 Front, :bookmark::bug: FIX

#3527 [multilanguage] inherit size
  packages/ng/forms/multilanguage-input/multilanguage-input.component.html
  packages/ng/forms/multilanguage-input/multilanguage-input.component.ts
Labels: :bookmark::bug: FIX

#3556 [Multi select] Search icon size with S size
  packages/scss/src/components/multiSelect/mods.scss
Labels: :bookmark::bug: FIX

#3535 fix(front) : [indexTable] reduce specificity of actions buttons to allow override from mods, like mod-delete
  packages/scss/src/components/indexTable/index.scss
  packages/scss/src/components/indexTable/mods.scss
  stories/documentation/listings/index-table/index-table-actions.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3555 [fancyBox] fix position + story
  packages/scss/src/components/fancyBox/component.scss
  stories/documentation/structure/fancy-box/angular/fancy-box-basic.stories.ts
  stories/documentation/structure/fancy-box/html&css/fancy-box-basic.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3501 Fix(filter pills): clearable
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/date2/abstract-date-component.ts
  packages/ng/date2/date-input/date-input.component.ts
  packages/ng/date2/date-range-input/date-range-input.component.html
  packages/ng/date2/date-range-input/date-range-input.component.ts
  packages/ng/filter-pills/core/filter-pill-input-component.ts
  packages/ng/filter-pills/filter-pill/filter-pill.component.html
  packages/ng/filter-pills/filter-pill/filter-pill.component.ts
  packages/ng/forms/checkbox-input/checkbox-input.component.ts
  packages/ng/multi-select/input/select-input.component.html
  packages/ng/simple-select/input/select-input.component.html
  stories/documentation/forms/filterPills/angular/date-filter-pill.stories.ts
  stories/documentation/forms/filterPills/angular/filter-pills.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes, 🎨 Design sync

#3558 [19.2.6] Update RC
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/date2/abstract-date-component.ts
  packages/ng/date2/date-input/date-input.component.html
  packages/ng/date2/date-input/date-input.component.ts
  packages/ng/date2/date-range-input/date-range-input.component.html
  packages/ng/date2/date-range-input/date-range-input.component.ts
  packages/ng/filter-pills/core/filter-pill-input-component.ts
  packages/ng/filter-pills/filter-pill/filter-pill.component.html
  packages/ng/filter-pills/filter-pill/filter-pill.component.ts
  packages/ng/form-field/form-field.component.ts
  packages/ng/forms/checkbox-input/checkbox-input.component.ts
  packages/ng/forms/multilanguage-input/multilanguage-input.component.html
  packages/ng/forms/multilanguage-input/multilanguage-input.component.ts
  packages/ng/multi-select/input/select-input.component.html
  packages/ng/schematics/.eslintrc
  packages/ng/schematics/lib/angular-component-ast.ts
  packages/ng/schematics/lu-select/migration.ts
  packages/ng/schematics/lu-select/tests/input/api-selects.component.ts
  packages/ng/schematics/lu-select/tests/input/simple-case.component.ts
  packages/ng/schematics/lu-select/tests/output/api-selects.component.ts
  packages/ng/schematics/lu-select/tests/output/rejected.component.ts
  packages/ng/schematics/lu-select/tests/output/simple-case.component.ts
  packages/ng/schematics/lu-select/util.ts
  packages/ng/simple-select/input/select-input.component.html
  packages/scss/src/components/fancyBox/component.scss
  packages/scss/src/components/multiSelect/mods.scss
  stories/documentation/forms/fields/form-field.stories.ts
  stories/documentation/forms/filterPills/angular/date-filter-pill.stories.ts
  stories/documentation/forms/filterPills/angular/filter-pills.stories.ts
  stories/documentation/structure/fancy-box/angular/fancy-box-basic.stories.ts
  stories/documentation/structure/fancy-box/html&css/fancy-box-basic.stories.ts
  stories/qa/index-table/index-table.stories.ts
Labels: :bookmark::sparkles: Feature, :bookmark::bug: FIX

#3559 fix(lu-textarea-input): apply autoresize with initial value
  packages/ng/forms/textarea-input/textarea-input.component.ts
Labels: :bookmark::bug: FIX

#3560 [Dropdown] Fix description typo
  stories/documentation/overlays/dropdown/dropdown-component.stories.ts
Labels: :bookmark::bug: FIX

#3561 fix(lint): force ignore unused vars in schematic test cases
  package-lock.json
  packages/ng/schematics/lu-select/tests/input/simple-case.component.ts
  packages/ng/schematics/lu-select/tests/output/simple-case.component.ts
  packages/scss/src/components/indexTable/mods.scss
  stories/documentation/forms/fileToolbar/html&css/basic.stories.ts
  stories/documentation/forms/fileUpload/angular/basic.stories.ts
Labels: :hammer: Technical, :bookmark::bug: FIX, :book: Documentation changes

#3563 [icons] accessibility
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::bug: FIX

#3564 ref(title): better DX
  packages/ng/title/README.md
  packages/ng/title/title-translate.service.ts
  packages/ng/title/title.strategy.spec.ts
  packages/ng/title/title.strategy.ts
Labels: 💥 Breaking change, :hammer: Technical

#3568 fix(user-display): handle nullish values for user display tooling
  packages/ng/user/display/user-display.pipe.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#3570 [Navside] Remove New Badge automatic invert
  packages/scss/src/components/navside/states.scss
Labels: :bookmark::bug: FIX

#3569 [19.3] Format stories
  docs/rich-text-input.md
  packages/ng/button/button.component.ts
  stories/documentation/actions/button/angular/button-basic.stories.ts
  stories/documentation/actions/button/angular/button-icon.stories.ts
  stories/documentation/actions/button/html&css/button-disclosure.stories.ts
  stories/documentation/forms/fileUpload/angular/basic.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
  stories/documentation/navigation/breadcrumbs/angular/breadcrumbs-basic.stories.ts
  stories/documentation/navigation/horizontalNavigation/angular/horizontalNavigation-basic.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-basic.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-container.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-count.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-scrollbox.stories.ts
  stories/documentation/structure/footer/angular/footer-basic.stories.ts
  stories/documentation/structure/footer/html&css/footer-basic.stories.ts
  stories/documentation/structure/highlight-data/angular/basic.stories.ts
  stories/documentation/texts/read-more/angular/read-more.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3573 [fileUpload] remove lang fr
  stories/documentation/forms/fileUpload/angular/basic.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3567 [select] autocomplete off by default
  packages/ng/date2/date-range-input/date-range-input.component.html
  packages/ng/date2/date-range-input/date-range-input.component.ts
  packages/ng/multi-select/displayer/default-displayer.component.ts
  packages/ng/simple-select/input/select-input.component.html
  packages/ng/simple-select/input/select-input.component.ts
Labels: :bookmark::sparkles: Feature

#3574 fix(date-range-input): input always disabled
  packages/ng/date2/date-range-input/date-range-input.component.html
Labels: :bookmark::bug: FIX

#3576 [Date range] Fix disabled state by default
  packages/ng/date2/date-range-input/date-range-input.component.html
Labels: :bookmark::bug: FIX

#3581 [icons] widget
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::bug: FIX

#3584 fix(rich-textfield): #3583 replace grey with neutral
  packages/scss/src/components/richText/vars.scss
Labels: 👥 UI, :bookmark::bug: FIX

#3586 fix(date-input): selecting initial value after a change doesn't reflect on model
  packages/ng/date2/date-input/date-input.component.ts
  stories/documentation/forms/fields/date/date-input-field.stories.ts
Labels: 👥 Front, :bookmark::bug: FIX

#3589 [icons] focus
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::bug: FIX

#3577 [QA] Add Date input & Date range input basic pages
  stories/qa/date-input/date-input.stories.html
  stories/qa/date-input/date-input.stories.ts
  stories/qa/date-range-input/date-range-input.stories.html
  stories/qa/date-range-input/date-range-input.stories.ts
Labels: :hammer: Technical

#3592 [Textarea] Set default rows value
  packages/ng/forms/textarea-input/textarea-input.component.ts
Labels: :bookmark::bug: FIX

#3591 [Index table] Fix button style with Angular import
  packages/scss/src/components/indexTable/index.scss
  packages/scss/src/components/indexTable/mods.scss
  stories/qa/index-table/index-table.stories.html
  stories/qa/index-table/index-table.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3596 fix(rich-text-input): fixed RTE autofocus when value is set programmatically
  packages/ng/forms/rich-text-input/rich-text-input.component.html
  packages/ng/forms/rich-text-input/rich-text-input.component.ts
Labels: :bookmark::bug: FIX

#3531 test(simple-select): add e2e tests
  .gitignore
  .storybook/main.mjs
  package-lock.json
  package.json
  packages/ng/core-select/input/select-input.component.ts
  stories/documentation/forms/fields/date/date-input-field.stories.ts
  stories/documentation/forms/select/multi-select.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3605 fix(rich-text-input): fixed RTE being marked as touched & dirty when initial value is set
  packages/ng/forms/rich-text-input/rich-text-input.component.ts
Labels: :bookmark::bug: FIX

#3590 doc(stylelint): Explain what to do with Github API rate limit…
  packages/stylelint-config/README.md
Labels: :hammer: Technical, :book: Documentation changes

#3566 [option] increase depth for nesting + reduce code
  packages/ng/option/item/tree-option-item.component.scss
Labels: :bookmark::sparkles: Feature

#3606 Don’t remove divider if form field is present
  packages/scss/src/components/filterBar/component.scss
Labels: :bookmark::bug: FIX

#3608 [19.3.1] master → rc
  docs/rich-text-input.md
  docs/user-popover.md
  package-lock.json
  package.json
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
  packages/ng/button/button.component.ts
  packages/ng/date2/date-input/date-input.component.ts
  packages/ng/forms/rich-text-input/formatters/html/html-formatter.ts
  packages/ng/forms/rich-text-input/formatters/html/ng-package.json
  packages/ng/forms/rich-text-input/formatters/html/public-api.ts
  packages/ng/forms/rich-text-input/formatters/index.ts
  packages/ng/forms/rich-text-input/formatters/markdown/markdown-formatter.ts
  packages/ng/forms/rich-text-input/formatters/markdown/ng-package.json
  packages/ng/forms/rich-text-input/formatters/markdown/public-api.ts
  packages/ng/forms/rich-text-input/plugins/list-format/list-format.command.ts
  packages/ng/forms/rich-text-input/rich-text-input.component.html
  packages/ng/forms/rich-text-input/rich-text-input.component.ts
  packages/ng/forms/textarea-input/textarea-input.component.ts
  packages/ng/package.json
  packages/ng/title/README.md
  packages/ng/title/title-translate.service.ts
  packages/ng/title/title.strategy.spec.ts
  packages/ng/title/title.strategy.ts
  packages/scss/src/components/filterBar/component.scss
  packages/scss/src/components/indexTable/index.scss
  packages/scss/src/components/indexTable/mods.scss
  packages/scss/src/components/navside/states.scss
  packages/scss/src/components/richText/index.scss
  packages/scss/src/components/richText/vars.scss
  stories/documentation/actions/button/angular/button-basic.stories.ts
  stories/documentation/actions/button/angular/button-icon.stories.ts
  stories/documentation/actions/button/html&css/button-disclosure.stories.ts
  stories/documentation/forms/fields/date/date-input-field.stories.ts
  stories/documentation/forms/fields/rich-text/angular/rich-text-input.stories.ts
  stories/documentation/forms/fileUpload/angular/basic.stories.ts
  stories/documentation/forms/select/simple-select.stories.ts
  stories/documentation/navigation/breadcrumbs/angular/breadcrumbs-basic.stories.ts
  stories/documentation/navigation/horizontalNavigation/angular/horizontalNavigation-basic.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-basic.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-container.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-count.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-scrollbox.stories.ts
  stories/documentation/overlays/dropdown/dropdown-component.stories.ts
  stories/documentation/structure/footer/angular/footer-basic.stories.ts
  stories/documentation/structure/footer/html&css/footer-basic.stories.ts
  stories/documentation/structure/highlight-data/angular/basic.stories.ts
  stories/documentation/texts/read-more/angular/read-more.stories.ts
  stories/qa/date-input/date-input.stories.html
  stories/qa/date-input/date-input.stories.ts
  stories/qa/date-range-input/date-range-input.stories.html
  stories/qa/date-range-input/date-range-input.stories.ts
  stories/qa/index-table/index-table.stories.html
  stories/qa/index-table/index-table.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes
