Repository LuccaSA/lucca-front, pull requests merged in 2025-06, with the labels that each got.

#3653 [Sidenav] Remove unwanted padding
  packages/scss/src/components/navside/mods.scss
  packages/scss/src/components/navside/states.scss
Labels: :bookmark::bug: FIX

#3637 [pageHeader] add leading and trailing slots
  packages/ng/page-header/page-header.component.html
  packages/scss/src/components/pageHeader/component.scss
  stories/documentation/structure/page-header/angular/page-header-basic.stories.ts
  stories/documentation/structure/page-header/html&css/page-header-leading-trailing.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3623 feat(dialog): allow for type overriding in data config
  packages/ng/dialog/dialog.service.ts
  packages/ng/dialog/model/dialog-config.ts
  packages/ng/dialog/model/dialog-ref.ts
Labels: :bookmark::sparkles: Feature, :hammer: Technical

#3609 [User popover] Update folder name
  docs/user-popover.md
  packages/ng/user-popover/README.md
  packages/ng/user-popover/card/panel/user-popover-panel.component.html
  packages/ng/user-popover/card/panel/user-popover-panel.component.scss
  packages/ng/user-popover/card/panel/user-popover-panel.component.ts
  packages/ng/user-popover/card/panel/user-popover-panel.model.ts
  packages/ng/user-popover/card/pipe/inject-parameter.pipe.ts
  packages/ng/user-popover/card/pipe/is-future.pipe.ts
  packages/ng/user-popover/card/pipe/leave-ends-display.pipe.ts
  packages/ng/user-popover/card/trigger/user-popover-trigger.directive.ts
  packages/ng/user-popover/ng-package.json
  packages/ng/user-popover/popup-employee.translate.ts
  packages/ng/user-popover/public-api.ts
  packages/ng/user-popover/service/user-popover-service.model.ts
  packages/ng/user-popover/service/user-popover.store.ts
  packages/ng/user-popover/translations.ts
  packages/ng/user-popover/user-popover.model.ts
  packages/ng/user-popover/user-popover.providers.ts
  stories/documentation/listings/index-table/index-table-actions-tooltipsRow.stories.ts
  stories/documentation/listings/index-table/index-table-actions-userPopover.stories.ts
  stories/documentation/users/avatars/angular/basic.stories.ts
  stories/documentation/users/display/with-popover.stories.ts
  stories/documentation/users/popover/angular/popover.stories.ts
  stories/documentation/users/tile/angular/user-tile.stories.ts
Labels: 💥 Breaking change, :hammer: Technical, :bookmark::bug: FIX, :book: Documentation changes

#3660 [filterBar] fix display
  packages/scss/src/components/filterBar/component.scss
Labels: :bookmark::bug: FIX

#3673 feat(lu-skeleton-field): add hiddenLabel input
  packages/ng/skeleton/skeleton-field/skeleton-field.component.html
  packages/ng/skeleton/skeleton-field/skeleton-field.component.ts
  stories/documentation/loaders/skeleton-field/angular/skeleton-field.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3662 feat(pagination): Add Pagination Angular component
  packages/ng/pagination/ng-package.json
  packages/ng/pagination/pagination.component.html
  packages/ng/pagination/pagination.component.ts
  packages/ng/pagination/pagination.translate.ts
  packages/ng/pagination/public-api.ts
  packages/ng/pagination/translations.ts
  stories/documentation/navigation/pagination/angular/pagination.stories.ts
  stories/documentation/navigation/pagination/html&css/pagination-basic.stories.ts
  stories/documentation/navigation/pagination/html&css/pagination-compact.stories.ts
  stories/documentation/navigation/pagination/html&css/pagination-pages.stories.ts
Labels: 👥 Front, 👥 UI, :bookmark::sparkles: Feature, :book: Documentation changes, :triangular_ruler: Angular wrapper

#3676 refactor(core-select): allow optionComparer override for api-v4
  packages/ng/core-select/api/api-v4.directive.ts
Labels: :hammer: Technical

#3658 [box] wrapper
  packages/ng/box/box.component.html
  packages/ng/box/box.component.scss
  packages/ng/box/box.component.ts
  packages/ng/box/ng-package.json
  packages/ng/box/public-api.ts
  packages/scss/src/components/filterBar/component.scss
  stories/documentation/structure/box/angular/basic.stories.ts
  stories/documentation/structure/box/html&css/box-arrow-ng.stories.ts
  stories/documentation/structure/box/html&css/box-arrow.stories.ts
  stories/documentation/structure/box/html&css/box-basic.stories.ts
  stories/documentation/structure/box/html&css/box-killable.stories.ts
  stories/documentation/structure/box/html&css/box-toggle.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3670 [appLayout] [mainLayout] new components + angular wrappers
  packages/ng/app-layout/app-layout.component.html
  packages/ng/app-layout/app-layout.component.scss
  packages/ng/app-layout/app-layout.component.ts
  packages/ng/app-layout/ng-package.json
  packages/ng/app-layout/public-api.ts
  packages/ng/main-layout/block/main-layout-block.component.ts
  packages/ng/main-layout/main-layout.component.html
  packages/ng/main-layout/main-layout.component.scss
  packages/ng/main-layout/main-layout.component.ts
  packages/ng/main-layout/ng-package.json
  packages/ng/main-layout/public-api.ts
  packages/ng/styles/components/cdk/_global.scss
  packages/ng/styles/definitions/select/_select-input.scss
  packages/scss/src/commons/vars.scss
  packages/scss/src/components/appLayout/component.scss
  packages/scss/src/components/appLayout/exports.scss
  packages/scss/src/components/appLayout/index.scss
  packages/scss/src/components/appLayout/mods.scss
  packages/scss/src/components/appLayout/states.scss
  packages/scss/src/components/appLayout/vars.scss
  packages/scss/src/components/container/component.scss
  packages/scss/src/components/container/index.scss
  packages/scss/src/components/container/mods.scss
  packages/scss/src/components/container/vars.scss
  packages/scss/src/components/fileEntry/component.scss
  packages/scss/src/components/fileUpload/component.scss
  packages/scss/src/components/filterBar/mods.scss
  packages/scss/src/components/filterPill/component.scss
  packages/scss/src/components/filterPill/mods.scss
  packages/scss/src/components/form/component.scss
  packages/scss/src/components/index.scss
  packages/scss/src/components/listing/component.scss
  packages/scss/src/components/mainLayout/component.scss
  packages/scss/src/components/mainLayout/exports.scss
  packages/scss/src/components/mainLayout/index.scss
  packages/scss/src/components/mainLayout/mods.scss
  packages/scss/src/components/mainLayout/states.scss
  packages/scss/src/components/mainLayout/vars.scss
  packages/scss/src/components/multiSelect/mods.scss
  packages/scss/src/components/navside/component.scss
  packages/scss/src/components/navside/index.scss
  packages/scss/src/components/navside/mods.scss
  packages/scss/src/components/pageHeader/component.scss
  packages/scss/src/components/richText/component.scss
  packages/scss/src/components/simpleSelect/mods.scss
  packages/scss/src/components/textField/component.scss
  stories/documentation/forms/fileDropzone/angular/basic.stories.ts
  stories/documentation/forms/fileToolbar/html&css/basic.stories.ts
  stories/documentation/structure/app-layout/angular/basic.stories.ts
  stories/documentation/structure/app-layout/html&css/basic.stories.ts
  stories/documentation/structure/main-layout/angular/basic.stories.ts
  stories/documentation/structure/main-layout/angular/inAppLayout.stories.ts
  stories/documentation/structure/main-layout/html&css/basic.stories.ts
  stories/documentation/structure/main-layout/html&css/inAppLayout.stories.ts
  stories/qa/fieldset/fieldset.stories.html
  stories/qa/footer/footer.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3683 chore(select-schematic): support `name` attribute as well as template references
  packages/ng/schematics/lu-select/util.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#3550 [scrollBox + filterBar] update
  packages/ng/filter-pills/filter-bar/filter-bar.component.html
  packages/ng/scrollBox/scroll-box.component.html
  packages/ng/scrollBox/scroll-box.component.ts
  packages/scss/src/components/filterBar/component.scss
  packages/scss/src/components/filterBar/mods.scss
  packages/scss/src/components/filterBar/vars.scss
  packages/scss/src/components/filterPill/mods.scss
  packages/scss/src/components/filterPill/vars.scss
  packages/scss/src/components/richText/component.scss
  packages/scss/src/components/scrollBox/component.scss
  packages/scss/src/components/scrollBox/states.scss
  packages/scss/src/components/scrollBox/vars.scss
  stories/documentation/forms/filterPills/html&css/filter-bar.stories.ts
  stories/documentation/navigation/horizontalNavigation/horizontalNavigation-scrollbox.stories.ts
  stories/documentation/structure/scroll-box/scroll-box-basic.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3693 [Table] Fix table shadow position
  packages/scss/src/components/tableSticked/mods.scss
Labels: :bookmark::bug: FIX

#3696 feat(number-format): currency style -> display a trailing 0 on fraction part if only 1 non-zero digit set
  packages/ng/number-format/number-format.spec.ts
  packages/ng/number-format/number-format.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#3692 [footer] display contents for wrapper
  packages/ng/footer/footer.component.scss
Labels: :bookmark::bug: FIX

#3681 [scrollBox] fix init
  packages/ng/scrollBox/scroll-box.component.ts
Labels: :bookmark::bug: FIX

#3663 fix: richtext placeholder was not shown at init when no content
  packages/ng/forms/rich-text-input/rich-text-input.component.ts
  stories/documentation/forms/fields/rich-text/angular/rich-text-input.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3661 Fix/richtext sanitize class
  packages/ng/forms/rich-text-input/formatters/html/html-formatter.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3700 [icons] checks
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#3674 chore(deps): angular 20, storybook 9
  .storybook/main.mjs
  .storybook/public/mockServiceWorker.js
  angular.json
  eslint.config.mjs
  package-lock.json
  package.json
  packages/ng/dialog/dialog-routing/dialog-routing.component.ts
  packages/ng/dialog/dialog-routing/dialog-routing.models.ts
  packages/ng/dialog/dialog-routing/dialog-routing.utils.ts
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
  tsconfig.json
Labels: 👥 Front, :hammer: Technical

#3705 Revert "chore(deps): angular 20, storybook 9"
  .storybook/main.mjs
  .storybook/public/mockServiceWorker.js
  angular.json
  eslint.config.mjs
  package-lock.json
  package.json
  packages/ng/dialog/dialog-routing/dialog-routing.component.ts
  packages/ng/dialog/dialog-routing/dialog-routing.models.ts
  packages/ng/dialog/dialog-routing/dialog-routing.utils.ts
  packages/ng/tooltip/trigger/tooltip-trigger.directive.ts
  tsconfig.json
Labels: :hammer: Technical

#3707 [pageHeader/pageFooter] container
  packages/ng/page-header/page-header.component.html
  packages/ng/page-header/page-header.component.ts
  packages/scss/src/commons/vars.scss
  packages/scss/src/components/container/index.scss
  packages/scss/src/components/container/mods.scss
  packages/scss/src/components/footer/component.scss
  packages/scss/src/components/footer/index.scss
  packages/scss/src/components/footer/mods.scss
  packages/scss/src/components/footer/vars.scss
  packages/scss/src/components/pageHeader/component.scss
  packages/scss/src/components/pageHeader/index.scss
  packages/scss/src/components/pageHeader/mods.scss
  packages/scss/src/components/pageHeader/vars.scss
  stories/documentation/structure/page-header/angular/page-header-basic.stories.ts
  stories/documentation/structure/page-header/html&css/page-header-container.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3715 [modal] fix class + [class]
  packages/ng/modal/modal-panel.component.html
Labels: :bookmark::bug: FIX

#3713 [Form field] Remove automatic inline with arrow
  packages/ng/form-field/form-field.component.html
  packages/ng/form-field/form-field.component.ts
  packages/ng/forms/radio-group-input/radio-group-input.component.ts
  stories/documentation/structure/box/html&css/box-arrow-ng.stories.ts
Labels: 💥 Breaking change, :bookmark::bug: FIX, :book: Documentation changes

#3711 fix(deps): update angular in ng package deps
  package-lock.json
  package.json
  packages/ng/package.json
Labels: :hammer: Technical

#3723 fix: various schematic fixes before release
  packages/ng/schematics/lu-button/migration.ts
  packages/ng/schematics/lu-button/tests/input/simple-cases.component.ts
  packages/ng/schematics/lu-button/tests/output/simple-cases.component.ts
  packages/ng/schematics/lu-icon/migration.ts
  packages/ng/schematics/lu-icon/tests/input/external-template.component.html
  packages/ng/schematics/lu-icon/tests/output/external-template.component.html
Labels: :bookmark::bug: FIX

#3664 feat(date2): allow reset instead of clear
  packages/ng/date2/abstract-date-component.ts
  packages/ng/date2/date-input/date-input.component.html
  packages/ng/date2/date-input/date-input.component.ts
  packages/ng/date2/date-range-input/date-range-input.component.html
  packages/ng/date2/date-range-input/date-range-input.component.ts
  packages/ng/date2/public-api.ts
  stories/documentation/forms/date2/date-input.stories.ts
  stories/documentation/forms/date2/date-range-input.stories.ts
  stories/documentation/forms/fields/date/date-input-field.stories.ts
Labels: 👥 Front, :bookmark::sparkles: Feature, :book: Documentation changes

#3679 chore(stylelint-deps): Update deps from stylelint config
  package-lock.json
  package.json
  packages/scss/src/components/field/component.scss
  packages/stylelint-config/package-lock.json
  packages/stylelint-config/package.json
  packages/stylelint-config/stylelint.config.mjs
Labels: 💥 Breaking change, :hammer: Technical

#3728 20.1 format.stories
  stories/documentation/feedback/mobile-push/html&css/mobile-push-basic.stories.ts
  stories/documentation/forms/date2/date-input.stories.ts
  stories/documentation/forms/date2/date-range-input.stories.ts
  stories/documentation/forms/fields/date/date-input-field.stories.ts
  stories/documentation/forms/input-framed/angular/basic.stories.ts
  stories/documentation/forms/input-framed/angular/checkbox.stories.ts
  stories/documentation/forms/input-framed/angular/grid.stories.ts
  stories/documentation/forms/input-framed/angular/illustrations.stories.ts
  stories/documentation/forms/input-framed/angular/infos.stories.ts
  stories/documentation/forms/input-framed/angular/panels.stories.ts
  stories/documentation/forms/input-framed/angular/states.stories.ts
  stories/documentation/forms/input-framed/angular/tag.stories.ts
  stories/documentation/forms/input-framed/html&css/basic.stories.ts
  stories/documentation/forms/input-framed/html&css/checkbox.stories.ts
  stories/documentation/forms/input-framed/html&css/grid.stories.ts
  stories/documentation/forms/input-framed/html&css/illustrations.stories.ts
  stories/documentation/forms/input-framed/html&css/infos.stories.ts
  stories/documentation/forms/input-framed/html&css/panels.stories.ts
  stories/documentation/forms/input-framed/html&css/states.stories.ts
  stories/documentation/forms/input-framed/html&css/tag.stories.ts
  stories/documentation/listings/listing/angular/basic.stories.ts
  stories/documentation/listings/listing/angular/checklist.stories.ts
  stories/documentation/listings/listing/angular/icons.stories.ts
  stories/documentation/listings/listing/angular/ordered.stories.ts
  stories/documentation/listings/listing/html&css/basic.stories.ts
  stories/documentation/listings/listing/html&css/checklist.stories.ts
  stories/documentation/listings/listing/html&css/icons.stories.ts
  stories/documentation/listings/listing/html&css/ordered.stories.ts
  stories/documentation/structure/box/html&css/box-basic.stories.ts
  stories/documentation/structure/box/html&css/box-killable.stories.ts
  stories/documentation/structure/box/html&css/box-toggle.stories.ts
  stories/documentation/structure/cards/cards-arrow-action.stories.ts
  stories/documentation/structure/cards/cards-clickable.stories.ts
  stories/documentation/structure/cards/cards-footer.stories.ts
  stories/documentation/structure/fancy-box/html&css/fancy-box-basic.stories.ts
  stories/documentation/structure/footer/angular/footer-basic.stories.ts
  stories/documentation/structure/footer/html&css/footer-basic.stories.ts
  stories/documentation/structure/page-header/angular/page-header-basic.stories.ts
  stories/documentation/structure/page-header/html&css/page-header-back.stories.ts
  stories/documentation/structure/page-header/html&css/page-header-basic.stories.ts
  stories/documentation/structure/page-header/html&css/page-header-breadcrumb.stories.ts
  stories/documentation/structure/page-header/html&css/page-header-container.stories.ts
  stories/documentation/structure/page-header/html&css/page-header-leading-trailing.stories.ts
  stories/documentation/structure/page-header/html&css/page-header-menu.stories.ts
  stories/documentation/texts/text/text.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3730 [listing] fix default icon
  packages/ng/listing/listing-item/listing-item.component.html
  packages/ng/listing/listing-item/listing-item.component.ts
  packages/ng/listing/listing.component.ts
  stories/documentation/listings/listing/angular/basic.stories.ts
  stories/documentation/listings/listing/angular/checklist.stories.ts
  stories/documentation/listings/listing/angular/icons.stories.ts
  stories/documentation/listings/listing/angular/ordered.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3733 [userPopover] keyboard navigation
  docs/user-popover.md
  packages/ng/popover2/popover.directive.ts
  packages/ng/user-popover/card/trigger/lu-user-popover.directive.ts
  packages/scss/src/components/userPopover/component.scss
  stories/documentation/listings/index-table/index-table-actions-userPopover.stories.ts
  stories/documentation/users/avatars/angular/basic.stories.ts
  stories/documentation/users/display/with-popover.stories.ts
  stories/documentation/users/popover/angular/popover.stories.ts
  stories/documentation/users/tile/angular/user-tile.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes
