Repository LuccaSA/lucca-front, pull requests merged in 2025-02, with the labels that each got.

#3361 Remove titles spacing
  packages/scss/src/commons/base.scss
  packages/scss/src/commons/config.scss
  packages/scss/src/components/emptyState/component.scss
  packages/scss/src/components/errorPage/component.scss
  packages/scss/src/components/index.scss
  packages/scss/src/components/textFlow/component.scss
  packages/scss/src/components/textFlow/exports.scss
  packages/scss/src/components/textFlow/index.scss
  packages/scss/src/components/textFlow/mods.scss
  packages/scss/src/components/textFlow/states.scss
  packages/scss/src/components/textFlow/vars.scss
  packages/scss/src/components/title/component.scss
  stories/documentation/texts/text-flow/html&css/basic.stories.ts
  stories/qa/text-flow/text-flow.stories.html
  stories/qa/text-flow/text-flow.stories.ts
Labels: :bookmark::sparkles: Feature, :hammer: Technical, :book: Documentation changes

#3354 v4 departments : scopedtree
  packages/ng/department/service/department-v4.service.ts
Labels: :hammer: Technical

#3382 feat(core-select): add a noClue directive to disable apiV3/V4 search
  packages/ng/core-select/input/select-input.component.spec.ts
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/no-clue/index.ts
  packages/ng/core-select/no-clue/no-clue.directive.spec.ts
  packages/ng/core-select/no-clue/no-clue.directive.ts
  packages/ng/core-select/public-api.ts
  stories/documentation/forms/select/simple-select.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3378 [icons] add plan and aid
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::bug: FIX

#3386 [numericBadge] maxValue
  packages/ng/numeric-badge/numeric-badge.component.html
  packages/ng/numeric-badge/numeric-badge.component.ts
  packages/scss/src/components/numericBadge/component.scss
  packages/scss/src/components/numericBadge/index.scss
  packages/scss/src/components/numericBadge/states.scss
  stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3363 Remove breadcrumb semantic for compact mode
  stories/documentation/navigation/breadcrumbs/breadcrumbs-compact.stories.ts
  stories/documentation/structure/page-header/page-header-back.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3390 [emptyState] no action
  packages/scss/src/components/emptyState/component.scss
Labels: :bookmark::bug: FIX

#3389 [formLabel] S alignement
  packages/scss/src/components/formLabel/component.scss
  stories/documentation/forms/fields/checkbox/angular/checkboxfield.stories.ts
  stories/documentation/forms/fields/date/date-input-field.stories.ts
  stories/documentation/forms/fields/form-field-nested-controls.stories.ts
  stories/documentation/forms/fields/form-field.stories.ts
  stories/documentation/forms/fields/multi-select/angular/multi-select.stories.ts
  stories/documentation/forms/fields/multilanguage/angular/multilanguagefield.stories.ts
  stories/documentation/forms/fields/number/angular/numberfield.stories.ts
  stories/documentation/forms/fields/simple-select/angular/simple-select.stories.ts
  stories/documentation/forms/fields/switch/angular/switchfield.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/fields/textarea/angular/textareafield.stories.ts
  stories/documentation/forms/fields/textarea/html&css/textareafield.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3388 [indexTable] wider backgrounds
  packages/scss/src/components/indexTable/mods.scss
  packages/scss/src/components/indexTable/vars.scss
Labels: :bookmark::bug: FIX

#3372 [utils] overflow block
  packages/ng/styles/components/cdk/_global.scss
  packages/scss/src/commons/utils/overflow.scss
  packages/scss/src/components/layout/states.scss
  packages/scss/src/components/navside/states.scss
Labels: :bookmark::sparkles: Feature

#3387 [QA] Compact stories - first batch
  .storybook/styles.scss
  stories/qa/_sample/sample.stories.html
  stories/qa/avatar/avatar.stories.html
  stories/qa/box/box.stories.html
  stories/qa/breadcrumb/breadcrumb.stories.html
  stories/qa/callout/callout.stories.html
  stories/qa/card/card.stories.html
  stories/qa/chip/chip.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#3395 [formFields] width mixin
  packages/scss/src/commons/config.scss
  packages/scss/src/components/form/index.scss
  packages/scss/src/components/form/mods.scss
Labels: :bookmark::sparkles: Feature

#3364 docs(pagination): replace "aria-labelledby" with "aria-label"
  stories/documentation/listings/index-table/index-table-mass-selection-and-pagination.stories.ts
  stories/documentation/navigation/pagination/pagination-basic.stories.ts
  stories/documentation/navigation/pagination/pagination-compact.stories.ts
  stories/documentation/navigation/pagination/pagination-pages.stories.ts
  stories/qa/pagination/pagination.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3396 fix(multi-select): wrong selection/unselection when manually selectin…
  packages/ng/core-select/establishment/establishment-grouping.component.ts
  packages/ng/multi-select/input/select-all/with-select-all.directive.ts
  packages/ng/multi-select/input/select-input.component.ts
Labels: :bookmark::bug: FIX

#3397 [link] fix label
  packages/ng/link/link.component.ts
Labels: :bookmark::bug: FIX

#3399 [filterPills] fix period keyboard navigation
  packages/ng/date2/date-range-input/date-range-input.component.html
Labels: :bookmark::bug: FIX

#3367 [multiSelect] remove placeholder when input is not used
  packages/ng/core-select/api/api.directive.spec.ts
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/multi-select/input/select-input.component.spec.ts
  packages/scss/src/components/multiSelect/index.scss
  packages/scss/src/components/multiSelect/states.scss
Labels: :bookmark::sparkles: Feature

#3402 [filterPills] fix focus visible for checkboxes
  packages/scss/src/components/filterPill/index.scss
Labels: :bookmark::bug: FIX

#3403 [Page header] Actions gap
  packages/scss/src/components/pageHeader/component.scss
Labels: :bookmark::bug: FIX

#3406 [Dropdown] Storybook DOM typo
  stories/documentation/overlays/dropdown/dropdown-basic.stories.ts
Labels: :bookmark::bug: FIX

#3410 [19.2] Format stories
  stories/documentation/forms/fields/phone-number-input/angular/phone-number-input.stories.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
  stories/documentation/forms/filterPills/angular/filter-bar.stories.ts
  stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
  stories/documentation/texts/status-badge/angular/status-badge-angular.stories.ts
  stories/documentation/texts/text-flow/html&css/basic.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3411 [19.2] Format doc 2
  stories/documentation/forms/fields/text/html&css/textfield-width.stories.ts
  stories/documentation/forms/filterPills/angular/filter-bar.stories.ts
  stories/documentation/forms/filterPills/angular/filter-pills.stories.ts
  stories/documentation/listings/chip/angular/basic.stories.ts
Labels: :hammer: Technical

#3413 [19.2] Fix modal title padding
  packages/ng/styles/components/_popup.scss
Labels: :bookmark::bug: FIX

#3420 [Icons] Add smile & megaphone
  packages/icons/font/lucca-icons.svg
  packages/icons/font/lucca-icons.ttf
  packages/icons/font/lucca-icons.woff
  packages/icons/font/lucca-icons.woff2
  packages/icons/icons-list.ts
  packages/icons/index.d.ts
  packages/icons/selection.json
  packages/icons/src/commons/config.scss
Labels: :bookmark::sparkles: Feature

#3424 [Empty states section] Fix width width on Angular component
  packages/ng/empty-state/empty-state-section/empty-state-section.component.scss
Labels: :bookmark::bug: FIX

#3407 fix(number-format): touched should be triggered even if value has not been changed
  packages/ng/number-format/number-format.directive.ts
Labels: :bookmark::bug: FIX

#3404 Fix some margins
  packages/scss/src/components/textFlow/component.scss
Labels: :bookmark::bug: FIX

#3415 docs: add new display name user popover story and improve existing user-related stories with popover
  packages/ng/popup-employee/card/trigger/user-popover-trigger.directive.ts
  stories/documentation/users/avatars/angular/basic.stories.ts
  stories/documentation/users/display/with-popover.stories.ts
  stories/documentation/users/tile/angular/user-tile.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3422 [Select] Fix multiple chip overflow
  packages/ng/styles/definitions/select/_select-input.scss
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3421 [Simple & Multi select] Display search icon when component has search
  packages/ng/multi-select/input/select-input.component.html
  packages/ng/simple-select/input/select-input.component.html
  packages/scss/src/components/multiSelect/component.scss
  packages/scss/src/components/multiSelect/index.scss
  packages/scss/src/components/multiSelect/states.scss
  packages/scss/src/components/simpleSelect/component.scss
  packages/scss/src/components/simpleSelect/index.scss
  packages/scss/src/components/simpleSelect/states.scss
Labels: :bookmark::sparkles: Feature

#3423 feat(schematics): add cdn-urls schematic
  packages/ng/plg-push/plg-push.component.html
  packages/ng/schematics/cdn-urls/index.ts
  packages/ng/schematics/cdn-urls/migration.spec.ts
  packages/ng/schematics/cdn-urls/migration.ts
  packages/ng/schematics/cdn-urls/schema.json
  packages/ng/schematics/cdn-urls/tests/template.input.html
  packages/ng/schematics/cdn-urls/tests/template.output.html
  packages/ng/schematics/collection.json
  stories/qa/avatar/avatar.stories.html
  stories/qa/plg-push/plg-push.stories.html
  stories/qa/user-tile/user-tile.stories.html
Labels: :hammer: Technical, :book: Documentation changes

#3426 [Textfield] Update search icon in Angular component
  packages/ng/forms/text-input/text-input.component.ts
  stories/documentation/forms/fields/text/angular/textfield.stories.ts
Labels: :bookmark::bug: FIX

#3430 [numericBadge] disable tooltip option
  packages/ng/modal/dialog-adapter/dialog-content-adapter/dialog-content-adapter.component.html
  packages/ng/multi-select/input/select-all/multi-select-all-displayer.component.ts
  packages/ng/numeric-badge/numeric-badge.component.html
  packages/ng/numeric-badge/numeric-badge.component.ts
  stories/documentation/actions/button/angular/button-counter.stories.ts
  stories/documentation/texts/numeric-badge/angular/numeric-badge.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3432 [Numeric badge] Fix inherited color
  packages/scss/src/components/numericBadge/mods.scss
Labels: :bookmark::bug: FIX

#3434 [scrollBox] fix menu
  stories/documentation/navigation/menu/menu-scrollbox.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3427 fix sticky with sort
  packages/scss/src/components/dataTableSticked/mods.scss
Labels: :bookmark::bug: FIX

#3405 chore: remove allowSignalWrites options in effect
  packages/ng/date2/calendar2/calendar2.component.ts
  packages/ng/date2/date-input/date-input.component.ts
  packages/ng/date2/date-range-input/date-range-input.component.ts
Labels: 👥 Front, :hammer: Technical

#3454 fix(form-filed): invalid status when invalid input is provided
  packages/ng/form-field/form-field.component.ts
Labels: :bookmark::bug: FIX

#3439 [Select (deprecated)] Fix line break
  packages/ng/api/select/input/api-select-input.component.html
  packages/ng/formly/types/select.html
  packages/ng/styles/definitions/select/_select-input.scss
Labels: :bookmark::bug: FIX

#3436 [dataTable] fix overflow with WebKit
  packages/scss/src/components/dataTable/component.scss
Labels: :bookmark::bug: FIX

#3455 fix(schematics): use direct function imports instead of global ts
  packages/ng/schematics/lib/angular-component-ast.ts
  packages/ng/schematics/lib/lf-schematic-context.ts
  packages/ng/schematics/lu-select/index.ts
  packages/ng/schematics/lu-select/migration.ts
  packages/ng/schematics/lu-select/tests/input/setupJest.ts
  packages/ng/schematics/lu-select/tests/output/setupJest.ts
  packages/ng/schematics/lu-select/util.ts
Labels: :hammer: Technical, :bookmark::bug: FIX

#3456 [User Tile] Fix height calculation when role is empty
  packages/ng/user/tile/user-tile.component.html
Labels: :bookmark::bug: FIX

#3457 [table] Fix text align inheritance
  packages/scss/src/components/table/component.scss
Labels: :bookmark::bug: FIX

#3459 feat(lu-form-field): allow string to width input
  packages/ng/form-field/form-field.component.ts
Labels: :bookmark::sparkles: Feature

#3458 [Phone number] Prevent search icon
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/forms/phone-number-input/phone-number-input.component.html
  packages/scss/src/components/multiSelect/index.scss
  packages/scss/src/components/simpleSelect/index.scss
Labels: :bookmark::bug: FIX

#3463 [19.2.1] Update RC
  packages/ng/api/select/input/api-select-input.component.html
  packages/ng/core-select/api/api.directive.spec.ts
  packages/ng/core-select/establishment/establishments.directive.ts
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/core-select/panel/key-manager.ts
  packages/ng/core-select/panel/panel.utils.ts
  packages/ng/core-select/user/users.directive.spec.ts
  packages/ng/core-select/user/users.directive.ts
  packages/ng/date2/abstract-date-component.ts
  packages/ng/date2/calendar2/calendar2.component.ts
  packages/ng/date2/date-range-input/date-range-input.component.ts
  packages/ng/form-field/form-field.component.ts
  packages/ng/formly/types/select.html
  packages/ng/forms/phone-number-input/phone-number-input.component.html
  packages/ng/forms/phone-number-input/phone-number-input.component.ts
  packages/ng/forms/textarea-input/textarea-input.component.ts
  packages/ng/schematics/lib/angular-component-ast.ts
  packages/ng/schematics/lib/lf-schematic-context.ts
  packages/ng/schematics/lu-select/index.ts
  packages/ng/schematics/lu-select/migration.ts
  packages/ng/schematics/lu-select/tests/input/setupJest.ts
  packages/ng/schematics/lu-select/tests/output/setupJest.ts
  packages/ng/schematics/lu-select/util.ts
  packages/ng/styles/definitions/select/_select-input.scss
  packages/ng/user/tile/user-tile.component.html
  packages/scss/src/components/dataTable/component.scss
  packages/scss/src/components/dataTableSticked/mods.scss
  packages/scss/src/components/multiSelect/index.scss
  packages/scss/src/components/simpleSelect/index.scss
  packages/scss/src/components/table/component.scss
  packages/scss/src/components/tag/component.scss
  stories/documentation/forms/fields/textarea/angular/textareafield.stories.ts
  stories/documentation/navigation/menu/menu-scrollbox.stories.ts
  stories/documentation/structure/box/box-arrow.stories.ts
  stories/qa/box/box.stories.html
Labels: :hammer: Technical, :bookmark::bug: FIX, :book: Documentation changes
