Repository LuccaSA/lucca-front, pull requests merged in 2025-09, with the labels that each got.

#3870 [readMore] fix line break for disabled state
  packages/scss/src/components/readMore/states.scss
Labels: :bookmark::bug: FIX

#3871 [readMore] fix detection for contents with lists or headings
  packages/scss/src/components/readMore/component.scss
  packages/scss/src/components/textFlow/component.scss
Labels: :bookmark::bug: FIX

#3864 fix(richtext): Resolve some scss on tag chips
  packages/ng/forms/rich-text-input/plugins/tag/tag-node.ts
  packages/ng/forms/rich-text-input/plugins/tag/tag.component.html
  packages/scss/src/components/richText/component.scss
Labels: :bookmark::bug: FIX

#3863 fix(rich-text): add optional parameter when tabindex is set
  packages/ng/forms/rich-text-input/rich-text-input.component.ts
Labels: :bookmark::bug: FIX

#3874 [pagination] fix documentation
  docs/pagination.md
Labels: :bookmark::bug: FIX

#3876 [skeleton] fix square default radius
  packages/scss/src/components/skeleton/mods.scss
Labels: :bookmark::bug: FIX

#3875 fix(button): keep original palette while loading/success
  packages/scss/src/components/button/states.scss
Labels: :bookmark::bug: FIX

#3904 [Fieldset] Improve stories
  stories/documentation/forms/fieldset/angular/fieldset-basic.stories.ts
  stories/documentation/forms/fieldset/html&css/fieldset-basic.stories.ts
Labels: :hammer: Technical, :book: Documentation changes

#3896 [scss] linter
  packages/ng/multi-select/panel/panel.component.scss
  packages/ng/simple-select/panel/panel.component.scss
  packages/scss/src/commons/vars.scss
  packages/scss/src/components/button/states.scss
Labels: :hammer: Technical

#3891 [dataTable] fix background for groups
  packages/scss/src/components/dataTable/mods.scss
Labels: :bookmark::bug: FIX

#3890 [Fieldset] fix story
  stories/documentation/forms/fieldset/angular/fieldset-basic.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3885 [button] fix states with counter
  packages/scss/src/components/button/states.scss
  packages/scss/src/components/numericBadge/states.scss
Labels: :bookmark::bug: FIX

#3880 [userPopover] skeleton
  packages/ng/user-popover/card/trigger/user-popover.component.html
  packages/ng/user-popover/card/trigger/user-popover.component.ts
  packages/scss/src/components/userPopover/component.scss
  stories/documentation/users/popover/html&css/skeleton.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3878 [segmentedControl] wrappers angular for filters and tabs
  packages/ng/segmentedControl/filter/filter.component.html
  packages/ng/segmentedControl/filter/filter.component.ts
  packages/ng/segmentedControl/ng-package.json
  packages/ng/segmentedControl/public-api.ts
  packages/ng/segmentedControl/segmented-control.component.scss
  packages/ng/segmentedControl/segmented-control.component.ts
  packages/ng/segmentedControl/segmented-control.token.ts
  packages/ng/segmentedControlTabs/ng-package.json
  packages/ng/segmentedControlTabs/panel/panel.component.ts
  packages/ng/segmentedControlTabs/public-api.ts
  packages/ng/segmentedControlTabs/segmented-control-tabs.component.html
  packages/ng/segmentedControlTabs/segmented-control-tabs.component.scss
  packages/ng/segmentedControlTabs/segmented-control-tabs.component.ts
  packages/ng/segmentedControlTabs/segmented-control-tabs.token.ts
  packages/scss/src/components/segmentedControl/component.scss
  stories/documentation/navigation/segmentedControl/angular/segmentedControl.stories.ts
  stories/documentation/navigation/segmentedControl/angular/segmentedControlTabs.stories.ts
  stories/documentation/navigation/segmentedControl/html&css/segmentedControl-filter.stories.ts
  stories/documentation/navigation/segmentedControl/html&css/segmentedControl-tabs.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3867 [inputFramed] mod-alignCenter
  packages/ng/form-field/framed-input/framed-input.component.html
  packages/ng/form-field/framed-input/framed-input.component.ts
  packages/ng/forms/radio-group-input/radio-group-input.component.ts
  packages/ng/forms/radio-group-input/radio/radio.component.html
  packages/ng/forms/radio-group-input/radio/radio.component.ts
  packages/scss/src/components/inputFramed/component.scss
  packages/scss/src/components/inputFramed/index.scss
  packages/scss/src/components/inputFramed/mods.scss
  packages/scss/src/components/inputFramed/vars.scss
  stories/documentation/forms/input-framed/angular/basic.stories.ts
  stories/documentation/forms/input-framed/html&css/alignCenter.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3901 feat(date): add panelOpen and panelClose events to date inputs
  packages/ng/core-select/input/select-input.component.ts
  packages/ng/date2/abstract-date-component.ts
  packages/ng/date2/date-input/date-input.component.html
  packages/ng/date2/date-range-input/date-range-input.component.html
  packages/ng/date2/date-range-input/date-range-input.component.ts
Labels: :bookmark::sparkles: Feature

#3922 fix(tree): total count on departments
  packages/ng/core-select/department/departments.directive.ts
Labels: :bookmark::bug: FIX

#3931 [indexTable] update stories for tooltips
  packages/scss/src/commons/core.scss
  stories/documentation/listings/index-table/index-table-actions-tooltipsCell.stories.ts
  stories/documentation/listings/index-table/index-table-actions-tooltipsRow.stories.ts
Labels: :bookmark::bug: FIX, :book: Documentation changes

#3928 refactor(prettier): use angular parser for more files
  .prettierrc
  packages/ng/formly/types/checkbox.html
  packages/ng/formly/types/radios.html
  packages/ng/formly/wrappers/helper.html
  packages/ng/formly/wrappers/icon.html
  packages/ng/formly/wrappers/suffix.html
  stories/documentation/listings/index-table/index-table-interactive-nested-selectable.stories.html
  stories/documentation/texts/icons/icon-basic.stories.html
  stories/documentation/users/display/display.stories.html
  stories/qa/empty-state/empty-state-page.stories.html
  stories/qa/icon/icon.stories.html
Labels: 👥 Front, :hammer: Technical, :book: Documentation changes, :see_no_evil: No log

#3937 [User popover] Remove Featflag documentation
  docs/user-popover.md
Labels: :hammer: Technical, :book: Documentation changes

#3921 fix(date): better handling of single-digit input on month and day
  packages/ng/date2/abstract-date-component.ts
  packages/ng/date2/date-format.ts
  packages/ng/date2/date-input/date-input.component.html
  packages/ng/date2/date-input/date-input.component.ts
Labels: :bookmark::bug: FIX

#3848 [gauge] add a mod circular
  packages/ng/gauge/gauge.component.html
  packages/ng/gauge/gauge.component.ts
  packages/ng/gauge/ng-package.json
  packages/ng/gauge/public-api.ts
  packages/scss/src/components/gauge/component.scss
  packages/scss/src/components/gauge/index.scss
  packages/scss/src/components/gauge/mods.scss
  packages/scss/src/components/gauge/states.scss
  packages/scss/src/components/gauge/vars.scss
  stories/documentation/loaders/gauge/angular/gauge-basic.stories.ts
  stories/documentation/loaders/gauge/gauge-basic.stories.ts
  stories/documentation/loaders/gauge/gauge-vertical.stories.ts
  stories/documentation/loaders/gauge/html&css/gauge-circular.stories.ts
  stories/documentation/loaders/gauge/html&css/gauge-horizontal.stories.ts
  stories/qa/gauge/gauge.stories.html
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3887 feat(date): new datePipeFormat input to force date pipe usage with specific format
  packages/ng/comment/comment/comment.component.html
  packages/ng/comment/comment/comment.component.ts
  stories/documentation/texts/comment/angular/basic.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3941 feat(multilanguage-input): new openOnFocus input to open panel on focus
  packages/ng/forms/multilanguage-input/multilanguage-input.component.html
  packages/ng/forms/multilanguage-input/multilanguage-input.component.ts
  stories/documentation/forms/fields/multilanguage/angular/multilanguagefield.stories.ts
Labels: :bookmark::sparkles: Feature, :book: Documentation changes

#3704 fix(date-range): #3689 removing effect to avoid null value emitted in…
  jest-global-setup.js
  jest.config.json
  packages/ng/date2/date-range-input/date-range-input.component.html
  packages/ng/date2/date-range-input/date-range-input.component.spec.ts
  packages/ng/date2/date-range-input/date-range-input.component.ts
Labels: 💥 Breaking change, :bookmark::bug: FIX, :book: Documentation changes
